### ISSUE TITLE
Consolidate the two redundant/conflicting cloud.gov incident response pages 

### ISSUE THREAD

**Issue by bengerman13** [cloud-gov/product#1051]
In order for an IC to be able to follow an orderly incident process, we need to have one single cloud.gov IR page instead of two pages (to accompany the 18F IR page).

**Background information**

We have 3 pages to consult for security incident responses. 
- [cloud.gov IR checklist][checklist]
- [cloud.gov IR guide][guide]
- [18F ir guide][18f]

They are in some cases redundant and in some cases contradictory, they contain circular references to each other, and in all cases it's a lot to look at.

We should either turn the [checklist page][checklist] into an actual checklist template, or merge it back into the [incident response page][guide]

[checklist]: https://cloud.gov/docs/ops/security-ir-checklist/
[guide]: https://cloud.gov/docs/ops/security-ir/
[18f]: https://handbook.18f.gov/security-incidents/

## Follow-on

Run the [IR exercise](https://github.com/cloud-gov/product/issues/1436)

## 2020-12-16

Resources:

https://docs.google.com/document/d/1AfX93aSNfcaMAwekFkrK0KZhuxA4KHGAgN_YFkqDUQM/edit#

https://sre.google/workbook/incident-response/

https://response.pagerduty.com/

**Acceptance criteria**

- [ ] We have one single cloud.gov IR page that has a linear section for an IR to follow in an incident 
- [ ] The deleted one redirects to the central one

**Comment by karareinsel** [comment]
Our work is dependent on the work that is being done by TTS Infrastructure around incident response. Once they deconflict, then we'll be able to be added to the TTS plan. Blocked for now.

**Comment by bengerman13** [comment]
blocked by 18F/tts-tech-portfolio#77

**Comment by karareinsel** [comment]
TTS has committed to having these de-conflicted by the end of January 2020.

**Comment by pburkholder** [comment]
Discussing with FedRAMP as part of our PMI letter: https://docs.google.com/document/d/15SPpgJtMkK3yK_Ya-b6VBo1OjG5Ttd1ZXloefX8AYRc/edit

**Comment by pburkholder** [comment]
@hillaryj Can you link here to the Mural you put together?

**Comment by hillaryj** [comment]
Mural of the in-progress drafting of an IR workflow diagram:
https://app.mural.co/t/gsa6/m/gsa6/1578454101053/2be4f2baba395ba881353094f668cd4ef22559b8

**Comment by hillaryj** [comment]
Also some comments that I'm bringing to IR:
- Contractors on cloud.gov are currently unable to access the security-incidents repo and file this GH issue
- Cloud.gov needs to notify JAB/FedRAMP stakeholders

**Comment by its-a-lisa** [comment]
@hillaryj -- to clarify, when you mention contractors, you mean contractors supporting cloud.gov and not an application owner, correct?

**Comment by hillaryj** [comment]
Correct - we have contractors on our platform engineering team.

**Comment by karareinsel** [comment]
This will eventually need to be split into two pieces of work- TTS stuff and cloud.gov stuff. We're verifying the proposed workflow and continuing to refine. Probably 3-4 more sprints before we have a proposed workflow.

**Comment by pburkholder** [comment]
Bumping this onto the Project Planning board since we need to still run an IR exercise and our IR guides 
- need to be more be more helpful
- need to have dates for "last updated/reviewed"

**Comment by pburkholder** [comment]
Related: these notes from routes w/o routers follow up yesterday:
```
StatusPage has been helpful and when we have serious long-running issues, we pick a person to keep things communicated out and noise to the team down
We’ve been getting better about this, but need to be on top of:
    Notes doc started
    Incident process kicked off
    IC determined
```

**Comment by pburkholder** [comment]
Notes related to 🎃 Halloween activity

- [ ] We need a "suspicious activity" support path, e.g. we let gsa-ir know.
