### ISSUE TITLE
Improving Kubernetes Alerting

### ISSUE THREAD

**Issue by mxplusb** [cloud-gov/product#1077]
# What we're after

Better alerting and metricking around Kubernetes metrics.

## Hypothesized benefit(s)/why:**
* Check if we have all the k8s-related reporting things in Grafana
* Include alerts for “approaching capacity” not just “at capacity”
* Identify key metrics per instance and cluster-wide for alerts and threshold values
  * Something to test/alert if HA clusters are all scheduled on the same node

## Potential metrics
* Grafana can display pods-per-node.

**Comment by karareinsel** [comment]
This issue needs to be further fleshed out/refined before an estimate can be provided. @bengerman13

**Comment by karareinsel** [comment]
Tackle in sprint after we finish the K8s scale out. Keep it as as research task.

**Comment by karareinsel** [comment]
Not for this sprint but split out this story into multiple smaller stories in the next backlog grooming (Nov. 12).

**Comment by mxplusb** [comment]
Now that k8s is stable (and has been for like a month), we should be able to review the metrics the node exporter puts out to determine what we want to metric on.
