### ISSUE TITLE
Import Logsearch and Logsearch Platform into Credhub

### ISSUE THREAD

**Issue by mxplusb** [cloud-gov/product#1111]
In order to get Logsearch Platform credentials into Credhub, we need to import Logsearch Platform's variables into Credhub.

## Acceptance Criteria

- [ ] Development Logsearch and Logsearch Platform manifest should be identical to existing manifest, but with variables pulled from Credhub.
- [ ] Staging Logsearch and Logsearch Platform manifest should be identical to existing manifest, but with variables pulled from Credhub.
- [ ] Production Logsearch and Logsearch Platform manifest should be identical to existing manifest, but with variables pulled from Credhub.

**Comment by karareinsel** [comment]
Hoping to address in the next sprint (20.1.24).

**Comment by mxplusb** [comment]
Blocked by: https://github.com/cloudfoundry/bosh-cli/pull/550

**Comment by mxplusb** [comment]
It turns out Spruce can actually generate a manifest without resolving all fields and then secrets can be resolved from Credhub, so this might be much easier than I originally thought.

**Comment by mxplusb** [comment]
This is currently blocked by https://github.com/18F/cg-deploy-logsearch/pull/178.

**Comment by mxplusb** [comment]
Poked the project owner of https://github.com/cloudfoundry/bosh-deployment-resource/pull/65 for an update.

**Comment by mxplusb** [comment]
It can be removed from the Project Planning board and added to the Credhub Epic, this can also be moved to the `deploy-logsearch` repo once it gets migrated over.
