### ISSUE TITLE
Log ingestors are not balancing load evenly

### ISSUE THREAD

**Issue by bengerman13** [cloud-gov/product#1159]
Logsearch-platform has 3 ingestors in production, but ingestor/0 always seems to get more load (based on CPU load graphs from grafana, and based on the fact that ingestor/0 will fall behind and start writing to its persistent queue while the other two ingestors are staying caught up.

We should figure out why this is and get the load balanced more evenly.

**Comment by hillaryj** [comment]
Priority is quickly rising. @bengerman13 is currently checking and fixing this manually. Prioritize in the next sprint.

**Comment by karareinsel** [comment]
@bengerman13 is in the process of implementing a possible fix - he will confirm if it's fixed. If so, close the issue. If it's not fixed, it'll be several sprints before it can be addressed.

**Comment by karareinsel** [comment]
@bengerman13 is this fixed? If so, we can close this issue.
