### ISSUE TITLE
cg-staging-kops IAM role security review

### ISSUE THREAD

**Issue by ChrisMcGowan** [cloud-gov/product#1189]
Review the cg-staging-kops user account rights and document

## Acceptance Criteria
TBD

--- 

## Security considerations
Review IAM roles assigned to cf-staging-kops in relation to elevated rights needed for kops to deploy and maintain k8s

## Implementation sketch
[links to background notes, sketches, and/or relevant documentation
* [ ] Review kops documentation on best practices post install
* [ ] Make adjustments to rights as needed to secure the account
* [ ] Complete any process/paperwork to document the rights needed

**Comment by pburkholder** [comment]
@ChrisMcGowan I understand that KOPS is gone, so closing this as no longer pertinent.
