### ISSUE TITLE
[bug] cloud.gov not showing in stratos 

### ISSUE THREAD

**Issue by eddietejeda** [cloud-gov/product#1206]
It appears the logo in the source code and assets, but its not displayed. 

https://github.com/18F/cg-deploy-stratos/tree/master/custom-src/frontend/assets 

Is the build breaking before the logo is copied?

## Why this matters.

Bad user experience. Users are logging into cloud.gov, not stratos.

**Comment by bengerman13** [comment]
it looks like the linking is happening - I wonder if the interface for linking changed?
``` 
 + Linking file   : /tmp/build/b9a8e74f/stratos-src/custom-src/frontend/assets/logo.png ==> /tmp/build/b9a8e74f/stratos-src/src/frontend/packages/core/assets/logo.png
```
