### ISSUE TITLE
Ensure AWS keys and other obvious secrets are not inadvertently committed to git or pushed to GitHub

### ISSUE THREAD

**Issue by pburkholder** [cloud-gov/product#1262]
## Problem and proposed solution 

The cloud.gov team has suffered several incidents over the last year when sensitive credentials have been inadvertently posted to public repositories in GitHub. This happens because early in our [change control management process](https://cloud.gov/docs/ops/configuration-management/), developers/operators save development code in GitHub. While developers should review the code additions/changes before `committing` or `pushing` code, it can happen that a file gets included, or a copy/paste section overlooked, that happens to include sensitive/private information.

To prevent such inadvertent sharing of sensitive data, we have historically instructed our developers to [install a leak prevention tool](https://github.com/18F/laptop#want-to-install-just-git-seekret), `git-seekrets`, during their on boarding. But we've not followed up on ensuring that the tool is installed, properly configured, and has a configuration to catch and prevent the types of credentials we work with.

Our plan to address this issue has the following components (and status as of 2020-04-01)

* Identify a better community-supported tool to detect secrets in Git, and prevent them from being committed.
  * This work has been completed by the TTS Tech Portfolio in identifying [gitleaks](https://github.com/zricethezav/gitleaks) - see https://github.com/18F/laptop/issues/185
* Make it easy for all cloud.gov team members to install, configure, and verify operation of leak prevention
  * This work, [caulking](https://github.com/cloud-gov/caulking), is feature-complete, has been deployed by all cloud.gov team members (except one who is having technical issues, and they are not an active developer), AND has been validated as functional by all relevant team members
  * This step is _the most important feature_ in leak prevention and is sufficient to prevent all incidents we've had to date. For this reason, we intend 3PAO assessment to focus on this feature.
* Ensure that event if the above steps fail, that we're less likely to leak `keys` that would allow a malicious actor to use those keys in our AWS accounts
  * This work is pending, but would entail extending `caulking` to set up `aws-vault` and audit that it works correctly.
* Review all GitHub repositories to see if there are previously-committed secrets still lurking in them
  * This is work is pending. It is lower-priority and lower-value, as our HackerOne reports show that white hats are already combing our repositories for such information.
* Rearchitect our AWS accounts so even without `aws-vault`, our developers would only use keys that are invalid after an hour or so.

## Security considerations

This is a key outcome from 2020-01-23 Postmortem summary AWS keys in github

## Implementation overview

1. Commit no more secrets to Git
    1. ensure test suite in `laptop` covers our use cases for potential secrets
    1. update the `laptop` repository with more patterns to match cloud.gov use cases
    1. use a bats script in `cg-script` to ensure operators have controls to prevent committing secrets
    1. Add a regular and periodic audit to verify the secret pre-commit hook is working on all dev laptops
    1. update documentation
1. Ensure we have no secrets now ~, or later~, in GitHub
    1. Choose a tool to scan all our repos for the patterns identified above and report back
    1. Use such a tool at least monthly, or regularly as a service, or continually as part of periodic process, like an existing pipeline, or a regular manual process
    1. Update documentation on how we scan and how to conduct such a scan to minimize false positives.
1. Stop using long-lived, unencrypted AWS credentials
    1. ~ensure `aws-vault` does indeed obviate the need for a file `~/.aws/credentials`~
    1. Ensure that AWS IAM policies enforce use of short-lived keys + MFA for all commandline access
    1. ensure onboarding includes covering in detail use of these tools and process.
    1. include in Bats script a check for `aws-vault` and absence of `~/.aws/credentials`
    1. Update documentation
1. Iterate and improve
    1. AWS: adopt better primary/secondary AWS account model to only used short-lived credentials for all operator access
    2. Git and GitHub: work with TTS tech portfolio for a supports/sustained git leak prevention tool
  
 
## Acceptance criteria

* [ ] All developers/engineers on cloud.gov can easily install leak prevention and generate a report showing it's installed and configured
* [ ] 3PAO has assessed leak prevention meets the above goal
* [ ] All developers/engineers on cloud.gov can easily install AWS credentials management and generate a report showing it's installed, configured and there are no cleartext credentials under `$HOME/.aws`
* [ ] cloud.gov has a periodic process for assessing local workstation configuration.

## Notes and related work:

* Work with TTS tech portfolio on a common approach https://github.com/18F/tts-tech-portfolio/issues/20
* https://blog.acolyer.org/2019/04/08/how-bad-can-it-git-characterizing-secret-leakage-in-public-github-repositories/
* Evaluate https://github.com/sds/overcommit and pre-commit
* AWS Vault: https://github.com/99designs/aws-vault
* Current cloud.gov secrets page: https://cloud.gov/docs/ops/secrets/ and https://github.com/cloud-gov/cg-site/blob/master/_docs/ops/secrets.md

* AWS work in this ticket: https://github.com/cloud-gov/cg-product/issues/1263

**Comment by karareinsel** [comment]
Must be completed within the next 30 days.

**Comment by hillaryj** [comment]
I found some good resources for secret scanning and patterns:

- GH token scanning info with some patterns https://help.github.com/en/github/administering-a-repository/about-token-scanning
- Article with links https://blog.acolyer.org/2019/04/08/how-bad-can-it-git-characterizing-secret-leakage-in-public-github-repositories/
- Tool called “Secret Beagle” https://github.com/atomist-blogs/secret-beagle
- Test data for “Dodgy” https://github.com/landscapeio/dodgy/tree/master/tests/testdata
- Secrets patterns https://adriancolyer.files.wordpress.com/2019/04/git-secrets-table-v.jpeg?w=520&h=542&zoom=2
- Secrets patterns https://adriancolyer.files.wordpress.com/2019/04/git-secrets-table-iii.jpeg
- Yelp’s detect secrets https://github.com/Yelp/detect-secrets/
    - This tool looks really comprehensive and useful! We can likely use some of their patterns at least, and it may be a candidate for switching tools

**Comment by hillaryj** [comment]
I looked through `overcommit` and it looks like a fairly heavy lift to get started. It's set up to be more of a framework than a deployable tool, so it's very powerful but doesn't ship with things we'd need right away.

**Comment by hillaryj** [comment]
`git-secrets`, per discussion with the larger team about secrets management, is essentially a maintained-by-not-us tool similar to `git-seekret` that has more rulesets but is less user-friendly in identifying what and where to fix exceptions. I haven't re-found the comment thread but if I do can post it here.

**Comment by pburkholder** [comment]
Evaluating new guidance from Tech Portfolio: https://github.com/18F/laptop/issues/185#issuecomment-593472618

**Comment by pburkholder** [comment]
Working with Coalfire to schedule assessment and reporting back to the JAB.

**Comment by pburkholder** [comment]
WIP now at https://github.com/pburkholder/caulking

**Comment by pburkholder** [comment]
JAB requires a 3PAO review, so working on closing the contracting loop.

**Comment by pburkholder** [comment]
@mheadd Since you're on Support interrupt -- could you please take the caulking repo, https://github.com/cloud-gov/caulking through the protect branches checklist at https://cloud.gov/docs/ops/configuration-management/#checklist-for-new-repositories? 

I can pair with you if that helps, but I don't have the perms to do this myself. Thanks

**Comment by mheadd** [comment]
@pburkholder I'm no longer an org admin, so not sure I have the permissions either. I think my permissions are the same as yours..? I'm not able to see `settings` option on that repo.

**Comment by bengerman13** [comment]
I also don't have access to this repo.... I think we may need @karareinsel, @RonWilliams, or @eddietejeda to update this.

**Comment by mheadd** [comment]
When we moved repos over from 18F, we associated them with teams but it looks like we missed a few. This repo may have already been in the org when we did this. @karareinsel and I no longer have org owner access.

**Comment by karareinsel** [comment]
@RonWilliams or @eddietejeda can you assist since Mark and I no longer have admin access?

**Comment by mheadd** [comment]
I'm happy to knock this one out if I can get temporary admin access to our Github org.

**Comment by pburkholder** [comment]
Additional work here:

- [ ] Update Security IR guide with better steps for GitHub secret leaks (remove right away, while other team members rotate). 
- [ ] Update IR training that team members practice removing secrets from a pushed branch.

**Comment by karareinsel** [comment]
I'm now a GH owner so @pburkholder let me know if/how I can help.

**Comment by pburkholder** [comment]
@karareinsel  -- To quote from an earlier attempt:
>  could you please take the caulking repo, https://github.com/cloud-gov/caulking through the protect branches checklist at https://cloud.gov/docs/ops/configuration-management/#checklist-for-new-repositories?

Let me know if I can help in a pairing session.

**Comment by pburkholder** [comment]
@cloud-gov/platform-ops 

I propose we add `self-managed-credentials` policy, https://github.com/cloud-gov/cg-provision/blob/master/terraform/modules/iam_role_policy/self_managed_credentials/policy.json, to our Administrators group. This would close out this issue's point #3, "Stop using long-lived, unencrypted AWS credentials", which I originally thought would have to be done client side.

The policy includes:

```
     {
          "Sid": "DenyAllExceptListedIfNoMFA",
          "Effect": "Deny",
          "NotAction": [
              "iam:CreateVirtualMFADevice",
              "iam:EnableMFADevice",
              "iam:GetUser",
              "iam:ListMFADevices",
              "iam:ListVirtualMFADevices",
              "iam:ResyncMFADevice",
              "sts:GetSessionToken"
          ],
```

Which as an explicit Deny will enforce MFA not only for console logins but also for access keys on the command line.  @RonWilliams and I already have this policy in place on our production account. 

I don't think we can do this yet in terraform, but instead would have to run something like this for each of our accounts:

```
aws iam attach-group-policy
          --group-name Administrators
          --policy-arn arn:aws-us-gov:iam::{aws-account-number}:policy/self-managed-credentials
```

Once this is in place, we'd need to use `aws-vault` which is already described in https://cloud.gov/docs/ops/secrets/.

I'd like a quorum of 👍 before asking someone to do this. Whaddya all think?

**Comment by tammersaleh** [comment]
I love the intention (`aws-vault` is great!), but I'm not an IAM expert so I worry that messing this up will lock us out of our AWS accounts.  Maybe it's in the thread above, but have we tried this on a single account first?

Also, what's stopping us from doing this via Terraform?  Do we not have TF configs to provision our admin users (maybe we do that by hand?)?

**Comment by pburkholder** [comment]
@tammersaleh 1) Absolutely we can do this with user accounts first with: `aws iam attach-user-policy --user-name tammer.saleh --policy-arn arn:aws-us-gov:iam::{aws-account-number}:policy/self-managed-credentials` (if you're willing)

2) We can do this in terraform but there's a delta between our human IAM settings and what's in Terraform, so I don't want to put cart of "normalizing all our IAM with Terraform" before this particular horse.

**Comment by spgreenberg** [comment]
This seems like a good area to add an automated test to verify these policies are in place. Without this, anyone with admin privileges could remove the policy, intentionally or inadvertently. 

Otherwise, I like the approach.

**Comment by pburkholder** [comment]
@tammersaleh @spgreenberg https://github.com/cloud-gov/internal-docs/pull/7 adds policy verification (and some other AWS IAM InSpec checks). Shall we start with one of you getting the policy attached to your user, then attach to the Administrators group?

**Comment by spgreenberg** [comment]
That seems like a fairly safe approach to check the functionality and expected outcome.

**Comment by pburkholder** [comment]
Removing ticket from project board in favor of tracking following task issues:

* #1364 
* https://github.com/cloud-gov/caulking/issues/5 -- proxy issue to make `caulking` more robust & usage.
* https://github.com/cloud-gov/private/issues/165
* https://github.com/cloud-gov/caulking/issues/20

**Comment by pburkholder** [comment]
This work is all complete except for cosmetic issue cloud-gov/caulking#5 -- proxy issue to make caulking more robust & usage. Closing
