### ISSUE TITLE
As an operator, I don't have long-lived AWS credentials in my env or on disk

### ISSUE THREAD

**Issue by pburkholder** [cloud-gov/product#1263]
In order to stop leaking AWS credentials, we want to use ephemeral tokens/credentials

## Acceptance Criteria
* [ ] GIVEN [a precondition] \
  AND [another precondition]
  WHEN [test step] \
  AND [test step] \
  THEN [verification step] \
  AND [verification step]

* [ ] Update cg-site secrets page
--- 

## Security considerations

This is a key outcome from 2020-01-23 Postmortem summary AWS keys in github

## Implementation sketch

* Look at current state of aws-vault, and use of Roles in AWS IAM
* Ask how login or other teams are doing this.

**Comment by karareinsel** [comment]
Must be completed within the next 30 days.

**Comment by pburkholder** [comment]
https://github.com/18F/cg-scripts/pull/114, WIP, and depends on https://github.com/18F/laptop/pull/191
