### ISSUE TITLE
AIDE boshrelease

### ISSUE THREAD

**Issue by bengerman13** [cloud-gov/product#1278]
We need to switch from Tripwire to AIDE. 
Step one is to create and AIDE boshrelease

**Comment by bengerman13** [comment]
Got back on this yesterday. 
AIDE now installs and runs, and its config passes self-test. 
I'm currently working on getting reports running and exporting to prometheus.
After that, I need to add some documentation and refine the rules a bit.

**Comment by pburkholder** [comment]
- [ ] Patch K8s to a specific version
- [ ] Log AIDE results to a discoverable
- [ ] Test watching /etc/passwd and so on with stricter rules
- [ ] ...
