### ISSUE TITLE
Migrate ELBs to v2

### ISSUE THREAD

**Issue by mxplusb** [cloud-gov/product#1279]
In order to properly scale and maintain cloud.gov, our ELB versions need to be upgraded from v1 to v2.

## Acceptance Criteria
GIVEN cloud.gov has multiple ELBs deployed
WHEN an operator looks in the console
THEN there are no Classic ELBs deployed

--- 

## Security considerations

None in particular, we might have to migrate public IPs for some things.

## Implementation sketch

* [ ] https://docs.aws.amazon.com/elasticloadbalancing/latest/userguide/migrate-to-application-load-balancer.html
* [ ] Figure out how to do this in terraform.
* [ ] Make sure we have the proper amount of scale for our network usage.

**Comment by mxplusb** [comment]
This might be related: https://cloud-gov.zendesk.com/agent/tickets/2198

Since we don't have a way to scale the networking stack on classic ELBs, we're limited to like 25GBps or something like that, which may not be enough overall throughput at the scale at which we are starting to operate.

**Comment by hillaryj** [comment]
Next step is to plan the migration path and schedule - may be worth delaying until splitting into different VPC environments for dev/etc but we may be running into scaling issues with our current ELBs.

**Comment by hillaryj** [comment]
Goal: determine migration plan and timeline in roughly the next 1-3 sprints.
