### ISSUE TITLE
Migrate from Postfix to G Suite for SMTP services

### ISSUE THREAD

**Issue by mxplusb** [cloud-gov/product#1280]
In order to have a stable SMTP relay, cloud.gov should explore migrating from Postfix to G Suite for `@cloud.gov` emails. [Source](https://gsa-tts.slack.com/archives/C09CR1Q9Z/p1581464329105500)

## Security considerations

Better DMARC/DKIM support with G Suite.

## Implementation sketch

* [ ] Test in dev with something
* [ ] Test in staging with something else.
* [ ] Determine where we're using the postfix user
* [ ] create robot gsuite user
* [ ] rotate credentials
* [ ] monitor postfix logs for usage
* [ ] shutdown postfix

**Comment by hillaryj** [comment]
Discussion: https://gsa-tts.slack.com/archives/C09CR1Q9Z/p1581464329105500

Next step:

- Research how to use G Suite for SMTP
- How much G Suite do we have for cloud.gov already vs needs to be procured? - will take pairing with Eddie

**Comment by hillaryj** [comment]
@eddietejeda What's the priority/timeline for this work?
