### ISSUE TITLE
As an operator, I no longer want to check the kibana date format

### ISSUE THREAD

**Issue by spgreenberg** [cloud-gov/product#1293]
The current support task list includes:

'In logs.fr.cloud.gov, go under “Management” -> “Advanced Settings” and check the Kibana timezone setting (dateFormat:tz) - it should be set to Browser. If anyone has changed it, change it back to Browser.'

https://cloud.gov/docs/ops/maintenance-list/#weekly-support-tasks

## Acceptance Criteria

The task is automated of the field is made immutable. 
The manual task is removed from the maintenance-list.

--- 

## Security considerations
None

**Comment by tammersaleh** [comment]
...or just figure out how to make it immutable.

**Comment by spgreenberg** [comment]
Excellent point!
