### ISSUE TITLE
As an operator on support, I don't want manually check for CVEs for elastic search and redis.

### ISSUE THREAD

**Issue by spgreenberg** [cloud-gov/product#1294]
The support tasks currently include: 

'- Check for any new CVEs in [Elasticsearch](https://www.cvedetails.com/vulnerability-list/vendor_id-13554/Elasticsearch.html), and [Redis](https://www.cvedetails.com/vulnerability-list/vendor_id-15183/product_id-31837/Pivotal-Software-Redis.html).'

https://cloud.gov/docs/ops/maintenance-list/

## Acceptance Criteria

CVEs for Elastic Search and Redis are automatically reported in slack. 
The manual task is removed from the support tasks page.

--- 

## Security considerations

~None~ Enhancement

**Comment by its-a-lisa** [comment]
I'd be interested to hear what ya'll have in mind for doing so; I can also check with some folks in DOD to see how they manage this...
