### ISSUE TITLE
Setup a Multi-AZ CloudFoundry Instance within Single Region

### ISSUE THREAD

**Issue by RonWilliams** [cloud-gov/product#1329]
In order to assess the technical complexity of deploying new CF Instances, we want to setup and deploy a new instance of CloudFoundry for prototyping use. 

### Additional Items
- [ ] An approximate number of days / hours for each staff member is documented within issue at time of completion.

**Comment by spgreenberg** [comment]
Clarification: every CF instance should be multi-AZ in a single region. Multi-AZ is a fully supported aspect production CF.

**Comment by RonWilliams** [comment]
@spgreenberg Thanks! I've updated the issue based on your feedback.

**Comment by karareinsel** [comment]
Details on this work can be found in the project repo.

**Comment by karareinsel** [comment]
Closing out.
