### ISSUE TITLE
k8s journey: Review existing AWS RDS Broker for viability for Redis/ES

### ISSUE THREAD

**Issue by ChrisMcGowan** [cloud-gov/product#1333]
As part of this journey we need to find a new home for a broker to run Redis/ES service instances.  This ticket is to review the existing AWS RDS broker - https://github.com/18F/aws-broker. to see if it's a viable candidate for the task.

## Acceptance Criteria
- [x] Code base is still viable
- [x] Code base is supportable by the current team (format, language, tools, etc)

--- 

## Security considerations
Note any issues with the existing code base, if these issues impact the broker expansion, and form an implementation plan (and ticket) to resolve these issues even if this broker is not selected.

## Implementation sketch
- [x] Provide the recommendation to the team on if this broker is a candidate
- [x] Provide a pros/cons list on using this broker base to support AWS Redis/ES
- [x] Provide a rough plan and timeline to convert this broker for use with AWS Redis/ES

**Comment by soutenniza** [comment]
RDS Broker uses the AWS golang APIs to create the RDS Service. 
The broker also is very generic and can be extended to support other services. This makes RDS broker the best candidate over S3 Broker to be used to deploy Redis/ES services.

Had a meeting with Kara and Chris and said I will give a better timeline after working with the broker for a week first.
