### ISSUE TITLE
k8s journey: Review existing AWS S3 Broker for viability for Redis/ES

### ISSUE THREAD

**Issue by ChrisMcGowan** [cloud-gov/product#1334]
As part of this journey we need to find a new home for a broker to run Redis/ES service instances.  This ticket is to review the existing AWS S3 broker - https://github.com/cloudfoundry-community/s3-broker to see if it's a viable candidate for the task.

## Acceptance Criteria
- [x] Code base is still viable
- [x] Code base is supportable by the current team (format, language, tools, etc)

--- 

## Security considerations
Note any issues with the existing code base, if these issues impact the broker expansion, and form an implementation plan (and ticket) to resolve these issues even if this broker is not selected.

## Implementation sketch
- [x] Provide the recommendation to the team on if this broker is a candidate
- [ ] Provide a pros/cons list on using this broker base to support AWS Redis/ES
- [ ] Provide a rough plan and timeline to convert this broker for use with AWS Redis/ES

**Comment by soutenniza** [comment]
For the S3 Broker:

S3 broker uses the AWS golang APIs which is same as the RDS Broker. 

The main reason for using RDS Broker to deploy services over S3 broker is due that S3 broker seems to be more customized to work with S3 only. This makes the RDS Broker a better candidate to be able to support other services.
