### ISSUE TITLE
k8s journey: Start AWS services rollout with Redis

### ISSUE THREAD

**Issue by ChrisMcGowan** [cloud-gov/product#1335]
As part of this journey we found a new home for our AWS services and now it's time to deploy our first new AWS service - Redis

## Acceptance Criteria
- [x] Make a new branch to test this code base in staging
- [x] Testing of the broker in CF Staging for viability
- [x] Map catalog/service to match as close as possible to legacy Redis service

--- 

## Security considerations
- Moved these to new ticket https://github.com/cloud-gov/product/issues/1383

## Implementation sketch
- [x] Have a working branch that is vetted/tested in staging
- [x] Have built out a concourse pipeline to deploy/upgrade the broker
- [x] Have developed documentation library for CG customers to use this new service

**Comment by soutenniza** [comment]
Will start testing initial broker changes in Dev this week.

**Comment by karareinsel** [comment]
Link to draft of customer announcement https://docs.google.com/document/d/1g8_2GKXFwWCwZaLKyxJ-9rFOvAJhY25yCmAQ65tQTvk/edit

**Comment by ChrisMcGowan** [comment]
@RonWilliams 

Here are the plan details we are looking at.

Service name:  redis
Doc link: Same as current- https://cloud.gov/docs/services/redis/ - we'll need to update the website with more plan details.
Image: generic redis icon

Plans:

- redis-single
  - single instance redis
  - Displayname: non-prod single redis5.0.6, persistent storage, 512Mb memory limit
  - Description: AWS Elasticache Redis 5.0.6 Single node non-prod use only
  - Free: true
  - Cost: 0 USD monthly
- redis-3node
  - three node redis instance
  - Displayname: 3 node redis5.0.6, persistent storage, 512Mb memory limit
  - Description: AWS Elasticache Redis 5.0.6 Three node
  - Free: false
  - Cost: 99.99 USD monthly
- redis-5node
  - five node redis instance
  - Displayname: 5 node redis5.0.6, persistent storage, 512Mb memory limit
  - Description: AWS Elasticache Redis 5.0.6  Five node
  - Free: false
  - Cost: 199.99 USD monthly

Not sure if you wanted to leave the single plan free or not for sandbox/testing.  The other 3/5 node amounts are place holders and I can update once you have pricing.

In all three plans we have the following enabled as offered by AWS:

- nightly snapshots are enabled done between 01:30 - 02:30 UTC - going to move that forward to 4:30 - 5:30 UTC before we launch
- Weekly AWS maintenance support window Sundays 23:00 - 1:00 UTC - again going to move forward to 6:30 - 7:30 UTC before we launch
- Single plan gets 1 snapshot retention limit - 3/5 node get 3 snapshot retention limit

As of right now we are using cache.t3.micro instance types for all three plans since the memory space matches the legacy redis plans on k8s.

For the beta launch all instances will be created using the highest redis engine level AWS supports at the moment which is `5.0.6`.  Open source Redis stopped at `5.0.8` and as of 4/30/20 `6.0` is now GA.  We don't know AWS' intentions/timeframe to offer higher than `5.0.6` or even `6.X`  

At @spgreenberg 's  suggestion we tried to see if the AWS API would support a wildcard for the engine but it does not.  The idea behind it was we could always offer the latest `5.X` version to customers once AWS releases it.  Open source `6.0` has some breaking changes so we didn't want to have the broker always give out the latest version and give customers a mixed experience if we are not tracking AWS offerings and adjust customer exceptions in a timely fashion. 

We will need to have further technical discussions on how we want to handle this and future engine offerings from both the broker and plan offerings.  At this point we felt it was not worth holding up the beta while we sort this out and we can adjust the broker code and plans during the beta to try and resolve this and provide the ability to offer the latest versions of the offerings without impacting our customers.

**Comment by RonWilliams** [comment]
I like the names based on replica count, but the redis-single should probably be redis-dev or similar or to clearly imply it should be used for non-production workloads. 

On pricing, I'd like to move away from any $0 cost charges when a service incurs cost to the program. I'll create a separate card for determining costs. Pricing should be $0 for all tiers during the beta.

**Comment by karareinsel** [comment]
@ChrisMcGowan - @RonWilliams just shared with me that the legacy Redis and ES need to be deprecated by October 16. So that we're in compliance with our deprecation policy, we'll need need to make a deprecation announcement probably in the first couple weeks of the beta.

**Comment by karareinsel** [comment]
Announcement emailed to customers today.

**Comment by karareinsel** [comment]
@ChrisMcGowan now that the Redis beta is live, could the remaining acceptance criteria that are open be split out into new stories? It'll be easier to track and it'll better reflect all the progress that's been made. Thoughts?

**Comment by ChrisMcGowan** [comment]
@pburkholder just following up - the SCR was filed for this new version of the service and broker correct?

**Comment by ChrisMcGowan** [comment]
Opened https://github.com/cloud-gov/product/issues/1383 to track the final bits for move to prod
