### ISSUE TITLE
k8s journey: Document customer code changes to use AWS Redis

### ISSUE THREAD

**Issue by ChrisMcGowan** [cloud-gov/product#1341]
With the move to AWS hosted Redis, CG customers will need to make changes to their applications to use the AWS version of Redis.  The CG Team needs to document those changes and make them available to CG Customers when the beta of Redis goes live.

## Acceptance Criteria
- [x] Create [examples repo](https://github.com/cloud-gov/aws-redis-example)
- [x] Documentation of code changes to interface with AWS Redis is posted for CG Customers to access
- [x] Documentation of Redis feature changes using AWS Redis is posted for CG Customers to access
- [x] Documentation of a self-serviced Redis migration between the legacy Redis and new AWS Redis is posted for CG Customers to access

--- 

## Security considerations
n/a

## Implementation sketch
- [Implemenation PR](https://github.com/cloud-gov/aws-redis-example/pull/1)
- [x] Document Redis client code changes - links to AWS doc are encouraged. The CG Team does NOT need to provide examples for every known code base but at least offer the most popular choices (go, python, java, etc) 
- [x] Document Redis feature changes and depreciations based on the final AWS Redis version and the previous legacy Redis
- [x] Document a customer driver migration strategy for CG Customers to move their own data from legacy Redis to AWS Redis

**Comment by hillaryj** [comment]
Some relevant links initially from @soutenniza:

- AWS ES - https://docs.aws.amazon.com/general/latest/gr/signature-v4-examples.html
- AWS Redis - https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/in-transit-encryption.html#in-transit-encryption-see-also
- AWS says these libraries work
    - Java - https://github.com/xetorthio/jedis
    - Python - https://github.com/andymccurdy/redis-py

**Comment by apburnes** [comment]
Should we create a `cg-redis-example` repo for code snippets on connecting to the updated service?

**Comment by ChrisMcGowan** [comment]
@apburnes that's a good idea and something we can use as reference for customers.  Just call it `aws-redis-example` - drop the `cg` as that was used in our older org under 18F to make it easy to find CG repos.  Thanks !

**Comment by apburnes** [comment]
Initial examples are created and available in the github.com/cloud-gov/aws-redis-example
