### ISSUE TITLE
ES/Redis AWS Services: Scale RI for Redis - revisit 10/15

### ISSUE THREAD

**Issue by ChrisMcGowan** [cloud-gov/product#1346]
As part of this journey we now need to define some reserved instances to reduce runtime costs for Redis.

## Acceptance Criteria
- [x] Proper cache instance type is specified for standard and HA offerings
- [x] Sample projections are provided to CG Leadership to define RIs
--- 

## Security considerations
N/A

## Implementation sketch
- [x] Review existing Redis services instances to establish baseline RI figures for beta customers
- [x] Increase AWS Service quota to meet future needs
- [ ] Make RI reservations in AWS Govcloud
- [ ] Monitor Redis RI usage

**Comment by ChrisMcGowan** [comment]
Based on the last check of legacy k8s we had the following Redis numbers:
25 Single node instances
43 HA node instances

Assuming 80/20 on HA customers taking 3 node vs 5 node we would need: 25 + 102 (80%/34 - 3 node) + 45 (20%/9 -  5 node) = 172 baseline nodes + 20% growth (34) = 206 Service Limit at a min should be requested.  The current service limit on Elasticache nodes is 20.

**Comment by ChrisMcGowan** [comment]
@RonWilliams  ^^ See above

**Comment by RonWilliams** [comment]
@ChrisMcGowan I went in to request the service limit increase; however, the service limit option for our region is not available within the support ticketing system. I've opened a ticket for fixing the UI and the service limit to 250.

**Comment by ChrisMcGowan** [comment]
Thanks @RonWilliams - that UI limit was my exp as well when I went to look that morning.  Thank You

**Comment by ChrisMcGowan** [comment]
@RonWilliams - at this point do we want to start purchasing Reserved Instances for our Redis cache nodes?  The current on-demand pricing for cache.t3.micro is $0.02 per hour.  A one year no up front RI is $0.0.14 per hour - a 30% savings.

**Comment by RonWilliams** [comment]
@ChrisMcGowan - I'd like to hold off on purchasing RIs and see if an AWS Savings Plan would be possible instead. For now, let's see how much we're using and consider adding these RIs if a savings plan is not viable within ~45 days.

**Comment by ChrisMcGowan** [comment]
Decision was made to close this for now as we don't have enough usage at this point to get value from RIs
