### ISSUE TITLE
As an operator, I want to review our current ALB and ELB usage for upgrades and old instances.

### ISSUE THREAD

**Issue by spgreenberg** [cloud-gov/product#1360]
It appears we have a few "Classic" ELBs and possibly a few ELB's that are not in use. The task is to evaluate our current ALB/ELB usage and report back on a plan to upgrade Classic ELBs to ALB if possible as well as a plan to delete unused resources.

**Comment by wz-gsa** [comment]
All load balancers are ALBs now.
