### ISSUE TITLE
As a cloud.gov team member, training is required to maintain compliance stance (5/13 next training)

### ISSUE THREAD

**Issue by pburkholder** [cloud-gov/product#1362]
Hold trainings for new members and current members who are approaching their one-year deadline. Training topics include:

- [x] Contingency Plan
- [x] Incident Response
- [x] Non-public Information

**Comment by pburkholder** [comment]
Contingency plan training was held for all team members except @eddietejeda on 2020-04-29. 

IR and NPI training is scheduled for 2020-05-13

**Comment by ccostino** [comment]
Safe to close this issue now @pburkholder?
