### ISSUE TITLE
Scaling disk space

### ISSUE THREAD

**Issue by karareinsel** [cloud-gov/product#1366]
From Amir - Federalist users are bumping up disk limits and while we can ask them to try trim their site repositories here and there we're worried it's not sustainable.  How would we go about understanding what can be done for scaling disk space? 
Research-based task stemming from this Slack thread - https://gsa-tts.slack.com/archives/C09CR1Q9Z/p1588954398264200

Timebox to one hour to investigate and report back what's possible.

**Comment by apburnes** [comment]
We set the `4096 MB` app disk limit at the platform level https://github.com/cloud-gov/cg-deploy-cf/blob/master/bosh/opsfiles/api-defaults.yml#L9-L11 which is controlled by [cloud_controller_ng](https://github.com/cloudfoundry/cloud_controller_ng).  There is no documentation in cloud_controller_ng or in the [bosh job](https://bosh.io/jobs/cloud_controller_ng?source=github.com/cloudfoundry/cf-release&version=287#p%3dcc.maximum_app_disk_in_mb) defining the maximum limit on apps disk space. The default is "2048 MB" and we set it at "4096 MB".

Questions to ask:
- Can the cloud controller increase `maximum_app_disk_in_mb` just on an org level basis?
- Will increasing the `maximum_app_disk_in_mb` at the platform level contribute to higher costs per app or effect bosh deployments?

**Comment by apburnes** [comment]
The federalist team is starting to support customers with larger sites, and as those customers continue to grow, they will experience hitting these disk limits more often.  Being able to increase the app disk size from **4GB** to **8GB** for the build container would be their ideal scenario but they appreciate the limits of the platform.  In the mean time, they are working towards minimizing dependencies in the build containers to free up additional disk.  If the disk size cannot be increased, they may start looking for alternatives like running builds directly on AWS or deploying their own version of Concourse.
