### ISSUE TITLE
PLANNING/DISCUSSION - Test CF during deployment in staging and development - fail deployments when tests fail

### ISSUE THREAD

**Issue by bengerman13** [cloud-gov/product#1371]
This is an outcome from the incident: [20200407 - routers without routes](https://docs.google.com/document/d/1SPq4LRJmaOYvDRcpRPWgB5go96zUwr8rVQatYWicIeA/edit)

**Comment by pburkholder** [comment]
This is a proxy for a POA&M so we need to be sure to keep this in our queue for completion

**Comment by karareinsel** [comment]
Team will review the post-mortem doc async to determine if procedural or technical changes are required.

**Comment by karareinsel** [comment]
Team needs to meet first to discuss an approach and then further work will be identified. This card is to meet to define what should be tracked and then determine the work that needs to be done.

**Comment by ccostino** [comment]
Discussion scheduled on 9/30 at 2:30 - 3:30 PM ET.

**Comment by ccostino** [comment]
[We've captured notes here](https://docs.google.com/document/d/133soq1mGroEE_8NurdhYV8uOXpI8VEpVpU0WvrlgMxU/edit#heading=h.4ipn3mubxfu9): two new issues will come out of this, one to be prioritized soon.
