### ISSUE TITLE
Determine platform capacity to support disk space increases

### ISSUE THREAD

**Issue by karareinsel** [cloud-gov/product#1374]
This is a follow-up issue to #1366. 

It's been confirmed that disk space could be increased to 6GB. What needs to be figured out is if our current platform capacity could support the increase in disk space and if there is any other collateral impact to the platform.

Latest request from David Corwin with Federalist team.
 "I just want to surface the issue around the maximum disk space per container again. We’ve had multiple customers bump up against this recently and as we get more complex sites I imagine this will continue to be an issue. To be clear, there are multiple factors that play into this, some outside of cloud.gov control:
1. The Federalist build container docker image is 2GB, taking up half the maximum space
2. Some of our customers are including things in their repository and build that could/should be stored and referenced elsewhere
3. We promise “unlimited storage”
We have worked with some of our customers to reduce the size of their repos with some success and are actively looking into ways to reduce the size of our build container by either switching to alpine based images or using buildpacks.
We understand that the limit is platform-wide, so the decision will impact the platform as a whole, however, users only receive the maximum if the explicitly ask for it, it’s not the default.
Would it be possible to explore raising the limit 1 or 2 GB to buy some time until we can find other solutions?"

## Acceptance Criteria:

- [x] Identify config in the CF deployment ops file
  - [Increasing diego-cell disk ](https://github.com/cloud-gov/cg-deploy-cf/blob/14d03acd7bd9887632023f41e59db769475c1a6a/bosh/opsfiles/diego-cell-disk.yml)
  - [Increase max app disk](https://github.com/cloud-gov/cg-deploy-cf/blob/14d03acd7bd9887632023f41e59db769475c1a6a/bosh/opsfiles/api-defaults.yml)
- [x] [Calculate](https://docs.google.com/document/d/1CR4nnf825cxCkOCVByF0F8cGn0A-NibmisZwfKfT1Bc/edit?usp=sharing) projected additional ephemeral disk space with increase to max disk space
- [x] Communicate estimated cost increases with cloud.gov leadership

## Reference material

- Diego architecture https://docs.cloudfoundry.org/concepts/diego/diego-architecture.html
- Staging architecture https://docs.cloudfoundry.org/concepts/how-applications-are-staged.html
- Managing disk space with grootfs https://docs.cloudfoundry.org/adminguide/examining_grootfs_disk.html
- Older release notes to help look at configs https://resources.docs.pivotal.io/pdfs/pcf-docs-1.12.pdf#cell

**Comment by apburnes** [comment]
Updated Federalist on the next steps.

**Comment by apburnes** [comment]
Closing for future implementation issue https://github.com/cloud-gov/cg-deploy-cf/issues/492
