### ISSUE TITLE
add micro instances to rds broker options

### ISSUE THREAD

**Issue by bengerman13** [cloud-gov/product#1378]
add t[23].micro instances as an option to rds broker

**Comment by karareinsel** [comment]
Is adding the micro instances another step in changing the RDS instance type? Clarification will help prioritize the work. Is it enabling as another option or is there more work to this (separate work just to set up this)?

**Comment by ccostino** [comment]
I think this is a sub-task/story for https://github.com/cloud-gov/product/issues/1367; at the very least it is related work!

**Comment by ccostino** [comment]
I spoke with @RonWilliams and we're going to stick with the T3 instance options for this; T2 is previous generation and the cost difference is negligible.

**Comment by ccostino** [comment]
Slight correction!  In the GovCloud region, only Postgres has T3 enabled; MySQL and MariaDB only have T2 available, so we'll account for these.

**Comment by ccostino** [comment]
This has been completed with this PR: https://github.com/cloud-gov/aws-broker/pull/81
