### ISSUE TITLE
what's up with AWSLogsInstanceExpired

### ISSUE THREAD

**Issue by bengerman13** [cloud-gov/product#1380]
This alert fires multiple times a day. What does it mean? How can we make it fire less?

tasks:
- [ ] document what this alert is for - why should we care?
- [ ] document what to do when this alert fires
- [ ] fix whatever is causing it to fire (do we need to adjust some timing? is something actually broken somewhere?)

**Comment by onelittlebecca** [comment]
https://github.com/cloud-gov/cg-deploy-prometheus/blob/master/bosh/opsfiles/rules.yml#L61
^^^ It is in this line here. Seems to fire when EC2 isn't logging. Brand new to devops world, so not sure how to fix that.

Follow up question: is anything occurring on the frontend, like sites being down or anything when that is firing? Do we know what else occurs when it isn't able to log? I assume this would be part of the "why do we care" portion of the first point.
