### ISSUE TITLE
Make Redis Prod Ready

### ISSUE THREAD

**Issue by ChrisMcGowan** [cloud-gov/product#1383]
Now that Redis is in BETA, we need to make sure the CG team is ready to support the service once it moves into prod

## Acceptance Criteria
- [ ] Have developed support documentation on how CG members will support the broker going forward
- [ ] For paid plans set the final monthly costs
- [ ] Tie Redis instance name to CF Service instance guid (AWS does not support tags on Redis instances)

--- 

## Security considerations
- [ ] SCR is ready

## Implementation sketch
[links to background notes, sketches, and/or relevant documentation
- [ ] Documentation is located in internal docs
- [ ] Instance name work is complete
- [ ] Enable service for all CF orgs on the pipeline

**Comment by pburkholder** [comment]
Let's add to this: 

- [ ] Customers have a clear long-term patch/upgrade path

**Comment by pburkholder** [comment]
- [ ] Backup & Recovery?

**Comment by wz-gsa** [comment]
no longer relevant
