### ISSUE TITLE
Enhance documentation around user-provided service instances

### ISSUE THREAD

**Issue by mheadd** [cloud-gov/product#1384]
In order to better assess the viability of running apps on the cloud.gov platform, customers want expanded documentation on how to set up, use, and integrate user-provided service instances in their cloud.gov apps.

We often have existing or potential customers ask about backing services that are not currently a part of [our marketplace](https://cloud.gov/docs/overview/portfolio-analysis/#identify-applications-with-a-supported-technology-stack) (e.g., SQL Server, MongoDB, etc.). Our docs mention both [user-provided service instances](https://cloud.gov/docs/services/intro/#setting-up-user-provided-service-instances) and [BYO brokers](https://cloud.gov/docs/services/intro/#extending-the-marketplace), but don't provide a description of the tradeoffs between these two approaches. Also, there are few details provided on how to set up and use a user-provided service instance with a cloud.gov app.

## Acceptance Criteria
* [x] GIVEN a need to utilize a service outside the cloud.gov marketplace, a customer can easily find a detailed description of a BYO broker and clearly identify which option is more suitable for their needs.
  * See [PR](https://github.com/cloud-gov/cg-site/pull/1707)

* [x] GIVEN a need to utilize a service outside the cloud.gov marketplace, a customer can easily find a detailed description of a user-provided service instances and clearly identify which option is more suitable for their needs.
  * See [PR](https://github.com/cloud-gov/cg-site/pull/1710)
--- 

## Security considerations
None - enhanced documentation and examples of features already provided. 

## Implementation sketch
Modifications to the following cloud.gov doc pages:
* https://cloud.gov/docs/overview/portfolio-analysis/
* https://cloud.gov/docs/services/intro/

A detailed blog post and sample Github repo showing how to set up and use a real user-provided service instance.

**Comment by ccostino** [comment]
@mheadd this looks good so far!  At the moment is this still a matter of more research into each of these things to give more clarity to customers when to choose one over the other?

**Comment by mheadd** [comment]
Yup, in addition to examples, I think it would be worth listing out the tradeoffs of each approach.

**Comment by mheadd** [comment]
Some common things hear from potential customers:
* How do I connect to a SQL Server instance from a cloud.gov app?
* How do I connect to a NoSQL DB from a cloud.gov app?
* How do I send an email (or some other form of notification) to users from a cloud.gov app?

**Comment by onelittlebecca** [comment]
I would be interested in pairing on this -- I think it will help me get more familiar with the platform!

**Comment by apburnes** [comment]
@onelittlebecca let's talk about this tomorrow morning

**Comment by spgreenberg** [comment]
This might be helpful: https://github.com/cloud-gov/cf-byo-broker
