### ISSUE TITLE
Complement the CIS with an sample inheritance breakdown for a notional Moderate-impact architecture 

### ISSUE THREAD

**Issue by pburkholder** [cloud-gov/product#1393]
Our cloud.gov docs say (or said) customers can inherit 269 controls. But if you look at our CIS you only see a number in the 60s. 

![image (1)](https://user-images.githubusercontent.com/1211146/86033178-86a8c900-ba06-11ea-824a-382bf127bf6d.png)

This is confusing.

Part of this  is  the result of imprecise wording of our controls, and not reflective of their actual inheritance status. An example would be SI-8(2), Spam Protection, which is likely N/A for most customers, but shows up as not-inheritable. See also this [thread in Slack w/ @lauraggit](https://gsa-tts.slack.com/archives/C09CR1Q9Z/p1592257228427500) for context. 

## Security considerations

Clarification of public documentation only, no security implications

Possible implementation:
- [x] Create an example using typical web app running on cloud.gov & list relevant controls given this architecture. 
- [x] Generate some examples of control families that apply based on certain features of web apps (auth, data persistence, etc.)

**Comment by pburkholder** [comment]
@mheadd Here's an existing issue for this work. I'm putting into triage for next week.

**Comment by mheadd** [comment]
@pburkholder Can we identify a set of values for the `Best case inheritability` columns? Not sure what corporate and procedural refer to. I don't want to mislabel something going through this list.

**Comment by karareinsel** [comment]
Making steady progress on reviewing each of the controls.

**Comment by mheadd** [comment]
To the point of this work, do we need to specify the specific controls that apply to agency ATO's that are undergoing a FISMA assessment (vs. a FedRAMP assessment)? Doesn't a FedRAMP assessment involve more controls than a FISMA assessment? Would all of the 325 controls listed for our FedRAMP assessment even apply to an agency getting an ATO that is based on a FISMA assessment? 

(It's possible that my understanding of FedRAMP vs FISMA, which applies to ATO's and the number of relevant controls involved is flawed is incomplete or inaccurate.)

**Comment by karareinsel** [comment]
Those are good questions. Are you thinking that by indicating which controls are undergoing a FISMA assessment vs. FedRAMP assessment, we could provide information that more accurately reflects the number of controls a customer could inherit?

**Comment by its-a-lisa-at-work** [comment]
I've found this [guide](https://www.gsa.gov/cdnstatic/FedRAMP_Control_Quick_Guide_V12_%281%29.pdf) as a handy reference that might help answer some questions at a quick glance

**Comment by mheadd** [comment]
This is a breakdown I was able to find that is [published by Coalfire](https://www.coalfire.com/documents/whitepapers/fisma-vs-fedramp_controls-authorizations), one of the 3POs:

<img width="658" alt="Screen Shot 2020-08-05 at 1 32 35 PM" src="https://user-images.githubusercontent.com/58419/89444726-27825680-d720-11ea-9b1d-84f09b40a62d.png">

**Comment by mheadd** [comment]
Next steps:
- [x] Remove outdated content on # of controls from website
- [ ] xxx
- [ ] xxx 
- [ ] Revise website with update information on controls

**Comment by lauraGgit** [comment]
@mheadd @pburkholder any update on how this is progressing?

**Comment by pburkholder** [comment]
@karareinsel Can you comment since @mheadd is out the rest of the week?

**Comment by karareinsel** [comment]
@mheadd and I met with @lauraGgit and Ryan Ahearn yesterday (9/26) and shared with them the audit results. They saved a version of the audit and are using it to inform their work with TANF and ACF.

**Comment by mheadd** [comment]
Preliminary meeting with 18F Design resource last week to go over what is needed, review existing information, and answer questions. Need to schedule follow up.

**Comment by mheadd** [comment]
Part of this work has been broken off into: https://github.com/cloud-gov/product/issues/1443

**Comment by mheadd** [comment]
Current thinking on notional apps is as follows:

| Description  | Impact level  |  
|---|---|
| Static website fronted by nginx where all the agency users use our integrated SSO.  | Low  | 
| Database backed app with no user logins (e.g college scorecard) and where all the agency users use our integrated SSO.  | Low  | 
| Agency users would re-use the cloud.gov UAA identity provider for agency authentication (e.g. like Tock) but the information managed would be moderate impact  | Moderate  |

**Comment by mheadd** [comment]
GSA IT may already have a relevant breakdown of controls for Low and Moderate apps as part of the [Lightweight Security Authorization Process](https://insite.gsa.gov/cdnstatic/insite/Lightweight_Security_Authorization_Process_%5BCIO_IT_Security_14-68_Rev_6%5D_04-25-2018.pdf) (:lock:) - see Appendix B. Going to chat with someone there this week and see if they have something that can be used as the basis for this comparison.

**Comment by mheadd** [comment]
I've developed an initial draft of this using the list of controls from the SSP for [Tock](https://github.com/18F/tock). Instead of using a notional app, we can use the list of controls for an actual application running on cloud.gov to show what the control profile looks like. We can then identify controls that likely will not apply to a few other examples of apps that _could_ run on cloud.gov. Initial draft is open for review and comment here: https://docs.google.com/spreadsheets/d/10UMdR-FSRiBB6MOtgekWz-kDHqoJd4kw3iZbX-FLsjg/edit#gid=0

**Comment by mheadd** [comment]
This material could be used to form the basis of a blog post (or posts) or future tech talk, but we shouldn't add more compliance-related content to the cloud.gov website before doing an audit of that material and making sure it is updated and consistent.
