### ISSUE TITLE
Implement App Auto-Scaler

### ISSUE THREAD

**Issue by mheadd** [cloud-gov/product#1394]
# What we're after

A way to enable customers to auto-scale their apps (horizontally) within allocated memory thresholds.

## Hypothesized benefit(s)/why:
* Would allow some of our larger customers (FDIC, FEC) to auto scale their apps during times of heavy use. Both may experience spikes in traffic at certain times because of the nature of their work.
* FDIC, EPA (and possibly other customers) have asked for this feature in the past.
* (non-benefit) This won't affect customer bills under our current billing model

## Potential metrics
* Number of customers utilizing the new service
* Increase in BD opportunities where this feature becomes a differentiator.

### Security considerations

* TBD

### Notes for implementers

- There is an [existing component for this already available and supported](https://www.cloudfoundry.org/blog/cloud-foundry-app-autoscaler-project-has-graduated/) in the Cloud Foundry community.
- https://github.com/cloudfoundry/app-autoscaler-release
- https://github.com/cloudfoundry/app-autoscaler-release/blob/main/docs/Readme.md

**Comment by wz-gsa** [comment]
@cweibel implemented this
