### ISSUE TITLE
rename default branch to `main` in all repositories

### ISSUE THREAD

**Issue by spgreenberg** [cloud-gov/product#1395]
We should rename all of our default branches to main.

Utility here: https://github.com/resilientscale/utilities#replace-master-with-main-in-github

## Security considerations

none

## Implementation sketch

- [x] Check w/ federalist to ensure this won't break things for them
- [ ] Search docs for links that could break.

- [ ] Update git and github (steve has a script)
- [ ] Update pipelines

**Comment by spgreenberg** [comment]
We should remove the branch specification from all git resources unless it is explicitly needed. Concourse will clone the default repo branch if not specified.

**Comment by karareinsel** [comment]
We will address the renaming when we do the SonarQube work which must be done by November 1, 2020.

**Comment by karareinsel** [comment]
GitHub is going to be rolling out new functionality that will make renaming an easier process (anticipated date is this fall). We recommend waiting until Github pushes the new functionality into production and then make the naming change.

See more - https://github.com/github/renaming

**Comment by markdboyd** [comment]
This was completed for all active repos in the cloud-gov org. See https://github.com/pulls?q=is%3Apr+author%3Amarkdboyd+archived%3Afalse+is%3Aclosed+branch+main+user%3Acloud-gov for a list of some of the PRs related to this work
