### ISSUE TITLE
Create guidance for using tags on all support requests in Zendesk

### ISSUE THREAD

**Issue by mheadd** [cloud-gov/product#1397]
Zendesk supports the use of tags for customer support requests, which would allow us to see trends in requests and to help identify where staff time is being used to help our customers. 

<img width="301" alt="Screen Shot 2020-07-02 at 9 15 32 AM" src="https://user-images.githubusercontent.com/58419/86363877-75013480-bc45-11ea-94e7-829c240f5e15.png">

We should update [our current support documentation](https://cloud.gov/docs/ops/customer-support/) to provide guidance on adding meaningful tags to all new support requests so that we can analyze trends, and better focus our support resources and improve our documentation.

**Comment by karareinsel** [comment]
@mheadd should there be a meeting first to discuss?

**Comment by mheadd** [comment]
Yup, that would probably help us determine both the criticality and LOE required for this.

**Comment by karareinsel** [comment]
I'm going to remove this from triage for now. Once the meeting has occurred and next steps are clear, prioritization can be re-visited.
