### ISSUE TITLE
Update control plane RDS instances to Postgres 12.x

### ISSUE THREAD

**Issue by pburkholder** [cloud-gov/product#1398]
This work will address findings around SSL/TLS on RDS instances

See POA&Ms CG200-SC-13 and CG99 and CG90

In order to close ensure security, compliance and a clean FedRAMP bill of health, we want to address POA&Ms related to Nessus findings regarding TLS/SSL on RDS. See [the Queries tab of our POAM Dashboard](https://docs.google.com/spreadsheets/d/1Of4psOutBmZHVekV-_n_CuG8lOqbdpmrSQQJeSwobm0/edit#gid=2006937259).

These are all likely ORs (operational requirements)

## Acceptance Criteria

- [ ] POA&Ms are closed or have DR/Operational Requirement evidence submitted.

--- 

## Security considerations

Improves security and compliance to understand and document these findings. 

## Implementation sketch

Databases to update:
- [x] bosh/production
- [x] credhub/production
- [x] ccdb/production
- [x] bosh/tooling
- [x] atc/tooling
- [x] credhub/tooling
- [x] opsuaa/tooling

**Comment by pburkholder** [comment]
AWS response. Not helpful but my question wasn't well-framed.

> I reviewed the findings mentioned in the case correspondence, and can notice that they are related to security with the use of TLS and Self-Signed Certificate. I did some research internally, and found that the findings in your Nessus compliance scans are something which are not configurable for RDS instances. 
> I was able to find out that both disabling TLS and Using Custom public and private SSL certificate on RDS instance are not yet supported. This is because AWS RDS is a managed service, unfortunately this is a limitation that settings related to these findings cannot be configured.  
> The above limitation is applicable to RDS Instances in general, hence, even after replacing / upgrading to a different instance class, there would not be an option to configure settings related to the mentioned findings.

**Comment by pburkholder** [comment]
Updating this to reflect that AWS postgres 12 now has proper TLS and cipher suites, so we can adopt it and no longer carry a POA&M with a vendor dependency.

**Comment by karareinsel** [comment]
March 10 is the deadline.

**Comment by ccostino** [comment]
This work is also related to a cost reduction that we embarked on a few months ago, captured here: https://github.com/cloud-gov/private/issues/241

There are PRs already open in [`cg-provision`](https://github.com/cloud-gov/cg-provision/) that we could leverage for this work, specifically [mentioned here](https://github.com/cloud-gov/private/issues/241#issuecomment-683115346).

@ChrisMcGowan mentioned that for BOSH, we'll want to shut off `resurrection` before that goes to keep BOSH from trying to rebuild everything while its DB is down.

For the upgrades, we will need to do these in phases in terms of components and versions:

- We can't update everything at once, that'll bring the system down
- We can't update directly to the latest version for PostgreSQL - we need to update in steps

The PRs that are already open should account for this with their documentation and the version specified in their changes to get to the first step (a version `11` release) that will get us to `12`.  We also want to be mindful of letting AWS handling auto-updates, so not specifying minor/patch versions.

**Comment by jfredrickson5** [comment]
@pburkholder All the databases have now been upgraded!
