### ISSUE TITLE
Draft cloud.gov shared database deprecation and new RDS scaling feature notice

### ISSUE THREAD

**Issue by RonWilliams** [cloud-gov/product#1399]
Allow teams that currently use the shared database instance to migrate to a new instance type. Also, notify all database users of new resizing features now available. 

[Google Doc for Draft](https://docs.google.com/document/d/1hZWpMTgndf_THG2GYcS_NV7t6Weren4f7eUmpJZmZaU/edit)

**Comment by ccostino** [comment]
When saying resizing, we'll want to be sure that this is in relation to instance classes and therefore the CPU and RAM for the instance, not the storage size.

I did create an issue for [updating the storage size](https://github.com/cloud-gov/product/issues/1407), so whenever that is prioritized that'll be a nice update to have!

**Comment by ccostino** [comment]
@RonWilliams and @karareinsel, I've taken a crack at a first draft of this to help move it along!  Please take a look and let me know if I can help anymore with this or if you'd like me to continue working on the draft directly.

If anything, there might be too much to cover in one notice so I understand if you want to split it apart.  I wanted to make sure everything was at least captured so there was something to start with. :-)

**Comment by RonWilliams** [comment]
Update notification has been sent to customers via StatusPage. 

[Important updates and enhancements to cloud.gov’s relational database service
](https://cloudgov.statuspage.io/incidents/0v1nwyybb0fs)
