### ISSUE TITLE
Fix the permissions issue with removing custom RDS parameter groups

### ISSUE THREAD

**Issue by ccostino** [cloud-gov/product#1405]
In order to make sure custom RDS parameter groups are cleaned up properly, we need to fix an apparent permission issue with our broker AWS API call that attempts to retrieve the existing custom parameter groups so that they can be properly deleted when an RDS service instance is deleted.

## Acceptance Criteria
* [ ] GIVEN an existing RDS service instance with a custom parameter group associated with it
  WHEN the service instance is deleted
  THEN the associated custom parameter group is removed as well

--- 

## Security considerations
* [ ] Double check that the IAM configuration for the user(s) related to this activity is configured properly (this may involve Terraform updates in [`cg-provision`](https://github.com/cloud-gov/cg-provision))

## Implementation sketch
The error in the logs from the broker is the following:

```
Could not retrieve list of parameter groups while cleaning up: AccessDenied: User: [redacted] is not authorized to perform: rds:DescribeDBParameterGroups
```

And yet, in `cg-provision`, [it looks like that's clearly defined](https://github.com/cloud-gov/cg-provision/blob/master/terraform/modules/iam_role_policy/aws_broker/policy.json#L17) and set to Allow. Given this, I am not quite sure where the breakdown is happening, but there is definitely a permissions issue regardless.

* [ ] Investigate the permissions for the IAM user(s) related to the broker
* [ ] Adjust the permissions as necessary (may be manual, may be through our Terraform setup)
* [ ] Test the removal of an instance with a custom parameter group (check our [smoke test](https://github.com/cloud-gov/aws-broker/blob/master/ci/run-smoke-tests-db-updates.sh) for an example of how to do this)
* [ ] Make a note if there's any other issue(s) once the permissions issue is fixed

**Comment by bengerman13** [comment]
I found the event for one of these in CloudTrail. According to CloudTrail, the RequestParameters were `null`, so we might not be passing the name filter correctly

**Comment by ccostino** [comment]
Oh, awesome find, thanks @bengerman13!
