### ISSUE TITLE
Add support to increase RDS instance storage size

### ISSUE THREAD

**Issue by ccostino** [cloud-gov/product#1407]
In order to enable customers to increase their RDS storage size, we want to expose the ability to pass in the `-c '{"storage": $SIZE_IN_GB}'` argument with the `cf update-service` command.

## Acceptance Criteria
* [x] GIVEN an existing RDS service instance
  WHEN a customer updates their service instance
  AND provides the `-c` flag with a storage increase request (e.g., `-c '{"storage": $SIZE_IN_GB}'`)
  THEN their database instance storage capacity is updated

## Additional resources/reference

* [AWS Go SDK documentation for ModifyDBInstance](https://docs.aws.amazon.com/sdk-for-go/api/service/rds/#RDS.ModifyDBInstance)
* [AWS API User Guide documentation for ModifyDBInstance parameters](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_ModifyDBInstance.html)

--- 

## Security considerations
None - this would be exposing already existing Cloud Foundry and AWS API functionality.  Furthermore, AWS [does not allow you to decrease storage size](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_PIOPS.StorageTypes.html), which could lead to data loss.

## Implementation sketch
With the newly implemented [`modifyDB`](https://github.com/cloud-gov/aws-broker/blob/master/services/rds/rds.go#L278) command under the hood in the [aws-broker](https://github.com/cloud-gov/aws-broker), add support to accept JSON parameters via the `-c` flag and process them just like the [`createDB`](https://github.com/cloud-gov/aws-broker/blob/master/services/rds/rds.go#L198) method does:

* [x] Add support for accepting the database size as a custom parameter; [this is already done in the `ModifyInstance` method in broker.go](https://github.com/cloud-gov/aws-broker/blob/master/services/rds/broker.go#L149-L159)
* [x] Add the database storage size to the [modify input](https://github.com/cloud-gov/aws-broker/blob/master/services/rds/rds.go#L284) (or figure out the right place to do this)
* [x] Figure out where to add additional error handling for checking that the storage input is correct (either in the [`Validate` method](https://github.com/cloud-gov/aws-broker/blob/master/services/rds/broker.go#L23-L28) for the `RDSOptions` struct or in the [`ModifyInstance` method](https://github.com/cloud-gov/aws-broker/blob/master/services/rds/broker.go#L146-L238) itself; this will help to make sure that this is an appropriate size increase
* [x] Add error handling for the AWS API call in the [`modifyDB` method in rds.go](https://github.com/cloud-gov/aws-broker/blob/master/services/rds/rds.go#L276-L301) in the case of API errors related to storage size changes
* [x] Add unit tests for adjusting storage size
* [x] Add smoke tests adjusting storage size

**Comment by ccostino** [comment]
@onelittlebecca and I paired a bit on this feature this afternoon to walk through where this change will take place and what it might look like.  Based on our initial walkthrough and discussion, I've updated the information in the issue description with additional reference links and more details regarding the implementation sketch.

We'll schedule more time starting at the beginning of next week to begin tackling the implementation itself!

**Comment by ccostino** [comment]
@onelittlebecca and I are continuing to make progress on this and we feel we have the implementation in place for this support now.  Next up is to get some unit tests in place and then try it out in the `dev` environment.  Once that's getting closer to done, we'll wrap up with a couple of additional smoke tests for MySQL and PostgreSQL instances.

**Comment by onelittlebecca** [comment]
Pushed to prod this morning!
