### ISSUE TITLE
ES/Redis AWS Services - Smoke Tests

### ISSUE THREAD

**Issue by ChrisMcGowan** [cloud-gov/product#1408]
As part of moving forward with AWS deployed ES and Redis services, the aws-broker pipeline needs to have smoke tests defined and added to the pipeline.  These tests are for future aws-broker code changes so that those changes don't effect the excepted outcomes of the ES and Redis services.

## Acceptance Criteria
- [ ] Smoke tests create and validate the creation of at least one plan from Redis
- [ ] Smoke tests create and validate the creation of at least one plan from ES

## Security considerations
n/a

## Implementation sketch
* [ ] Concourse acceptance test runs and uses outcome of Redis smoke tests
* [ ] Concourse acceptance test runs and uses outcome of ES smoke tests

**Comment by apburnes** [comment]
We've put up a [draft PR](https://github.com/cloud-gov/aws-broker/pull/108) with Redis tests and working Elasticsearch today.  Will follow up with thoughts on the approach.
