### ISSUE TITLE
ES/Redis AWS Services: Solve AWS ES Manual Snapshot problem

### ISSUE THREAD

**Issue by ChrisMcGowan** [cloud-gov/product#1411]
In order to support manual snapshots in AWS ES, new policies need to be assigned for ES to assume a role to access S3 to import and export manual snapshots.  See: https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-managedomains-snapshots.html#es-managedomains-snapshot-prerequisites

The automated snapshots that take place behind the scenes in all our ES plans can not be exported to be used as a data backup.  These snapshots are self contained and can only be used to restore to their specific index.

CG customers will need the ability to be able to import and export data from their ES instances as they needed and without manual CG support.

## Acceptance Criteria
* [x] CG Customers can provide S3 and ES connection information so that an automated process in a broker can create and assigned the needed progress to allow the customer ES instance to connect to a S3 backup for manual snapshot import and export
* [x] This process has to be automated and in control of the CG customer and not require manual intervention by CG support staff.

--- 

## Security considerations
* [x] Depending on which broker/process that performs this work, that brokers IAM user might need expanded rights to create the role and associated policies between ES and S3 

## Implementation sketch
* [x] Decide which broker (ES or S3) is the best place to commit this work
* [x] Implement the needed code changes to the respected broker to implement the required functionality

**Comment by ChrisMcGowan** [comment]
After a few design meetings, @soutenniza and myself have come up with the following go forward plan for addressing this issue: 

- The existing aws-broker will be used to make the new IAM role and ES and S3 policies to allow ES to access a S3 bucket for snapshots
- We will utilize the `create service key` along with the `-c` or `config` option function of the broker to allow CG customers to specify the name of an existing CG provisioned S3 bucket (via the CG S3 broker) to the aws-broker to create the IAM polices and role needed
- The aws-broker via `create service key` will return the ARN of the assume role policy to be used for manual snapshot operations
- CG customers can then use that role for their manual snapshot operations

**Comment by ChrisMcGowan** [comment]
Today @soutenniza and myself meet with @pburkholder to discuss this approach and it's impact on compliance and our SCR filing for this service.  Peter reviewed our approach and did not find any items of concern in regards to compliance. A small update will be needed to the SCR to explain at a high level that these IAM operations are a requirement from AWS on using manual snapshots within AWS ES.

**Comment by ChrisMcGowan** [comment]
@RonWilliams @karareinsel @eddietejeda 

This is a new issue that came up with implementing customer service data migration to this new AWS ES service from our legacy k8s offering.  After technical and compliance review, a plan is in place to move forward to resolve this issue for our customers while keeping all the operations inside a broker and under the control of CG customers with no manual invention by CG support staff.  This work can take place while the beta for AWS ES is still on-going.

**Comment by soutenniza** [comment]
PR: https://github.com/cloud-gov/aws-broker/pull/95 
Will roll out to Dev/Staging today and Prod tomorrow
