### ISSUE TITLE
Determine other RDS plan offerings to enable

### ISSUE THREAD

**Issue by ccostino** [cloud-gov/product#1412]
As a follow up to https://github.com/cloud-gov/product/issues/1367, we ought to consider what other RDS plan offerings we could enable for customers.  This includes the following:

- New engine types to choose from (e.g., MariaDB, SQL Server)
- New instance class configurations (with an eye toward balancing the latest generations vs. costs to operate)
- Any version bumps needed; alternatively, just switching to offering the latest available in the case of MySQL

As noted in the instance class bullet, we'll want to balance the choices with the operational costs these would entail to make sure that we're provided cost-effective solutions to customers.

**Comment by ccostino** [comment]
@RonWilliams and @karareinsel, I'm not flagging this for triage just yet unless you feel it should be bumped in priority.  I noticed we hadn't created the issue though, and we do eventually want to tackle this. :-)

**Comment by ccostino** [comment]
A related question to this:  would AWS Aurora fall under this, or is it concerned a separate service?  And, is this something else we ought to consider offering?

Flagging @pburkholder if there's any compliance considerations to be had on this front or if it's a non-start all together.

**Comment by karareinsel** [comment]
@ccostino thank you for creating the issue. How does this compare to #1407 that's currently in triage?

**Comment by ccostino** [comment]
That one would be a nice follow up to the work that was just recently completed as it would enable more self-service for customers. :-)

This issue is definitely lower priority in comparison (and mostly involves research), and it's okay if https://github.com/cloud-gov/product/issues/1407 ultimately gets de-prioritized as well.

**Comment by markdboyd** [comment]
This is stale. Closing as we also refine our process for keeping our brokers up to date
