### ISSUE TITLE
PLANNING - Disentangle AWS Account (11/6)

### ISSUE THREAD

**Issue by karareinsel** [cloud-gov/product#1413]
Production, staging, and development instances of cloud.gov run in the same AWS account representing significant risk. Operations intended for development or staging environment could have unintended consequences on production.

Recommend starting with a research-based task to figure out approach.

Acceptance Criteria:
- [ ] Review and document existing AWS account structure and rationale / history.
- [ ] Identify challenges / opportunities of account consolidation, particularly things that could cause issues.
- [ ] Estimate level of effort required to make changes.
- [ ] Share with the team (either through documentation or a briefing) a recommended path forward.

**Comment by karareinsel** [comment]
This story is not to do the actual disentanglement but instead to come up with a plan for how to do the work. An outcome might be creating stories and/or an epic.

**Comment by pburkholder** [comment]
I started with Aidan and infrastructure the process for getting the additional AWS accounts we need for this, and a good thing as it's taking 6+ weeks to sort our.  In the end we'll have in each of AWSe/w and AWSGovCloud the following accounts:

- jump
- prod
- stage
- dev
- sandbox

**Comment by karareinsel** [comment]
Schedule the planning meeting for **after** 11/3.

**Comment by karareinsel** [comment]
Had a meeting today. @bengerman13 wrote up the [two possible approaches](https://github.com/cloud-gov/internal-docs/blob/master/design-decisions/aws-disentangle.md) which will be discussed in the engineering huddle. Will assess if the team has capacity to start work on 11/30.
