### ISSUE TITLE
generate-POAM-inventory script should emit unique identifiers needed for August ConMon (small task)

### ISSUE THREAD

**Issue by pburkholder** [cloud-gov/product#1415]
In order to meet FedRAMP requirements, the [monthly inventory first column](https://docs.google.com/spreadsheets/d/1_9Neq8fGO4NdQhsqLXDn445g3GUa1k_FZUrUXc7hulY/edit#gid=1371600163) needs to have an identifier unique within the document.  Here's how they look now:

![image](https://user-images.githubusercontent.com/1211146/89083298-99445400-d35e-11ea-87c1-61f013bd5b32.png)

A TR emailed us to note:

> Inventory - Unique Asset Identifier column does not contain UNIQUE identifiers

So the script generate-POAM-inventory.py should do that. Ideally it would match the names in the Nessus report, but if that's not possible, a name+IPaddr would suffice.

Example Nessus report host naming:

![image](https://user-images.githubusercontent.com/1211146/89083232-5f734d80-d35e-11ea-8fb1-3c0a30f39970.png)

## Acceptance Criteria
* [x] first column of generate report has unique ids

--- 

## Security considerations

Compliance requirement.

**Comment by ChrisMcGowan** [comment]
Changes made in a branch - PR: https://github.com/cloud-gov/cg-scripts/pull/136

**Comment by pburkholder** [comment]
Thanks for taking care of this @ChrisMcGowan
