### ISSUE TITLE
ES/Redis: Conduct SCR 3PAO assessment (9/4)

### ISSUE THREAD

**Issue by pburkholder** [cloud-gov/product#1417]
In order to offer new services, we need to complete the SCR assessment with our 3PAO

Note: move this ticket to `private` if we get into contracting details

--- 

## Security considerations

* be careful about any platform permissions we grant, and to revoke them afterward. 
* ensure testing doesn't impact current customers

## Implementation sketch

* [x] Revoke all cloud.gov users added to orgs
* [x] Decommission instances, apps, space and orgs created for testing in cloud-gov-compliance and cloud-gov-compliance-2.

**Comment by pburkholder** [comment]
For the record: @ccostino created the org `cloud-gov-compliance` based on the updated spreadsheet at https://docs.google.com/spreadsheets/d/1Bdzl9n2E1MXWV4elXvZ-nYuZmmEj4PEU-u5aZlNGZF4/edit#gid=131031416 and the 🆗 from @RonWilliams in Slack thread: https://gsa-tts.slack.com/archives/C0A1Z7L2U/p1597170635270600?thread_ts=1597166445.262500&cid=C0A1Z7L2U

**Comment by pburkholder** [comment]
- [ ] Obtain AWS contract that specifies what services we do or don't have access to and share that with CoalFire.

**Comment by pburkholder** [comment]
- [ ] Update CP to note what we do and don't do for AWS Redis and AWS Elasticsearch.

**Comment by pburkholder** [comment]
For AU-6(3):
- [ ] Update maintenance checklist and related filter script to pull out ES and Redis events.

**Comment by pburkholder** [comment]
For PL-2:
- [ ] Capture change process for updating diagrams for SSP (and update diagrams for SSP)

**Comment by pburkholder** [comment]
Update:
- The pentester now has two orgs to work in, and we'll need to make sure to clean them up from both `cloud-gov-compliance*` orgs
- The RET is now [on Google Drive](https://docs.google.com/spreadsheets/d/1PUQlkplTcQ71QlIO6w9rYPHkz9ToDxNi/edit?usp=drive_web&ouid=103473930635985642120&dls=true) and we need to respond by Friday 8/29
- Anna asked if the JAB has approved our SCR, and I think they've only approved in draft form, and I need to check if there's add'l work there to be done with the JAB now to keep us on track.

**Comment by pburkholder** [comment]
Update/recap on some tasks that need to be done here:

- [ ] Reply to RET by Friday 8/28 with docs/pushback 
- [ ] Per SCR language and direction from JAB, add SSP Section: SSP and public documentation

> As service brokering is a fundamental concept for cloud.gov users and for ensuring brokered services are configured to a particular standard, we will update SSP with a section on brokering, and have 3PAO review for clarity and accuracy, and include the same documentation on our public website

- [ ] PL-2 - update diagrams
- [ ] Share customer docs how to restore and show screenshots thereof

**Comment by karareinsel** [comment]
WAiting for Coalfire to deliver pen-test results and for us to complete the contingency exercise.

**Comment by pburkholder** [comment]
Closing this. Work to continue in 

https://github.com/cloud-gov/product/issues/1417
https://github.com/cloud-gov/product/issues/1437

**Comment by pburkholder** [comment]
I went through and deleted the user and spaces. We also deleted the org `cloud-gov-compliance-1` as it should no longer be necessary.
