### ISSUE TITLE
ES/Redis AWS Services: Scope and implement legacy to aws-elasticsearch data migration

### ISSUE THREAD

**Issue by ChrisMcGowan** [cloud-gov/product#1418]
With the move from our legacy k8s ES offering to aws-elasticsearch, cloud.gov needs to establish a customer data migration policy, document the process, and provide as much resources through the aws-broker to allow the customers to perform this migration on their own

## Acceptance Criteria
* [x] Provide CG customers a documented process on how to migrate from legacy ES 5.6 to aws-es 7.X

--- 

## Security considerations
N/A

## Implementation sketch
* [x] Sketch out data/process flow
* [x] Create transitional ES 6.X offering in catalog to facilitate migration
* [ ] Review AWS-ES API to see if the broker can perform a aws-ES 6.X to aws-ES 7.X upgrade at customer request
* [x] Code the above point if possible otherwise document the process flow between CG customer and operators

**Comment by ChrisMcGowan** [comment]
@cloud-gov/platform-ops - looking for some input on the following implementation sketch:

- In the catalog offer a ES 6.8 version of the medium and medium-ha plans
- That 6.8 version is not open to all users - it would be added on demand to customer orgs that request it
- The aws broker would be configured to accept input on the `cf update-service -c` command to trigger a 6.8 to 7.X based on when the customer is ready to perform the upgrade

The documented flow the customer would follow would be:

1. Request via a support ticket access to the migration service plan (6.8)
2. CG support enables service access to the plan to the customer org
3. The customer can create a new 6.8 service instance for migration
4. The customer uses existing manual snapshot functionality to assign a S3 bucket to their new 6.8 instance
5. The customer does a snapshot of their legacy 5.X data into that S3 bucket.
6. The customer then performs the snapshot restore into their new 6.8 instance
7. After the restore and and customer validation, the customer then requests an upgrade via update-service to the 7.X version - this takes place at the time the update-command is issued - not schedulable
8. Using existing CF service instance monitoring, the customer tracks the upgrade via `cf service`
9. Once the upgrade is complete, the customer validates connectivity and data 

Once we announce the removal of the legacy k8s services, we can remove the 6.8 plan offering. We can then review the `cf upgrade-service` portion of the broker for future customer driven instance upgrades.

**Comment by ChrisMcGowan** [comment]
Leaving ticket as is as it's scoped well for the span of work.  It just lingered due to other priorities when it should have been moved to blocked for a period of time

**Comment by soutenniza** [comment]
https://github.com/cloud-gov/cg-site/pull/1802
