### ISSUE TITLE
SCR Redis/ES: Conduct contingency plan exercise 

### ISSUE THREAD

**Issue by pburkholder** [cloud-gov/product#1423]
In order to assure continued operations, and to attain our Redis/ES SCR, we want to run a contingency plan exercise demonstrating recovery of the service.

The 3PAO recommendations were:

> It is recommended that Cloud.gov  test the information system's Contingency Plan and  recovery with the new components being added so that a proper review of the test can be completed to ensure the system can recover to a known state.

> It is recommended that Cloud.gov test the information system's Contingency Plan with the new components being added.

> It is recommended that Cloud.gov  test the information system's Contingency Plan with the new components being added so that a proper review of the test can be completed.

> It is recommended that Cloud.gov test the information system's Contingency Plan with the new components being added so that proper corrective actions can be taken where necessary.

--- 

## Security considerations

This will result in updates to our CP documentation and SSP controls. The exercise itself will likely be done in fr-staging to limit any impact to production

## Implementation sketch

* [x] Draft a CP exercise
* [x] Update the official CP (and add a date) if feasible
* [x] Run the exercise and keep documents
* [x] Review and report on the exercise

**Comment by pburkholder** [comment]
I have a draft exercise underway in a [Google Doc](https://docs.google.com/document/d/1FDvnZgHrTbtsfgh05Ji7E53XvCwPMmfItVbROjJhZAc/edit#heading=h.ictqn4cilc2e)

For folks following along at home it currently reads:

---
``` 
Redis and ES Contingency Plan exercise

Prior to exercise, update the published CP to provide guidance on contingency planning in the event brokered customer services are rendered unavailable. This can be high-level that points to more detailed information in our scripts or internal documentation. 

For the exercise, we’ll assume that operator error, or a massive AWS failure, has deleted two instances of cloud.gov customer Redis and two instances of cloud.gov customer Elasticsearch. To complete the exersice we’ll need to demonstrate that those instances are fully restored

PRIOR TO EXERCISE

Write contingency response documentation
Stage two multi-node instances of ES
Stage two multi-node instances or Redis
Insert dummy data
Set up applications that are using backend data
Determine how we validate data (as if we were customers)
Determine how we validate applications are working
Ensure backups are occurring

EXERCISE

Delete instances
Go through CP exercise, including mocking notifications and status updates
Restore instances
Validate data
Validate application functionality
Complete CP exercise

REFLECT

QUESTIONS:

Can the process for restoring two instances scale to replace all instances? How long would that take?
```

**Comment by soutenniza** [comment]
Elasticsearch and Redis example applications have been updated so the plan can be done much easier 
* https://github.com/cloud-gov/aws-elasticsearch-example/pull/2 
* https://github.com/cloud-gov/aws-redis-example/pull/9

Elasticsearch restore is very quick depending on how much data was there.
Redis Restore is longer due to AWS creates a new redis cluster with the Redis backups

**Comment by ChrisMcGowan** [comment]
Van's branches for example changes are merged, the CG test was conducted successfully on 11/12/20, and the runbook on restores has been created at: https://github.com/cloud-gov/internal-docs/blob/master/runbooks/ec-es%20restore.md

@pburkholder you should be good to close out the POAM.
