### ISSUE TITLE
Investigate Tock login-generated account creation

### ISSUE THREAD

**Issue by mheadd** [cloud-gov/product#1432]
We have observed several instances where [new cloud.gov sandbox accounts are created when users log in to Tock to record their hours](https://gsa-tts.slack.com/archives/C047SQF9C/p1597418808003800). Tock users are often not aware that a cloud.gov account is created, and It is not fully understood why this login process creates a new cloud.gov account.

Tasks:

- [x] Raise issue with Tock dev team to try and understand why this is occurring.
- [x] Work with Tock dev team to fix this issue so that occasional logins to Tock do not create new sandbox accounts.
- [x] Review existing sandbox accounts in `sandgox-gsa` org to see if it makes sense to purge inadvertently created accounts.

**Comment by mheadd** [comment]
Example of this happening is here:

<img width="685" alt="Screen Shot 2020-09-11 at 11 34 20 AM" src="https://user-images.githubusercontent.com/58419/92945247-026dbb80-f423-11ea-834e-aefb7e2c580d.png">

**Comment by apburnes** [comment]
Talked with Joe Krzystan and he's will to help us out.  We will try to recreate the sandbox creation and troubleshoot from there.

**Comment by apburnes** [comment]
Started a trouble shooting doc to follow the trail https://docs.google.com/document/d/1H-Qrcvv8iP3myzpPt0QdM2-jZOC6_qqmLH1WZZiBX2k/edit

**Comment by apburnes** [comment]
Added GSA Sandbox inventory https://docs.google.com/document/d/1GnHJZ445Ugd89SIhnMXfl3TJhOEGsLv5LB85GuADWp8/edit?usp=sharing

Closing this issue to create a new one around a deeper dive into UAA #1444 and another around purging sandboxes of former GSA employees and unintentionally created ones #1445
