### ISSUE TITLE
ES/Redis AWS Services - Service version in binding

### ISSUE THREAD

**Issue by ChrisMcGowan** [cloud-gov/product#1441]
Modify the binding credentials provided by customers so that it reflects the last know version of the service at the time of binding.  Since the service/plans no longer contain the version, this is the most direct way for a customer to know what version their service instance is on.

## Acceptance Criteria
* [x] Making sure that service instance engine versions are included in binding credentials so customers can easily find what version of the service they are running for Redis

--- 

## Security considerations
n/a

## Implementation sketch
* [x] Make changes to the broker to include the version of the service in the binding credentials.

**Comment by soutenniza** [comment]
https://github.com/cloud-gov/aws-broker/pull/126
