### ISSUE TITLE
ES AWS Services - Track ES usage and hard limit in AWS

### ISSUE THREAD

**Issue by ChrisMcGowan** [cloud-gov/product#1442]
Per AWS: https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/aes-limits.html

Each AWS account and associated VPC are limited to 100 AWS ES Domains.  Currently we have ~43 elasticsearch instances on our legacy k8s infrastructure.

## Acceptance Criteria
* [ ] Track usage and plan next steps

--- 

## Security considerations
n/a

## Implementation sketch
* [ ] Contract AWS Support to see if this in fact a hard limit or something that can be updated
* [ ] If this is a hard limit, plan next steps on how to mitigate the issue to resolve the limitation

**Comment by karareinsel** [comment]
@ChrisMcGowan is this something that is ongoing, small checks? Or a larger effort? Could it be added to the weekly support tasks?
