### ISSUE TITLE
Update CIS listing and collateral documents

### ISSUE THREAD

**Issue by mheadd** [cloud-gov/product#1443]
Compliments the work done in #1393 by creating examples to accompany CIS docs that show how some typical apps on cloud.gov would be able to inherit (or render not-applicable) many of the 325 FedRAMP controls.

Acceptance criteria:

- [x] Remove outdated content on # of controls from website
- [x] Determine appropriate number of controls to consider for partner inheritance purposes (FedRAMP vs. FISMA)
- [x] Engage 18F Designer to assist with revamping controls listing
- [x] Revise website with update information on controls

**Comment by mheadd** [comment]
Initial design concepts: https://docs.google.com/presentation/d/1hYmQ91j1srmSjqFk_kWQAVGA_LGX4xCQygCy7iLXoKk/edit?ts=5f6a74a5#slide=id.g98ffe553ae_0_0

**Comment by karareinsel** [comment]
@mheadd does the CIS and customer responsibility matrix need to be updated? The version that's available on the website is from 2018.

**Comment by mheadd** [comment]
My understanding from @pburkholder is that we'll need to run changes to that document pasty the JAB. Until then, what we have is the authoritative version.

**Comment by mheadd** [comment]
Noting here that the CIS listing was also updated [in a separate PR](https://github.com/cloud-gov/cg-site/pull/1789).
