### ISSUE TITLE
Add test to perform small health check of the platform during deployments

### ISSUE THREAD

**Issue by ccostino** [cloud-gov/product#1448]
In order to ensure that our deployments are not going to break things in production, we want to add an additional health check to our deployment process to that helps ensure the system is still available and responding during deployments.

## Acceptance Criteria
* [ ] GIVEN a script that runs `curl` to hit the `info` endpoint at set intervals
  WHEN the curl call is made
  THEN an alert is sent to Slack indicating if the call succeed or failed

--- 

## Security considerations
None; this is just small additional step to check the things we're already doing in our open source deployment.

## Implementation sketch
[Please see the notes for additional details.](https://docs.google.com/document/d/133soq1mGroEE_8NurdhYV8uOXpI8VEpVpU0WvrlgMxU/edit#bookmark=id.e3gib2xfh06a)

**Comment by bengerman13** [comment]
I think this should be split into two issues, since there are two separate pieces of work here

**Comment by ccostino** [comment]
Modified this one to focus on curl check - adding another for the small app!

**Comment by karareinsel** [comment]
Revisit after Thanksgiving.
