### ISSUE TITLE
Add a small app (e.g., hello world example) that we can check on during deployments

### ISSUE THREAD

**Issue by ccostino** [cloud-gov/product#1450]
In order to ensure that our deployments are not going to break things in production, we want to add a small app that we can check on during deployments so that we have more confidence in things working correctly.

## Acceptance Criteria
* [ ] GIVEN a small hello world app that is running and scaled to 3 instances
  WHEN a deployment is performed
  THEN an alert is sent to Slack indicating if the app becomes unhealthy

--- 

## Security considerations
None; this is just a small additional step to check the things we're already doing in our open source deployment.

## Implementation sketch
[Please see the notes for additional details.](https://docs.google.com/document/d/133soq1mGroEE_8NurdhYV8uOXpI8VEpVpU0WvrlgMxU/edit#bookmark=id.e3gib2xfh06a)

**Comment by mheadd** [comment]
Is this related to this pipeline? Does the pipeline already do what is envisioned here? https://ci.fr.cloud.gov/teams/main/pipelines/test-hello-worlds
