### ISSUE TITLE
Export contact list

### ISSUE THREAD

**Issue by karareinsel** [cloud-gov/product#1452]
The business unit needs an export of the latest contact list of registered sandbox accounts. The export list should include the email addresses and names of all registered sandbox accounts. The BU team will use this list to assist with outreach efforts.

Moving forward, the BU team would like to receive the export list on a quarterly basis.

**Comment by mheadd** [comment]
As a first step on this one, can we identify the orgs that we want to target with outreach? Currently there are 110 orgs with `sandbox-` in the name. Some of these may no longer be sandbox accounts, or the partner may have transitioned to a new org. Which of those listed in the [attached spreadsheet](https://docs.google.com/spreadsheets/d/1Bdrv4cSXh2JkBz1bGm50xWY1kkQbI4rNN19DTzqH8ls/edit#gid=0) are sandbox orgs we want to target with outreach efforts?

If there is additional information for these orgs I can provide to help, just let me know.

**Comment by mheadd** [comment]
@kelleyconfer @jessykacastillo ☝️

**Comment by mheadd** [comment]
I think I might have found an easier way to do this via the Cloud Foundry API. Will have an updated org listing shortly.

**Comment by mheadd** [comment]
Added a new script to `cg-scripts` to support this work. https://github.com/cloud-gov/cg-scripts/pull/141

**Comment by mheadd** [comment]
First iteration of the report for the BU team listing user details for all sandbox users is here: https://docs.google.com/spreadsheets/d/13bpSKtLvG1GCVffoyaZJkHsV5GZk9v0ji5H2vCUH3bQ/edit#gid=379263413
