### ISSUE TITLE
Outline options to ship RDS instance logs to customers

### ISSUE THREAD

**Issue by pburkholder** [cloud-gov/product#1454]
In order to meet customer's security and compliance needs, they may need to receive instance event information either as logs or periodic reports.

This is an urgent need for one current customer already in production.

The scope of this issue is to generate options for meeting the AU-5 needs for one customer.

Options that are scalable and repeatable are good too

Implementation for either the one-off or the repeatable solution should be delegated to subsequent ticket.

--- 

## Security considerations

Solution will need to respect tenant isolation, so this simply won't happen for our shared databases.

## Acceptance criteria

* [ ] ~A repeatable process for customers is published at https://cloud.gov/docs/services/relational-database/~
* [x] An architecture document is committed to https://github.com/cloud-gov/internal-docs/tree/master/design-decisions
* [x] A decision is made on which implementation(s) to pursue and subsequent ticket(s) created.

**Comment by pburkholder** [comment]
Tagging @MelissaBraxton @mgwalker @mheadd

**Comment by JonathanLerner54** [comment]
Thanks Peter, Standing by for a solution from your guys . Much appreciated.

**Comment by pburkholder** [comment]
I've rescoped this issue to cover what we can do in one week, with one of the outcomes to create the next chunk of work. This doesn't change the overall goal here, but GitHub issues doesn't have a good mechanism for Epics, so scoping this smaller helps keep work moving across our board.

**Comment by spgreenberg** [comment]
@pburkholder Can you review the option I came up with here and provide feedback? https://docs.google.com/document/d/19v4ykZ5fIPygsHnz3ErcM5tdl6UZM62sGTMdE43XD2Q/edit?usp=sharing

**Comment by JonathanLerner54** [comment]
I'm can't access the document, I just clicked the request access, so standing by

**Comment by spgreenberg** [comment]
Hi @JonathanLerner54. In that doc, I outlined a possible solution that includes what I think are viable short and long term options. I cannot share that doc outside of our team given it is in a team folder (at least I don't believe I can). I would also like Peter to review it first as I want to be sure the requirements and intent of the work would be met.

**Comment by JonathanLerner54** [comment]
OK,  I was asked to review the document, so I’ll stand by while you work the issues out.

Thanks,

JON L

[Forest Service Shield]
Jon Lerner, CISSP
Cybersecurity Engineer
Forest Service Contractor
Forest Service
p: 703-943-8421
jonathan.lerner@usda.gov<mailto:jonathan.lerner@usda.gov>
1400 Independence Avenue SW
Washington, DC 20250
www.fs.fed.us<http://www.fs.fed.us/>
[USDA Logo]<http://usda.gov/> [Forest Service Twitter] <https://twitter.com/forestservice>  [USDA Facebook] <https://www.facebook.com/pages/US-Forest-Service/1431984283714112>
Caring for the land and serving people

**Comment by spgreenberg** [comment]
- Created Issues: https://github.com/cloud-gov/aws-broker/issues?q=is%3Aissue+is%3Aopen+label%3Ards-logs
- Internal doc: https://github.com/cloud-gov/internal-docs/blob/master/design-decisions/rds-logs-to-customers.md

@JonathanLerner54 I realize you can't see the internal doc link above but you should be able to see the issues above (let me know if you can't). In summary, we believe we can ship logs from RDS to S3 and/or Kibana (logs.fr.cloud.gov). There is a good amount of work required to make this happen but it should be possible.

**Comment by JonathanLerner54** [comment]
Thanks Steve,  Yes I have been following the progress.   So I'll be standing by for more info or seeing the new report.  

While you are working the issue, please look into allowing these report to be forwarded to User's SIEM tools.  This will greatly enhance cloud.gov's so that your users can implement a single pane of glass for operations and security situational awareness, reporting and Trend analysis.  

Regards,

JON L

**Comment by JonathanLerner54** [comment]
Please Add Matt Reiss to any future development on this as I am starting my retirement on Dec 01, 2020.
Matt's email is:  matthew.reiss@usda.gov
Thanks,

JON L
