### ISSUE TITLE
Review Concourse Workers (Next Steps Meeting - 10/26/2020)

### ISSUE THREAD

**Issue by ChrisMcGowan** [cloud-gov/product#1456]
In order to make sure we utilizing platform resources efficiently as possible, a review should take place on concourse workers to make sure the following is taking place:

- The correct number of workers for our workload is online at all times (# and size [cpu/mem] of VMs plus 30% surge capacity)
- Workers have the needed permissions to complete their tasks
- Define pool(s) of specific tagged workers if certain permission roles are required for certain concourse tasks

## Security considerations
That each IAM profile assigned to a worker pool is given least privilege needed to complete their tasks

## Implementation sketch
* [x] Review existing concourse deployments
* [x] Review existing concourse pipelines for tagged worker usage
* [x] Review worker IAM profiles
* [x] ~Adjust # and size of workers to handle task workloads effectively and in a cost effective manner for the platform~ (breaking out into subsequent issues)

**Comment by apburnes** [comment]
Added a PR ready for review to our internal documentation and will want to pair or possibly schedule a large operators talk about " Adjust # and size of workers to handle task workloads effectively and in a cost effective manner for the platform"

**Comment by apburnes** [comment]
Meeting is set for 10/26/2020 to determine next steps.  Will update ticket title and move to blocked until meeting.

**Comment by apburnes** [comment]
Closing with [meeting notes](https://docs.google.com/document/d/1yO5tDEeJ2jIGvmF0lyTu28WOnAZUyPw3GAjawrDtGL4/edit?usp=sharing) on next steps and issues to follow.
