### ISSUE TITLE
Explainer for agency vendor teams

### ISSUE THREAD

**Issue by mheadd** [cloud-gov/product#1460]
In order to help our partners being on vendors teams, we want a document or other artifact that describes cloud.gov to vendor teams and explains how it differs from traditional IaaS offerings.

## Acceptance Criteria

- [ ] Document that can be shared with agency partners for their vendor teams.
- [ ] Copy for the cloud.gov website that can be included in new or existing pages.

## Implementation sketch

- [ ] Should explain in succinct terms what cloud.gov platform is, and how vendor teams can get started understanding how it works before the develop a technology architecture for the partner.
- [ ] Should make specific reference to IaaS offerings and explain the equivalent or similar in cloud.gov
   * EC2 -> CF app instance
   * VPC -> CF org / spaces
   * AWS Internet Gateway -> api.data.gov
   * etc

**Comment by mheadd** [comment]
Also, underscore for partner that technical architecture decisions made by vendor team up front can have significant compliance implications down the road.

**Comment by markdboyd** [comment]
This ticket is stale and not a priority, so closing for now
