### ISSUE TITLE
Better error handling in prometheus aws rds check

### ISSUE THREAD

**Issue by ChrisMcGowan** [cloud-gov/product#1461]
The existing aws rds check python script needs better error handling when it can't pull stats/metrics from RDS instances that are unavailable like in a stopped state: https://github.com/cloud-gov/cg-deploy-prometheus/blob/master/ci/aws-rds-storage/rds_disk_space.py

## Acceptance Criteria
* [ ] update python script to better handle non-response on stats gathering and not fail concourse check

--- 

## Security considerations
n/a

## Implementation sketch
* [ ] Update script with error handling
* [ ] Test script for expected results using sample rds instances that are in a stopped state

**Comment by markdboyd** [comment]
Fixed by https://github.com/cloud-gov/cg-deploy-prometheus/pull/220
