### ISSUE TITLE
Concourse should alert on errors, not just failures

### ISSUE THREAD

**Issue by bengerman13** [cloud-gov/product#1477]
Right now, when concourse encounters an error outside of a build script (for example: getting rate-limited pulling docker containers, or encountering issues with Garden launching containers), it marks the job as errored but does not retry or alert us on the failure. We should add alerts for errored tasks, similar to our failed task alerts. 

I'm not sure if we can do this globally. If not, we should create sub-tasks for each pipeline to add these in.

**Comment by karareinsel** [comment]
+1 to breaking this into sub-tasks for each pipeline (doesn't appear it can be addressed globally). Closing this issue so it can be replaced with smaller, more incremental tasks.
