### ISSUE TITLE
Install Intermediate Certificate on Containers to support TLS

### ISSUE THREAD

**Issue by mheadd** [cloud-gov/product#1478]
In order to avoid issues with applications that need to use TLS and have trouble using certificate chains, we want to install both the intermediate and root certificates from AWS on all containers. (Note - the root certificate is already configured on all containers.)

The issue driving this change is explained more fully in [this support ticket](https://cloud-gov.zendesk.com/agent/tickets/2923).

## Acceptance Criteria
- [ ] Review all relevant documentation on installing certificates (if needed).
- [ ] Obtain certificate bundle from AWS.
- [ ] Update config / deployment pipeline(s) as need to install root and intermediate certificates. 
--- 

## Security considerations
This change will enhance the security of applications running on cloud.gov, as it will obviate the need for workaround for applications that have trouble using certificate chains.

**Comment by pburkholder** [comment]
Note that we'll need to install per:
> To get a certificate bundle that contains both the intermediate and root certificates for the AWS GovCloud (US) Regions, download from https://s3.us-gov-west-1.amazonaws.com/rds-downloads/rds-combined-ca-us-gov-bundle.pem.
