### ISSUE TITLE
ES/Redis broker - follow-up customer communications

### ISSUE THREAD

**Issue by karareinsel** [cloud-gov/product#1482]
In support of the deprecation of the legacy Elasticsearch and Redis broker deprecation, we should send a follow-up communication to customers who are still using the legacy brokers and encourage them to migrate to the new brokers. 

AC

- [x] Identify customers still using legacy brokers
- [x] Decide if we want to offer support to customers who are migrating
- [x] Draft communication
- [x] Send communication

**Comment by karareinsel** [comment]
@ChrisMcGowan [draft communication](https://docs.google.com/document/d/10rbi5lh7jqKsY-A_P5wQG0MFont0ujMNcp4ZACIJ0k0/edit) - ready for your review.

**Comment by karareinsel** [comment]
Communications will be sent to customers on 12/7/2020.

**Comment by karareinsel** [comment]
[Communications tracker ](https://docs.google.com/spreadsheets/d/1MEAYpgRb1lmVDoyCvJgQzgncKy-DaMlCzBgI9DsQp_c/edit#gid=1318675786)

**Comment by onelittlebecca** [comment]
Writing a communication response for when people email in asking for instructions on migrating. Will post here when it is drafted and ready for review.

**Comment by onelittlebecca** [comment]
Whew! Took a while to craft a good response, but finally got it sorted with a little help from the team! woot! Feel free to check it out! I added it to the doc with the initial communication on it. (Link is above and [here](https://docs.google.com/document/d/10rbi5lh7jqKsY-A_P5wQG0MFont0ujMNcp4ZACIJ0k0/edit))
