### ISSUE TITLE
Resolve BOSH CLI Slowness on create-release 

### ISSUE THREAD

**Issue by ChrisMcGowan** [cloud-gov/product#1485]
Recently CG ops switched the BOSH v2 CLI release in the concourse task image from the base `6.0.0` to current at the time `6.4.1` and it led to a 50X increase in the time it takes to build a BOSH release.

For now it was reverted back to `6.0.0` but the team needs to find out what which version between the 2 versions is causing the issue and report it to the community for repair.

## Acceptance Criteria
* Step through the versions to see which one introduces the delay 

## Security considerations
n/a

## Implementation sketch

* Update https://github.com/cloud-gov/cg-deploy-concourse-docker-image/blob/master/task/concourse-tasks/config.sh to tic up the BOSH CLI rev versions to find the culprit and report it to the community

**Comment by pburkholder** [comment]
In reviewing, https://github.com/cloudfoundry/bosh-cli/releases/:
* 6.0.0 was released on Aug 5, 2019
* 6.4.1 was released in Oct 2020.
There are no issues that seem related to performance.

**Comment by bengerman13** [comment]
Isolated this to 6.2.0 and opened cloudfoundry/bosh-cli#570

**Comment by bengerman13** [comment]
Blocked waiting on response from the bosh-cli team

**Comment by mheadd** [comment]
Add to next eng huddle meeting agenda.
