### ISSUE TITLE
Upgrade all PostgreSQL to 12+

### ISSUE THREAD

**Issue by pburkholder** [cloud-gov/product#1490]
In order to satisfy compliance requirements, we should upgrade all cloud.gov DBs to PG 12 or newer.

From AWS:

·         Starting with PostgreSQL 12, customer can select minimum TLS version in their database parameters.

·         We have already removed medium like RC4 in PostgreSQL 11.3+ and MEDIUM in all versions 12 and later.

·         AmVU will be updated to a later version by Q2 2021 but too early to give a date right now.

·         As for 2048 bit SSL certificate, an update is still outstanding (will press for additional information).

## Acceptance Criteria
- [ ] We've documented our status sufficiently to close all related POA&Ms

--- 

## Security considerations

This issue itself does not leak actionable info about weaknesses. The actions outlined improve our posture.

**Comment by JasonTheMain** [comment]
This work has been completed
