### ISSUE TITLE
Ship Kibana incident post-mortem to our StatusPage, blog and JAB TRs

### ISSUE THREAD

**Issue by pburkholder** [cloud-gov/product#1500]
In order to be transparent with our stakeholders, and to meet compliance requirements with the JAB, we should publish a post-mortem from the 2020-12-10 incident Kibana was not properly isolating logs from various tenants. 

https://cloudgov.statuspage.io/incidents/32bd83xh70qk is a good example of a public cloud.gov postmortem.

## Acceptance Criteria
* [x] Publish on statuspage
* [ ] Publish on blog?
* [ ] Ship to JAB TRs

Now that we're mostly back from holidays, we should do this first week in Jan 2021.
--- 

## Security considerations

Yes. We should take care not to say too much about unremediated operational weaknesses.

**Comment by ccostino** [comment]
I've completed the [draft public postmortem](https://docs.google.com/document/d/1JjpVz17IB3FbuOFsbUQ-kMEM0XgDYwoTRfm3TndSVo8/edit#heading=h.7fvo3akm48aj); ready for review and edits!

**Comment by pburkholder** [comment]
Thanks for drafting this. I'd just recently read the Google SRE guide to post-mortems so made edits/suggestions to shift from a narrative and more of a breakdown of key points. This is hard work but we'll get it right.

**Comment by ccostino** [comment]
Thanks!  I'll be working through the edits to hopefully get this finalized today.

**Comment by ccostino** [comment]
Postmortem is live!  https://cloudgov.statuspage.io/incidents/ylqdcn8nkv5f

I also changed the incident impact to `Major`, as I thought that's what it was (it was listed as `Critical` initially for some reason).

**Comment by ccostino** [comment]
This is ready for anything else required to send off to the JAB, @pburkholder!

**Comment by pburkholder** [comment]
I shipped to JAB with the public content plus the ["non-public info for stakeholders"](https://docs.google.com/document/d/1JjpVz17IB3FbuOFsbUQ-kMEM0XgDYwoTRfm3TndSVo8/edit#heading=h.medxvxvzw4f0)
