### ISSUE TITLE
Update Content-Security-Policy for "wildcard directive" findings

### ISSUE THREAD

**Issue by pburkholder** [cloud-gov/product#1503]
See : CG145 and 2021-V007-RA-5 and 2021-V008-RA-5

In order to provide exemplary web security, and remove Zap findings, we should update Kibana and account.fr to use comprehensive content-security policies.

For Kibana (7.6?) the policy is:
```
content-security-policy |script-src 'unsafe-eval' 'self'; worker-src blob: 'self'; style-src 'unsafe-inline' 'self'
```

the finding is:

>The following directives either allow wildcard sources (or ancestors), are not defined, or are overly broadly defined:
>img-src, connect-src, frame-src, frame-ancestors, font-src, media-src, object-src, manifest-src, prefetch-src, form-action
> The directive(s): frame-ancestors, form-action are among the directives that do not fallback to default-src, missing/excluding them is the same as allowing anything.

Based on https://w3c.github.io/webappsec-csp/#parse-serialized-policy, I think the policy should be something like: `Content-Security-Policy: default-src 'self'; script-src 'unsafe-eval' 'self'; worker-src blob: 'self'; style-src 'unsafe-inline' 'self'`  where we've added `default-src: 'self'`

This should be configurable based on the `csp.rules` settings at https://github.com/elastic/kibana/blob/master/docs/setup/settings.asciidoc

For account.fr, the CSP for, say, https://account.fr.cloud.gov/signup is:

```
content-security-policy: default-src 'self'; script-src 'self'; connect-src 'self'; object-src 'self'; frame-ancestors 'self'; img-src 'self' *.cloud.gov; style-src 'self' *.cloud.gov *.googleapis.com; font-src 'self' fonts.gstatic.com *.cloud.gov
```

The ZAP report is:

> The following directives either allow wildcard sources (or ancestors), are not defined, or are overly broadly defined:
> form-action
> The directive(s): form-action are among the directives that do not fallback to default-src, missing/excluding them is the same as allowing anything.

It seems like we should a) remove the googeapis.com, b) add form-action

--- 

## Security considerations
[note any potential changes to security boundaries, practices, documentation, risk that arise directly from this story]

**Comment by bengerman13** [comment]
@pburkholder does that mean we can close this issue?
