### ISSUE TITLE
Identify issue with 621.95 stemcell

### ISSUE THREAD

**Issue by ChrisMcGowan** [cloud-gov/product#1505]
In late Dec'20 - the 621.95 stemcell seemed to be causing issues with the bosh director deployments. The team un-checked .95 and left BOSH on .94

## Acceptance Criteria
* [x] Resolve why the .95 stemcell causes issues with the directors and make adjustments to repos as needed.

**Comment by pburkholder** [comment]
It magically fixed itself when Chris fixed clamav. We're working on getting .101 stem cells rolled out

**Comment by ChrisMcGowan** [comment]
Changes to clamav:
https://github.com/cloud-gov/cg-clamav-boshrelease/commit/38f193129e9061091d99e2e287b36f2c8f38fb3a

and

https://github.com/cloud-gov/cg-clamav-boshrelease/commit/7fa516d7a1ea88ff7690018d1e631b972a3b3c28
