### ISSUE TITLE
Fix domain-broker inconsistencies in cg-provision

### ISSUE THREAD

**Issue by bengerman13** [cloud-gov/product#1508]
In order to stop having false changes and reduce the likelihood of creating problems,  we want to resolve the name conflict/resource conflict in terraform

## Acceptance Criteria
* [ ] GIVEN terraform/stacks/main/domain_broker_v2_do_not_delete.tf is deleted \
  AND terraform plan shows no changes \
  WHEN terraform apply is run \
  THEN no necessary production resources are deleted \
  AND no unnecessary domain broker resources remain

--- 

## Security considerations
None

## Implementation sketch
See comment here: https://github.com/cloud-gov/cg-provision/blob/68a4dafe8375d098d42abb96a41c7bf350917c73/terraform/stacks/main/domain_broker_v2_do_not_delete.tf#L1-L18

Tammer said this requires state surgery to fix. It seems plausible to me there's a different way to go about this, but I don't know for sure.

**Comment by soutenniza** [comment]
With the new terraform 12 - the output is prettier so we can actually see the differences!!!

Ben & I gathered that both staging + production is using same aws_iam_user_policy so when terraform for each environment is trying to correct each other all the time.... 

In theory the best fix is create another policy where id + name includes environment then add those then delete the old one after.

Will do this after we are done upgrading terraform
