### ISSUE TITLE
Evaluate the feasibility of migrating Federalist repositories to the cloud.gov Github organization

### ISSUE THREAD

**Issue by karareinsel** [cloud-gov/product#1511]
Do we use Terraform?

Do we use Tech Portfolio's Terraform work?

Can we move w/o impacting existing CircleCI work?  Are there compliance implications to moving a repo? Can we test that?

How do we move in advance of this being an approved SCR?

Also:
- [ ] Create a `pages-ops` team to mirror the `platform-ops` -team

**Comment by pburkholder** [comment]
After looking at this again for the first time in a few weeks, I am _OK_ with moving these whenever it makes sense. The presence of Pages repos in the cloud-gov org does not impact our compliance, nor does adding a new pages-ops team.
