### ISSUE TITLE
Resolve BOSH-DNS issues

### ISSUE THREAD

**Issue by ChrisMcGowan** [cloud-gov/product#1521]
On 2/2/2021 - VMWare updated bosh-dns to version `1.28.0` which included a rev of Go to `1.15`
https://github.com/cloudfoundry/bosh-dns-release/releases/tag/v1.28.0

This rev of Go caused issues at CG as the default runtime bosh-dns certificate definitions where not updated. Go `1.15` started to enforce certificates requiring a SAN (Subject Alternative Name) and not just a common name as the bosh-dns certs are currently setup.

CG rolled back `bosh-dns` to `1.27.0` and pinned the `deploy-bosh` pipeline resource for `bosh-deployment` back to just before the `bosh-dns 1.28.0` release.

## Acceptance Criteria
* [ ] Establish path forward on resolving being pinned back on a older `bosh-dns` release that CG support can maintain

--- 

## Security considerations
* Try to not use a `GODEBUG` value to bypass the error

## Implementation sketch
* Review the `bosh-dns` releases to see how VMWare corrects the issue: https://github.com/cloudfoundry/bosh-dns-release/releases/
* Review the response by VMWare to our open issue on the subject: https://github.com/cloudfoundry/bosh-dns-release/issues/76

**Comment by ChrisMcGowan** [comment]
So VMWare went and updated bosh-deployment to now include SAN names for the certs: https://github.com/cloudfoundry/bosh-deployment/commit/2c4b119969cf2bac24606bde83fcf1508a196896

It mentions you can do an in-place update using `update_mode: converage` as listed here: https://bosh.io/docs/manifest-v2/#variables but the reference use link for the api is down and appears to be down now for a few days as noted here: https://github.com/cloudfoundry-incubator/credhub/issues/176. - not quite sure that does and I don't see an option to do it in the credhub cli

Looks like the cf-dev folks do that already - example here: https://github.com/cloudfoundry/cf-deployment/blob/eb4dc49eafa018aa87b406be7abd1a306399f450/cf-deployment.yml#L1867

So the course of action would be:

- Modify one of our deploy-bosh ops files temporary (https://github.com/cloud-gov/cg-deploy-bosh/tree/master/operations)  to include the SAN changes as well as the update_mode change, push the changes, and run the pipeline for common releases to update the dns run-time config.
- Deploy all bosh deployments in all environments that use bosh-dns to get the new cert changes
- Pause all common releases jobs and then remove our temp changes to allow upsteam changes from bosh-deployments
- Unpin the bosh-deployments and allow the new version with bosh-dns `1.28.0` and runtime changes to come in
- Unpause and run common releases
- Deploy all bosh deployments in all environments that use bosh-dns to get the new bosh-dns code

**Comment by karareinsel** [comment]
@ChrisMcGowan is this done? Can it be closed?

**Comment by jfredrickson5** [comment]
> It mentions you can do an in-place update using update_mode: converage as listed here: https://bosh.io/docs/manifest-v2/#variables but the reference use link for the api is down and appears to be down now for a few days as noted here: cloudfoundry-incubator/credhub#176. - not quite sure that does and I don't see an option to do it in the credhub cli

Looks like that broken link is now fixed, so [here is the CredHub reference](https://docs.cloudfoundry.org/api/credhub/version/2.9/#_overwriting_credential_values).
