### ISSUE TITLE
Resolve Increase in loggregator dropped envelope messages 

### ISSUE THREAD

**Issue by ChrisMcGowan** [cloud-gov/product#1522]
We have noticed an up-tick in loggregator messages on dropped envelope messages and grafana does show a slow but steady increase in the amount of dropped envelopes over the last 30 days.

Review needs to take place to see what changes and possible scaling can take place (VMWare recommends horizontal scaling) to lower the amount of loss.  We do accept that the platform will always have some level of loss.

**Comment by bengerman13** [comment]
Started here: https://docs.cloudfoundry.org/loggregator/log-ops-guide.html#scaling

_if_ I'm looking at the right metrics, we're actually over-scaled on doppler instances, but our doppler:traffic controller ratio is correct. They recommend 1 firehose consumer per traffic controller, and we're low there.

**Comment by bengerman13** [comment]
this has had no effect here. I asked for some guidance in the CF slack. Waiting for a response there.
