### ISSUE TITLE
Assist Customers with Automatic PostgreSQL Upgrade

### ISSUE THREAD

**Issue by mheadd** [cloud-gov/product#1525]
AWS is [updating brokered RDS for PostgreSQL instances using PostgreSQL version 9.5](https://forums.aws.amazon.com/ann.jspa?annID=8176) beginning this coming Monday, February 15th, 2021. We need to identify all impacted RDS instances and upgrade to the appropriate version (v 9.6 _looks_ like it may be sufficiently recent to avoid the automatic upgrade) and assist any customers impacted with their migration as well. The number of impacted customers is small, so manually assisting them should be doable by engineering staff.

## Acceptance Criteria

- [x] Identify all RDS instances potentially impacted
- [x] Reach out to AWS customer reps to see if delaying this automatic upgrade for specific instances is possible
- ~[ ] Update all internal RDS instances being used by cloud.gov broker applications~
- [x] Reach out to all external customers potentially impacted
- ~[ ] Assist customers with migration by bumping PostgreSQL version manually in AWS console as needed~
- [ ] Follow up on original email to customers informing them of the new information we received from AWS. @onelittlebecca

**Comment by karareinsel** [comment]
[Messaging to customers](https://docs.google.com/document/d/180oGKwZz3McY3xXgVz3jxvaop9zAaVBS2sY701vNFPk/edit?ts=60248568)

**Comment by karareinsel** [comment]
Emails have been sent to customers.

**Comment by mheadd** [comment]
So, it looks like this was a false alarm from AWS..?

```
I have received an update from the RDS internal team. The force-upgrade notification for PostgreSQL 9.5 was posted in error in the GovCloud regions. RDS is working on providing a new date for the PostgreSQL 9.5 upgrade as soon as possible. RDS will give sufficient time to test and prepare for the upgrade.

To summarize, at this time there is no process underway to force-upgrade your database instances running PostgreSQL 9.5. Once the new date is determined, RDS will communicate the date to you.

I apologize for any inconvenience or confusion this may have caused. Please let me know if you have any additional questions.
```

**Comment by mheadd** [comment]
`Update all internal RDS instances being used by cloud.gov broker applications` should probably be moved to a separate stand alone ticket.
