### ISSUE TITLE
Patch Kubernetes before 03/05 (schedule by 02/24)

### ISSUE THREAD

**Issue by pburkholder** [cloud-gov/product#1527]
Nessus detected a High vuln on 2021-02-03, so we need to patch before 2021-03-05. If we bundle all High patches and fixes available by that date then we won't have to patch K8s again.

To do: 
- [ ] include all apt-get updates
- [ ] review all newer kernel findings and implement fixes -- this could take a day.

**Comment by ChrisMcGowan** [comment]
PR cut for sudo and ldap patches:
https://github.com/cloud-gov/kubernetes-release/pull/128

**Comment by ChrisMcGowan** [comment]
Plan is to get through dev and stage today and cut notification on scheduled maintenance for Wed March 3rd to apply to Prod
