### ISSUE TITLE
ES/Redis deprecation notice for StatusPage

### ISSUE THREAD

**Issue by karareinsel** [cloud-gov/product#1537]
Create a new notice to post on StatusPage to notify customers of the upcoming ES/Redis deprecation which will take effect on 4/5/2021.

- [x] Create draft of notice
- [x] Share with team for feedback
- [x] Publish to StatusPage
- [x] Tweet announcement from the cloud.gov Twitter account

**Comment by ChrisMcGowan** [comment]
First pass at doc:
https://docs.google.com/document/d/1awek_gfodH5mGY73bCw2afGKRCY1O_M_emJ1ovKzYOY/edit
