### ISSUE TITLE
Close out post-mortem for 502 incident

### ISSUE THREAD

**Issue by karareinsel** [cloud-gov/product#1539]
We hypothesize that what happened on 2021-03-05 will happen again, and soon. When it does, we need to be sure our site is resilient.

Potential work to do. Discuss with team how much of it we can take on:

- [x] Obtain support from AWS for more details on IPs involved (time limit effort here if they're not helpful)
- [ ] Share details on incident with GSA-IR and US-CERT
- [ ] Follow up with one detailed report to abuse@cloudproviders (make sure we're using the right channel/email)
- [x] Prepare selection of "Protect" technical measures, the relative effort and impact
- [x] Prepare selection of "Detect & Respond" technical measures
- [x] Hold another meeting to review and decide on measures.
- [ ] Post a public incident post-mortem with steps we're taking
- [ ] Ship an incident post-mortem to JAB TRs, with POA&Ms for the steps we're taking

This ticket needs grooming by the Engineering Huddle....

[Incident notes: ](https://docs.google.com/document/d/1Kfr34INqqbVZotFLyavDmmfP4h314-EQZn_pppLVR0M/edit#heading=h.44pjqgdczk2v )

[Incident PM meeting](https://docs.google.com/document/d/1Q987n-kZ1LWQCNm6126oJagen80-HthnF0DG3NBBwnQ/edit#heading=h.ner6wmke618c)

**Comment by pburkholder** [comment]
We met on 2021-04-09, with our [notes in the same document as before](https://docs.google.com/document/d/1Q987n-kZ1LWQCNm6126oJagen80-HthnF0DG3NBBwnQ/edit#heading=h.ner6wmke618c).

@bengerman13 and @mheadd are working on the full writeup. 

A redacted write-up willl go on Statuspage once the mitigation work is complete. The full write-up will go to the JAB, GSA-IR (and thence to CERT).

We can close this once:

- [ ] the full write up is shipped to the JAB
- [ ] Peter has checked on the current CloudFront status with the JAB
- [ ] The engineering team has tickets in the backlog for the next steps.
- [ ] We have a POA&M created for that same work.

**Comment by mheadd** [comment]
Draft incident post-mortem statements are [here](https://docs.google.com/document/d/1Q987n-kZ1LWQCNm6126oJagen80-HthnF0DG3NBBwnQ/edit?ts=60776fd9#heading=h.gky3fo7tknuo).

**Comment by bengerman13** [comment]
Action item tickets and PRs:
cloud-gov/logsearch-for-cloudfoundry#86
cloud-gov/cg-deploy-cf#541
cloud-gov/cg-provision#821
