### ISSUE TITLE
Develop a Pages PenTest plan with 3PAO 

### ISSUE THREAD

**Issue by pburkholder** [cloud-gov/product#1540]
In order to keep Pages on track for FedRAMP SCR, we need to work with CoalFire on a pentest approach for their SAP

## Acceptance Criteria
* [ ] 3PAO agrees they understand the outline of Federalist/Pages operations well enough to determine LOE and scope for Security Assessment Plan

Elements that will need to be included:
- NO: Local workstation: 
- Yes: phishing / social engineering
- Yes: Web Applications
- Yes: Multitenancy between customers (

--- 

## Security considerations

Use secure channels with 3PAO if discussing potential weaknesses.

**Comment by pburkholder** [comment]
I've sent email to 3pao pentest lead asking for a meeting. Waiting for him to propose times.

**Comment by karareinsel** [comment]
@pburkholder is there another pentest plan that we could work from? That'll make it easier to get this work started.

**Comment by pburkholder** [comment]
The 3PAO will come up with the pentest plan. That's on them. They just need to know to pentest and how to pentest it. 
Examples: 

* [The Pentest plan from the 2020 annual assessment](https://drive.google.com/drive/search?q=pentest%20parent:1_ZfKJySzlBKBnQ6tP73z5nfVs9sWpmCX)
* [The 2020 Redis/Elasticsearch SCR charter had a pentest scope (page 8)](https://docs.google.com/document/d/1K4B3vV7yQsM59Q9JASZtXQfp5T1jsuNm/edit)

**Comment by pburkholder** [comment]
@apburnes I think is done enough to done and any followup questions are just in the flow of work.
