### ISSUE TITLE
Disable Shared Database plans in Production

### ISSUE THREAD

**Issue by RonWilliams** [cloud-gov/product#1547]
On August 21, 2020 we announced that shared databases would be disabled as of January 24, 2021. The shared plans are still available and we should disable access to create new instances of the plan type at this time. 

Initial announcement: https://cloudgov.statuspage.io/incidents/0v1nwyybb0fs

Related task: https://github.com/cloud-gov/product/issues/1391

**Comment by bengerman13** [comment]
Remember to update cg-site docs

**Comment by jfredrickson5** [comment]
The general plan:

- [ ] Remove content from cg-site (https://github.com/cloud-gov/cg-site/pull/1919)
- [ ] Disable and remove services and smoke tests in dev
- [ ] Disable and remove services and smoke tests in stage
- [ ] Disable and remove services and smoke tests in prod
- [ ] Remove shared RDS instances from the catalog
- [ ] Create snapshots of the shared MySQL and PostgreSQL instances
- [ ] Remove RDS instances via Terraform
- [ ] Remove Concourse credentials

**Comment by jfredrickson5** [comment]
Site docs are updated to remove mentions of the shared databases. Any examples now use the micro plans instead of the shared plans. Disabled the shared-psql and shared-mysql plans via `cf disable-service-access`.

**Comment by RonWilliams** [comment]
The intent of this ticket was to disable the plan availability to create new instances, per our deprecation announcement. We have not announced the shutdown of existing instances on the shared DB. The work of @jfredrickson5 here should help us move in that direction if we choose to do so.

Can we add this for discussion in the next engineering huddle? This is a low priority, so consider delaying discussion until @bengerman13 is available.
