### ISSUE TITLE
Support package for Xenial stemcell patching

### ISSUE THREAD

**Issue by karareinsel** [cloud-gov/product#1548]
Purchase a support package for the Xenial stemcell patching.

**Comment by kelleyconfer** [comment]
Current status: 
• RFI is released on eBuy 3/29 - 4/2 (any questions will need to be submitted by 4/1)
• RFI draft is located [here](https://docs.google.com/document/d/1lxoAbvU2elekESn_VzqYTWOGioStGSrJj1Wwcpf2WJ8/edit?ts=605e3bf4#)
• Once RFI results come in, we will determine the next steps for the acquisition. Best case scenario, we will have ample vendors/resellers and will be able to make a direct award.

**Comment by kelleyconfer** [comment]
Met with acquisition team today, RFI had closed on Friday (4/2) with no quote responses. 

We are looking for a vendor/reseller on schedules, but haven't been making much progress. Acq team is meeting internally and will update us on possible avenues if we have to do open market.

**Comment by kelleyconfer** [comment]
Updates regarding acquisition: 
• Will be releasing an RFQ on NASA SEWP imminently (today 4/13 or tomorrow, 4/14)
• RFQ will likely be out through the end of the week (4/16)
• Proposal review happening Monday or Tuesday of next week (4/19-4/20), will just be reviewing for pricing
• No foreseen issues with awarding NLT the 4/30 drop dead date of current Canonical support
