### ISSUE TITLE
Blog post: From Drupal 7 to cloud.gov

### ISSUE THREAD

**Issue by mheadd** [cloud-gov/product#1553]
## Audience

As a site owner or maintainer of a Drupal 7 site, I want learn how to migrate my site to Federalist or cloud.gov to avoid the scheduled end of life for Drupal 7 within the next year. 

## Goal of the post

Provider information on how Drupal 7 sites can be transitioned to cloud.gov Platform or Pages.

## Imagery ideas

N/A

## Outline

* Discuss imminent EOL for Drupal 7
* Discuss benefits of cloud.gov platform
* Highlight a few general strategies for migrating.
* Ask readers to reach out for more in depths discussion / assistance.

## Who needs to clear

- [ ] cloud.gov ED (or acting)
- [ ] @kelleyconfer 
- [ ] @karareinsel

**Comment by karareinsel** [comment]
Great blog post topic!

**Comment by wz-gsa** [comment]
No longer relevant
