### ISSUE TITLE
Parent issue for several xenial to bionic stories

### ISSUE THREAD

**Issue by ccostino** [cloud-gov/product#1570]
This is a parent issue to capture all of the future work we'll need to do to with moving from xenial to bionic stemcells.  After our meeting today to working through the PR we received (https://github.com/cloud-gov/cg-awslogs-boshrelease/pull/47), we came up with the following tasks:

- Build bionic pipeline for awslogs
- Include/exclude support for all pipelines
- Look at hardening release next and note differences
    - Can it stay a single release to determine OS, or separate for each?
- How we want to test each of the runtime releases on bionic (all sub-releases)
    - Includes an assumption that BOSH DNS is fine and certified
- Performance/tracking between xenial and bionic
- Check on Nessus licenses and if we can run scans on both Xenial and Bionic, or just one
- Going through each custom releases (including admin UI) - e.g., AIDE, Clam-AV, cron, domain-broker, elb-log-inspector, log-cache (part of Elastic?), logsearch/logsearch-cloudfoundry, oauth2-proxy, prometheus, secure proxy, shibboleth, uaa-customize, etc.
    - Have to account for compliance scanning with Nessus; need to have to this discussion now due to possibility of purchase

We'll have to create separate issues for each of these with more details.

## Security considerations
- This represents the work that will enable us to move to using the newer bionic stemcells within Cloud Foundry
- [x] Ensure compliance checks are bumped from 16.04 to 18.04 (Added 2021-09-03)

**Comment by ccostino** [comment]
@ChrisMcGowan, @soutenniza, @apburnes, and @onelittlebecca, did I miss anything here?  Please feel free to correct!

@karareinsel, this issue itself probably doesn't need to be prioritized, but the work that comes out of it will.  That said, we'll still need to set aside some time to break this down and create the separate issues.  This probably makes sense as an engineering huddle activity, but I wanted to make sure you were aware too.  Thanks! :-)

**Comment by karareinsel** [comment]
Can this issue be closed out since we have other, smaller issues to address the work?

**Comment by ChrisMcGowan** [comment]
Project compliance board is in place and updated with swim lanes:
https://github.com/orgs/cloud-gov/projects/15

Tickets for all BOSH deployments are now defined

**Comment by ChrisMcGowan** [comment]
Pinning Ubuntu-bionic-stemcell 1.22 for the duration of this project

**Comment by pburkholder** [comment]
Added that we need to update compliance check from 16.04 to 18.04. 

And now I've checked that off. 

I've added both the L1 and L2 CIS checks.

**Comment by karareinsel** [comment]
Remaining work will be addressed by #1609 so closing this story.
