### ISSUE TITLE
Decide whether to add Elasticsearch Service plans

### ISSUE THREAD

**Issue by bengerman13** [cloud-gov/product#1574]
We have users asking for some specific configs for ES.
We should document what they want, and collaborate between BU and platform to see what we want to offer.

cc: @ccostino

**Comment by ccostino** [comment]
@bengerman13 were you clearing out old issues?  Should we place this in the https://github.com/cloud-gov/aws-broker repo instead?  A question about this came up recently, and the issue we just ran into with RDS yesterday has me thinking about this again as well.

**Comment by bengerman13** [comment]
yeah, closing old issues. This wasn't spelled out clearly enough to go anywhere, I think

**Comment by ccostino** [comment]
No worries, thank you!
