### ISSUE TITLE
Explore the use and value of a tool like CloudCheckr or DataDog

### ISSUE THREAD

**Issue by ccostino** [cloud-gov/product#1577]
In order to have better visibility about resource consumption and costs of our cloud infrastructure, it would be useful to have a tool like CloudCheckr or DataDog available to us so that we can better track our cloud resource utilization.

We have used CloudCheckr in the past, but whatever we end up considering we should note the following:

- It would need to be FedRAMP (JAB?) authorized
- We'd have to consider cost as we'd likely have to buy it

If there's a buy involved, it might also be worth exploring if other parts of TTS could benefit from it.

## Security Considerations
- Having access to such a tool could help us stay on top of cloud resources that require updates/patching

**Comment by markdboyd** [comment]
This ticket is stale and does not reflect an active team need 

There has been a lot of work around tagging resources more effectively and using AWS Cost explorer to break down costs by tag, which reduces the need for this ticket
