### ISSUE TITLE
Migrate federalist content to cloud.gov pages

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/product#1578]
In order to migrate Federalist to CG Pages, we want add content from the federalist.18f.gov site into the cloud.gov site. To facilitate the migration, the following tasks can released independently to cloud.gov to be as transparent as possible. This is larger epic issue that will continue to change as the migration progresses.

## Acceptance Criteria Tasks
* [ ] Create an announcement page on cloud.gov
* [ ] Add a new landing page based on the content from federalist.18f.gov under cloud.gov/pages
* [ ] Add product features to cloud.gov
* [ ] Add customer success stories to cloud.go
* [ ] Migrate docs
* [ ] TBD
--- 

## Security considerations
none

**Comment by wz-gsa** [comment]
Confirmed with @drewbo this is no longer needed
