### ISSUE TITLE
June Tech Talk: Strategies for Migrating Legacy Drupal to Federalist 

### ISSUE THREAD

**Issue by kelleyconfer** [cloud-gov/product#1579]
*AC*

- [x]  Determine topic from list of potential topics
- [x]  Determine who will be leading/presenting the Tech Talk
- [x]  Set up the Zoom Link
- [x]  Arrange for Fed Relay for closed captioning
- [x]  Summarize tech talk in run of show for Eventbrite
- [x]  Set up Eventbrite invite to share
- [x]  Prepare talk and any visual materials
- [x] Send recording of TT to DGU to upload to YouTube 
- [x] Send follow up with youtube link

**Comment by onelittlebecca** [comment]
@mheadd and I are meeting on this this afternoon to touch base!

**Comment by karareinsel** [comment]
6/22 update: Digital.gov has a new policy regarding the posting of video content on their site. They will get back to us by Friday, 6/25 with next steps. @kelleyconfer FYI.

**Comment by karareinsel** [comment]
This is the new policy from digital.gov. I'm confirming if this applies to videos that live on our playlist.

We recently received feedback about some accessibility issues with Digital.gov’s YouTube videos. Based on this feedback, we are implementing some new processes to ensure our videos are accessible and conform with the Revised 508 Standards, including:

- Improving the quality of captioning for pre-recorded videos. Before posting a recording, the captions need to be reviewed and edited to ensure they have proper spelling and grammar, indicate meaningful sounds and changes in speakers, and are synchronized with the speech.

- Ensuring presenters provide complete audio descriptions during their presentations for any visual aids used, such as graphics, pictures, embedded video, or demos. 

Retrofitting video recordings after a live event can be time-consuming — and sometimes impossible. So, in this case, we recommend publishing the content as a blog post on Digital.gov to share Strategies for Migrating Legacy Drupal to Federalist.

Alternatively, to post the pre-recorded video, we would need your team to:
Review and edit the YouTube captioning as described above; and,
Add any missing or incomplete audio descriptions to the audio recording. 
To make these changes, you may be able to obtain assistance from GSA IT’s Section 508 office or via the #helpwanted channel in TTS Slack. 
Moving forward, the best way to create accessible videos is to build these considerations into the live presentations from the start. For more information on creating accessible videos, please visit https://www.section508.gov/create/video-social.

**Comment by mheadd** [comment]
If it would be easier, I can write this up as a blog post. I can get started on that now.

**Comment by mheadd** [comment]
Questions:

Would the blog post live on Digital.gov? Or on our site?
If the former, could we republish on our site with the video? Or link to our site with the video?

cc: @geraldsill

**Comment by karareinsel** [comment]
I think we can decide where we want to publish the blog post. Publishing it on cloud.gov is easy and good practice. Can we confirm if we can embed a video in one of our own blog posts? We'd need digital.gov's help to publish the blog post on their site.
