### ISSUE TITLE
Verify the correct AWS regions are shown in StatusPage

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/product#1584]
In order to show the AWS status on our status page, we use the third party integration to show AWS status by region.  Currently the "**Services cloud.gov depends on**" is showing certain AWS services in the `us-west-1` and `us-west-2` regions when we should be using the `gov-west-1` region.  

Current screen shot
<img width="1190" alt="Screen Shot 2021-06-23 at 3 07 24 PM" src="https://user-images.githubusercontent.com/693815/123174667-5509e880-d435-11eb-8665-58a8130b8cdc.png">

## Acceptance Criteria
* [ ] Log into the statuspage account and turn or the applicable AWS services and regions in the third-party integration.

--- 

## Security considerations
none

**Comment by ccostino** [comment]
I took a look in StatusPage and it looks like this is just a label.  @apburnes, would you like to pair on this for a short bit to see if we can verify and then just correct the labels if that's all it is?
