### ISSUE TITLE
Concourse for Pages - Production

### ISSUE THREAD

**Issue by soutenniza** [cloud-gov/product#1585]
In order to have compliant ci, the Pages team needs to use concourse.

## Acceptance Criteria
* [] Credential storage: We currently store credentials in S3 and inject them during set-pipeline calls. This is not ideal for the Pages team as they would need access to S3 buckets. The cg ops team has also discussed moving away from using S3 for ease of use and to remove sensitive information from our pipelines. Concourse + Credhub integration is desired as Concourse will fetch credentials at runtime, keeping creds completely out of pipelines.

* [] Authentication: Currently, cg operators authenticate via opslogin.fr.cloud.gov and are granted access via the existence of the concourse.admin scope. The Pages team can be added to OpsLogin and individually assigned to roles in Concourse. 

* [] Authorization: Current cg operators are all administrators of Concourse. The Pages team only needs access to their pipelines and their credentials following the principles of least privilege.
--- 

## Security considerations

See https://github.com/cloud-gov/internal-docs/blob/master/design-decisions/concourse-pages.md. This outlines the required authentication and authorization controls.

## Implementation sketch

See: https://github.com/cloud-gov/internal-docs/blob/main/concourse/concourse-pages.md

### Staging

- [] Add a local admin user to prevent lockout (https://github.com/cloud-gov/internal-docs/blob/master/runbooks/concourse/default-local-account.md)
- [] Pipeline to deploy Credhub (https://github.com/cloud-gov/deploy-credhub)
  - [] DNS: credhub.fr.cloud.gov 
  - [] ALB rule
  - [] Use OpsUAA for authentication
  - [] Test ACLs
  - [] Pages team ACLs (use terraform)
  - [] Hook up new Credhub to doomsday
- [] Configure concourse to talk to credhub
  - [] Verify no existing pipelines are affected  
- [] Configure a Pages team in Concourse
  - [] Establish RBAC using OpsLogin
  - [] Test team pipeline

**Comment by markdboyd** [comment]
Confirmed with @soutenniza that this can be closed. There is separate work being done to implement Concourse for the Pages team
