### ISSUE TITLE
Provide access to database performance statistics / information

### ISSUE THREAD

**Issue by mheadd** [cloud-gov/product#1586]
In order to monitor RDS instances and troubleshoot application issues, platform users want access to performance information and statistics for their RDS services. Work related to this story is also described [here](https://github.com/cloud-gov/aws-broker/issues/171).

--- 

## Security considerations
TBD. Likely none.

## Implementation sketch

* https://aws.amazon.com/premiumsupport/knowledge-center/rds-postgresql-pgaudit/
* https://aws.amazon.com/premiumsupport/knowledge-center/rds-postgresql-resolve-preload-error/
* https://www.postgresql.org/docs/12/monitoring-stats.html#MONITORING-STATS-VIEWS

**Comment by markdboyd** [comment]
Superseded by

https://github.com/cloud-gov/private/issues/957
https://github.com/cloud-gov/private/issues/747
