### ISSUE TITLE
Contact existing Federalist customers about the migration

### ISSUE THREAD

**Issue by kelleyconfer** [cloud-gov/product#1592]
Contact existing Federalist partners about migration and ATO changes so that they are up-to-date and well informed. 

- [x] Draft Comms ([tracked here](https://docs.google.com/document/d/1QL_rK41xOA8uh-l9od2H5FwOz1biO82vaCTWwUzPNmY/edit)) 
- [x] Initial wave of comms to determine the org manager 
- [ ] Track all technical PoCs and programmatic [PoCs here ](https://docs.google.com/spreadsheets/d/1ok2f8xWuI0vFThVINIPJ6fRiJbjsJohcOchtMiuEur8/edit#gid=0)

**Comment by melanienleopold** [comment]
### Upcoming Renewals and PoP End Date:

- TTS Solutions / Federalist / DOD / JAIC FY2021 **8/8/2021**
- TTS Solutions / Federalist / Census FY2021 **8/11/2021**
- TTS Solutions / Federalist / FFB FY2021 **9/28/2021**
- TTS Solutions / Federalist / OES FY2021 **9/25/2021**
- TTS Solutions / Federalist / GSA OGP Performance.gov FY21 **9/25/2021**
- TTS Solutions / Federalist / USACE MRSI FY21 **8/19/2021**
- TTS Solutions / Federalist / DOI USGS FY2021 **8/22/2021*
- TTS Solutions / Federalist / VA / Reach.gov FY20 **8/19/2021**
- TTS Solutions / Federalist / GSA OGP / FICAM FY2021 **9/25/2021**
- TTS Solutions / Federalist / VA CTO FY2021 **8/25/2021**
- TTS Solutions / Federalist / OGP / Web Platforms for Councils FY21 **10/1/2021**
- TTS Solutions / Federalist / USAF FY2021 **9/20/2021**
- TTS Solutions / Federalist / GSA CTO / FY21 **9/30/2021**
- TTS Solutions / Federalist / DHS / Cyber Sites FY21 **11/5/2021**

**Comment by kelleyconfer** [comment]
All outreach has been sent, currently waiting to hear back from remaining partners. 

Will follow up on Friday, 8/6 for those who haven't responded.

**Comment by melanienleopold** [comment]
Followed up with the 5 Federalist customers I reached out to that haven't responded on 8/10.
