### ISSUE TITLE
research TLS usage 

### ISSUE THREAD

**Issue by bengerman13** [cloud-gov/product#1595]
In order to gauge the impact of disabling TLS1.0 and TLS1.1 on our ALBs, we should get numbers on TLS usage on our ALBs.

It would be good to know:
- TLS usage by version across the platform
- top users of TLS < 1.2

We should be able to get this from ALB logs, which are in an S3 bucket. This gist may be helpful: https://gist.github.com/bengerman13/4b31709aa1915da73900fd9bcfeaae92

We should limit this to ~2 hours

**Comment by pburkholder** [comment]
I'm going to close this issue as there's no valid indication we're running TLS 1.1
