### ISSUE TITLE
Shell for c2c encryption upstream issue 

### ISSUE THREAD

**Issue by bengerman13** [cloud-gov/product#1610]
Placeholder to track work on cloudfoundry/diego-release#587

**Comment by pburkholder** [comment]
> 👋 Hello @pburkholder,
>🎉 I get to deliver good news! Yes! We are working on this. I assigned @mariash to this issue to give you more information.

Good news from upstream!

**Comment by ccostino** [comment]
We'll create a separate issue to track documentation and any other follow up that needs to be done.
