### ISSUE TITLE
As a Pages customer, I need a customer compliance guide (enhanced CRM)

### ISSUE THREAD

**Issue by pburkholder** [cloud-gov/product#1621]
In order to adopt Pages or migrate from Federalist, customers will want a guide on which steps to take to secure their site and meet compliance requirements.

See for reference [Lindsay's first pass at this](https://docs.google.com/spreadsheets/d/1LkFyV1EDCpXr4EJtKPbKn2PP41kUUOWb/edit#gid=440485330) and also the old cloud.gov CRM which was organized around customer actions (link needed)

--- 

## Security considerations
This should be open so customers and interested parties can see how this work is accomplished.

**Comment by davemcorwin** [comment]
Guide https://docs.google.com/document/d/1hBqsYT2fGjAkcV_UjyBoHBRQJyou15DFHm7KHquWwfs/edit

**Comment by apburnes** [comment]
Closed by https://github.com/cloud-gov/cg-site/pull/2207
