### ISSUE TITLE
Pages SSP L-ATO

### ISSUE THREAD

**Issue by amirbey** [cloud-gov/product#1622]
In order to extend the ATO for Federalist sites, GSA IT is requiring the Federalist Operators to write an SSP L-ATO based on the implementation of Pages.

#### Implementation outline:
- [ ] update the LATO template with Pages implementation details
- [ ] submit LATO to ISSO/M for review

**Comment by karareinsel** [comment]
@amirbey @davemcorwin are there any critical dates that the team should be aware of? Want to be sure Pages has all the necessary support to meet important deadlines for the L-ATO.

**Comment by amirbey** [comment]
thanks @karareinsel  - so far there are not critical dates or any needs from the team to complete this work. Right now, we're waiting to sync with the Federalist ISSO/M on the Pages system infrastructure before updating the L-ATO

**Comment by karareinsel** [comment]
Should I move it out of the backlog or would you prefer to keep it on the board just for broader team visibility?

**Comment by amirbey** [comment]
@karareinsel  - you can move it out of the backlog 👍🏿

**Comment by karareinsel** [comment]
I moved it back to triage.

**Comment by davemcorwin** [comment]
I don't think so.

**Comment by pburkholder** [comment]
Do we still need to act on this issue, or can we close it?

**Comment by pburkholder** [comment]
Closing this as we can now lean on the Pages P-ATO, etc.
