### ISSUE TITLE
Adopt and maintain Stratos

### ISSUE THREAD

**Issue by pburkholder** [cloud-gov/product#1644]
Open-source: Free as in Kittens.

We've adopted it so now we're responsible for care and feeding.

In order to keep an well-maintained dashboard, we want to take over the community maintenance of the Stratos project.

## Acceptance Criteria
TBD

--- 

## Security considerations
This needs to be complete before closing.

**Comment by mogul** [comment]
Recent news... Looks like maybe [Stark and Wayne are interested in taking on Stratos](https://github.com/cloudfoundry/community/issues/226#issuecomment-1067975837)!

**Comment by nathanweeks** [comment]
The [cloudfoundry/stratos](https://github.com/cloudfoundry/stratos) repository recently went "public archive" as nobody has volunteered to maintain it.

**Comment by pburkholder** [comment]
Thanks @nathanweeks.

I'm moving this conversation to https://github.com/cloud-gov/private/issues/617 and I'm marking this as closed to keep our boards more sane, but future outside commenters please feel free to use this issue for updates.
