### ISSUE TITLE
TCP Routes (epic) 

### ISSUE THREAD

**Issue by bengerman13** [cloud-gov/product#1650]
In order to support non-HTTPS protocols, we want to support TCP routes for our users

## Security considerations
This will require an SCR, likely with 3PAO assessment. We should also do some threat modeling. Probably worth noting that there are less protections available/built-in here from AWS.

## Implementation sketch
https://docs.google.com/document/d/1z9v0Ub9h6KO25FkALpU9V_YMl2GG9lDMcLiiSUrMZP4/edit

We think the way to do this is probably 1 NLB per org, provided via a broker, with a setup cost and a monthly cost TBD
This would probably fit very well with a brokerpak, since all these things are terraformable, although getting the IP address information out might be clumsy?

**Comment by mogul** [comment]
@bengerman13 can you confirm we've got this implementation implemented but feature flagged? And the further work is to get the SCR moving?

**Comment by mogul** [comment]
Closing in favor of #1722
