### ISSUE TITLE
Container verification for Concourse

### ISSUE THREAD

**Issue by LindsayYoung** [cloud-gov/product#1658]
Validate container we pull is the same one we push

See previous planning:
https://github.com/cloud-gov/product/issues/1543

@davemcorwin has details on how we do this in Concourse

**Comment by bengerman13** [comment]
step 1: ADR

We could probably do this for concourse by scanning images, then putting the validated container checksums into credhub, and pulling by checksum rather than tag

**Comment by bengerman13** [comment]
ADR open - waiting for review/comments

**Comment by pburkholder** [comment]
Closing as duplicate of #1723 (which is more fully fleshed out)
