### ISSUE TITLE
Expand RDS backup retention period

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/product#1664]
# What we're after
Discuss expanding RDS's automated DB backups to 3 or 4 weeks from the current 14 days.

## Hypothesized benefit(s)/why:
* Add expanded service to fit customer needs.

## Potential metrics
* Provide more options for customers.
* May add significant cost.

---

### Security considerations
Expands customer's timeline to recover a database

### Notes for implementers

- Discuss the possibilities and implementation details.

**Comment by ccostino** [comment]
We have a detailed issue in the broker backlog for the actual implementation: https://github.com/cloud-gov/aws-broker/issues/186

**Comment by ccostino** [comment]
This is done! https://github.com/cloud-gov/aws-broker/pull/224 🎉
