### ISSUE TITLE
define pass/fail criteria for scanned container images

### ISSUE THREAD

**Issue by bengerman13** [cloud-gov/product#1687]
In order to keep containers secure and compliant, we need to track when new vulnerabilities are detected. We can then fail scans when vulnerabilities exceed the allotted fix time.

We think there are probably two ways to go about this:
- check when the vulnerability was first released. If this is readily available via the metadata from Grype, or from some other machine-readable CVE database, it's the easy route because we can stay stateless.
- persist a map somewhere of contanerVulnerability -> discoveryDate. This is harder, because we have to manage state, but still very feasible with JSON + S3, so it's a good option if we can't easily find release dates on CVEs

**Comment by mogul** [comment]
Van and David are pushing this forward... Still to decide on the pass/fail conditions.

**Comment by mogul** [comment]
@soutenniza and @dandersonsw can I ask you to pause work on this to help @pburkholder to resolve https://github.com/cloud-gov/cg-harden-boshrelease/issues/54? It's pretty urgent to get resolved.

**Comment by Chiakao** [comment]
@dandersonsw @soutenniza I'm drafting a quick pager for Ashley on our planned actions to address container scanning since we got a Detailed Finding Request from FEDRAMP. Is there a proposed date on addressing this?

**Comment by Chiakao** [comment]
Pass/fail criteria has been defined. @dandersonsw @soutenniza Can I close this?
