### ISSUE TITLE
As a developer for cloud-gov-compliance, I need ASG-restricted spaces.

### ISSUE THREAD

**Issue by pburkholder** [cloud-gov/product#1693]
In order to test and develop tooling which should _not_ have open egress, please create egress-restricted spaces:

- no-egress-dev
- limited-egress-dev
- limited-egress-prod
- no-egress-prod

--- 

## Security considerations
None for this change.

**Comment by apburnes** [comment]
Spaces `no-egress-dev` and `no-egress-prod` can be accessed by DNS. The apps within the space cannot reach out to the open internet or our services like RDS, Redis, and ES.

Spaces `limited-egress-dev` and `limited-egress-prod` can be accessed by DNS. The apps within the space can access our services like RDS, Redis, and ES. The apps cannot reach out to the open internet.

**Comment by pburkholder** [comment]
👨‍🍳 💋
