### ISSUE TITLE
Wrap up Pages SCR:

### ISSUE THREAD

**Issue by pburkholder** [cloud-gov/product#1709]
- Draw new diagram or update existing one.
- Add whether what is stored in New Relic customizable. And note that we cannot store hostname
- Update SSP to note that customer is responsible for FIPS 199 categorization of content external to ABD
- Create a POAM tracker for late inclusion in cloud.gov tracker.
- How are we going to production and are any controls impacted?

**Comment by pburkholder** [comment]
Diagrams comment is:
> Legend is not detailed > data flow arrows should show input, output, and two-way flows as applicable.  

I think we can POA&M that.

**Comment by pburkholder** [comment]
Update SSP to note that customer is responsible for FIPS 199 categorization of content external to ABD

* This will be an update to the SA-9 Control.

**Comment by pburkholder** [comment]
Current status on these:
- For diagrams, this has been satisfied
- For tenant separation and risks corrected during testing - we need to work that out with our 3pao
- I am opening POA&Ms in our general tracker and will submit those
- Need to submit v 1.2 of the addendum which addresses some questions.
- Still need to dig into New Relic
- Still need to map transition to production vs. their questions:
> "4/1/2022 Are any security controls different in production than in staging and if so, those would require validation by the 3PAO (3PAO would have to update SAR so it reflects risk status of Pages in production). 
>3/17/2022 It was said Pages is in staging and was assessed in staging. I'm having trouble with MS word right now to look up in the SSP…Is this the process that was referred to https://docs.cloudfoundry.org/concepts/how-applications-are-staged.html"

**Comment by pburkholder** [comment]
Current status on these:
- For diagrams, this has been satisfied
- For tenant separation and risks corrected during testing - we need to work that out with our 3pao
- I am opening POA&Ms in our general tracker and will submit those
- Need to submit v 1.2 of the addendum which addresses some questions.
- Still need to dig into New Relic
- Still need to map transition to production vs. their questions:
> "4/1/2022 Are any security controls different in production than in staging and if so, those would require validation by the 3PAO (3PAO would have to update SAR so it reflects risk status of Pages in production). 
>3/17/2022 It was said Pages is in staging and was assessed in staging. I'm having trouble with MS word right now to look up in the SSP…Is this the process that was referred to https://docs.cloudfoundry.org/concepts/how-applications-are-staged.html"

See migration documatne at https://docs.google.com/document/d/1JpBsMETzOmYEBDctGflRJB1inAYO3uulmbf1NQBW8Ak/edit

**Comment by pburkholder** [comment]
We're at working extending the PoP until May 31, hope they can work as soon as Thursday. I've notified CFF and I hope they'll have resources available (soon!).

**Comment by mogul** [comment]
Closing this one; we'll open new issues as new blockers appear.
