### ISSUE TITLE
Require signed commits for branches and pipelines

### ISSUE THREAD

**Issue by mogul** [cloud-gov/product#1724]
# What we're after

Fix a POA&M finding: "Code stored in Git repositories are not protected from tampering"

## Hypothesized benefit(s)/why:

* Prevent injection of code by valid user accounts (eg if credentials are misused/stolen)

## Potential metrics

* % of repositories that require signed commits

---
### Further context for those unfamiliar with what we're doing

GitHub has [a feature to prevent merging of unsigned code](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches#require-signed-commits). Turning this on in our repositories prevents adding code to a repository without high confidence that the code originated from a member of our team.

### Security considerations

This change requires team members to configure commit-signing in their various client-side environments and tools. GitHub will make a  merge-commit with an "untrusted" signature of its own when merges or rebases happen, but we are choosing to be less concerned about the potential of injection from the GitHub server-side so long as we can trust our process for merging only previously-signed commits in the first place.

### Notes for implementers

- [Implementation Sketch (needs updating)](https://docs.google.com/document/d/1-QKL1-Tc7C1RhmQ8_wKgIC-tGgqXfdHV9Tix2RMhZSU/edit)

### Related issues

- [x] #1761
- [x] #1762
- [x] #1763
- [x] #1764
- [x] #1776
- [x] #1765

**Comment by pburkholder** [comment]
POA&M CG290-CM-5 now references this issue with an ETS of 2022-06-30

**Comment by markdboyd** [comment]
Guidance on how to require signed commits for Github repos:

https://stackoverflow.com/a/62933851

**Comment by markdboyd** [comment]
This has been closed out with the JAB
