### ISSUE TITLE
Add Chiaka compliance access to our AWS accounts and cloud.gov accounts

### ISSUE THREAD

**Issue by pburkholder** [cloud-gov/product#1734]
In order to grant Chiaka AWS compliance role privileges, I need an operator to take care of these steps in her onboarding:

Create [AWS Accounts](https://cloud.gov/docs/ops/aws-onboarding/) via the AWS web console (not Terraform) and provide one-time credentials - these will be setup with read-only/auditor permissions, and once the 3 mandatory cloud.gov trainings are complete they will be added to the [audit input file](https://github.com/cloud-gov/cg-compliance/blob/master/audit/inputs.yml):

- [x]  AWS Commercial accounts
- [x]  AWS GovCloud accounts

* [x] [Make them an auditor](https://cloud.gov/docs/ops/managing-users/#managing-admins) of the platform.

--- 
## Security considerations
This is a standard step for onboarding for compliance role.

**Comment by rbogle** [comment]
done!
