### ISSUE TITLE
Update and share SSP w/ KEVs and Shea Bennett signature page.

### ISSUE THREAD

**Issue by Chiakao** [cloud-gov/product#1736]
SSP needs to be downloaded from Google Drive, properly updated with MS Word, converted to PDF and signed.
Prelim step - Chiaka to obtain access to MS Office - awaiting approval.

**Comment by pburkholder** [comment]
@Chiakao  To close CG257-CM-4 we also need to update SI-2 and CM-4 to reflect the additional gating work we've added (see issues #cloud-gov/private/426, #cloud-gov/private/427 and #cloud-gov/private/428. Can we do that this week?

**Comment by Chiakao** [comment]
SSP uploaded to 18F ConMon Page
