### ISSUE TITLE
Set up Ephraim's lightweight development environment on Windows

### ISSUE THREAD

**Issue by hursey013** [cloud-gov/product#1743]
In order to allow Ephraim to contribute code changes (e.g., documentation site updates), we need to take care of the following for a Windows environment:

### Additional compliance setup/review

* [ ] Install `caulking` git leak prevention by following the [README](https://github.com/cloud-gov/caulking/blob/master/README.md)
* [ ] Verify `caulking` by running `make audit` and pasting a screenshot as a comment on this GitHub issue
* [ ] Set GPG signing set up for GitHub (instructions [here](https://docs.google.com/document/d/11UDxvfkhncyLEs-NUCniw2u54j4uQBqsR2SBiLYPUZc/edit))

### Install a development environment for cloud.gov

- [ ] Install Ruby

## Security considerations
Minimal - this is a subset of the onboarding from the main onboarding issue.

## Implementation sketch
Work with Bret on getting started with WSL (windows subsystem linux).

**Comment by mogul** [comment]
Macbook now available, closing this issue in favor of the original onboarding issue.
