### ISSUE TITLE
Ensure IP restrictions apply to all endpoints

### ISSUE THREAD

**Issue by mogul** [cloud-gov/product#1746]
In order to ensure that the IP restriction feature applies no matter how an affected user interacts with cloud.gov, we will add tests that cover Stratos.

## Acceptance Criteria
* [x] GIVEN I have access to test output for the feature \
  WHEN I check the output \
  THEN I see a test specifically referencing Stratos \
  AND the test is passing.

--- 

## Security considerations
This work improves our security posture by eliminating the risk that we will unintentionally grant restricted users broader access through unrelated changes.

## Implementation sketch

[links to background notes, sketches, and/or relevant documentation
* [ ] [first thing to do]
* [ ] [another thing to do]

**Comment by bengerman13** [comment]
fixed in cloud-gov/cg-deploy-cf#660
fixed in cloud-gov/cg-deploy-cf#661
fixed in cloud-gov/cg-deploy-cf#662
fixed in cloud-gov/cg-deploy-cf#663
fixed in cloud-gov/cg-deploy-cf#665
