### ISSUE TITLE
[research: 2 days] Figure out how cloud.gov has access to use the GSuite SMTP Relay (check in on 7/3)

### ISSUE THREAD

**Issue by mogul** [cloud-gov/product#1749]
In order to understand how we can provision outgoing mail in new environments, we want to spend up to 2 days researching the existing SMTP Relay configuration that's set up for GSA's GSuite deployment, and how to extend it.

## Acceptance Criteria
* [ ] GIVEN we've spend two days looking into this \
  WHEN I look at the backlog for the account detangling epic \
  THEN I see issues covering the work we've identified as needing to happen.

## Security considerations
None, this is just research into how things work now.

## Implementation sketch

The main question: How does cloud.gov smtp work? When we did ctusa, we used gsa relays, but cloud.gov relays work differently, apparently. Ben thinks there's a clue in DNS: [Record A](https://github.com/cloud-gov/cg-provision/blob/main/terraform/stacks/dns/validators.tf#L36-L45), [Record B](https://github.com/cloud-gov/cg-provision/blob/main/terraform/stacks/dns/validators.tf#L123-L129)

See also https://support.google.com/a/answer/2956491?hl=en for an overview of how the G Suite SMTP Relay works

**Comment by rbogle** [comment]
- SMTP relay for google gmail is configured for TLS connections only
- The configuration seems to be restricted to a range of IPs and I have tested across several ip addresses ( via different jumpboxes). 
- Relay appears to work regardless of the HELO hostname provided. 
- The envelope of an email must include the mail_from or from “[no-reply@gsa.gov](mailto:no-reply@gsa.gov)”. 

I have a servicenow ticket created with GSA IT to get information on how the relay is currently configured in the Google workspace for our domain. [Ticket](https://gsa.servicenowservices.com/nav_to.do?uri=sc_request.do%3Fsys_id=a36cd93e1b085d5023d920efe54bcb13%26sysparm_stack=sc_request_list.do%3Fsysparm_query=active=true)

Tested ip blocks: 
10.80.0.x – works
10.99.1.x  – works
10.8.1.x – Failed.

[More Research Notes](https://docs.google.com/document/d/1z5WuNuNrNdWJL1r6XjmOq7PQBoZDJd9zfMdgWBS8-g4/edit?usp=sharing)

**Comment by mogul** [comment]
Still waiting on the GSA IT team to reply to the ServiceNow ticket.

**Comment by mogul** [comment]
We pinged in https://gsa-tts.slack.com/archives/C01J79YG1UL/p1657750110592769 and a couple people responded tagging each other, but still no movement.

**Comment by rbogle** [comment]
Finished confirming the configuration lives with GSA gsa.gov google workspace. 
The tooling and production NAT gateway addresses the the ips approved for relay...

52.222.123.172 (Cloud.gov Egress IP 2) [ [Nat Service AZ1 Production](https://console.amazonaws-us-gov.com/vpc/home?region=us-gov-west-1#NatGatewayDetails:natGatewayId=nat-0b4d660e1d46b4e7a) ]
52.222.122.97 (Cloud.gov Egress IP 1) [ [Nat Service AZ2 Production](https://console.amazonaws-us-gov.com/vpc/home?region=us-gov-west-1#NatGatewayDetails:natGatewayId=nat-097f238d470462c23) ]
52.222.8.223 (Cloud.gov 4) [ [Nat Service AZ1 Tooling](https://console.amazonaws-us-gov.com/vpc/home?region=us-gov-west-1#NatGatewayDetails:natGatewayId=nat-0a0bd8c7b569eba58) ]
52.61.29.77 (Cloud.gov 3) [ [Nat Service AZ2 Tooling](https://console.amazonaws-us-gov.com/vpc/home?region=us-gov-west-1#NatGatewayDetails:natGatewayId=nat-010236611b0e08856) ]
