### ISSUE TITLE
[bug] Previous Ruby buildpack version is auto-detected ahead of the most recent

### ISSUE THREAD

**Issue by mogul** [cloud-gov/product#1750]
If you allow buildpack auto-detection to happen for a Ruby app, the second most recent Ruby buildpack will be selected instead of the most recent one.

## How to reproduce

GIVEN a directory with a Ruby app in it \
AND no buildpack specified in a `manifest.yml` file \
WHEN I run `cf push APPNAME`...

## Expected behavior

...THEN the app should be staged with the most recent platform-provided Ruby buildpack

## Actual behavior

...BUT the app is staged with a Ruby buildpack one version older.

## Observations

When no buildpack is specified, [the Cloud Foundry auto-detect process runs through the list of available buildpacks](https://docs.cloudfoundry.org/buildpacks/understand-buildpacks.html#buildpack-detection) (in the order indicated by `cf buildpacks`) until it finds one that reports that it can handle the app. 

When you run `cf buildpacks` on cloud.gov then you see this list:

```
$ cf buildpacks
Getting buildpacks as bret.mogilefsky@gsa.gov...

position   name                    stack        enabled   locked   filename
1          staticfile_buildpack    cflinuxfs3   true      false    staticfile_buildpack-cflinuxfs3-v1.5.29.zip
2          java_buildpack          cflinuxfs3   true      false    java-buildpack-cflinuxfs3-v4.48.3.zip
3          ruby-buildpack          cflinuxfs3   true      false    ruby-buildpack-cflinuxfs3-v1.8.52.zip
4          ruby_buildpack          cflinuxfs3   true      false    ruby_buildpack-cflinuxfs3-v1.8.53.zip
5          dotnet_core_buildpack   cflinuxfs3   true      false    dotnet-core_buildpack-cflinuxfs3-v2.3.41.zip
6          nodejs_buildpack        cflinuxfs3   true      false    nodejs_buildpack-cflinuxfs3-v1.7.69.zip
7          go_buildpack            cflinuxfs3   true      false    go_buildpack-cflinuxfs3-v1.9.42.zip
8          python_buildpack        cflinuxfs3   true      false    python_buildpack-cflinuxfs3-v1.7.53.zip
9          php_buildpack           cflinuxfs3   true      false    php_buildpack-cflinuxfs3-v4.4.59.zip
10         binary_buildpack        cflinuxfs3   true      false    binary_buildpack-cflinuxfs3-v1.0.43.zip
11         nginx_buildpack         cflinuxfs3   true      false    nginx_buildpack-cflinuxfs3-v1.1.37.zip
12         r_buildpack             cflinuxfs3   true      false    r_buildpack-cflinuxfs3-v1.1.28.zip
```

Note there are _two_ entries for Ruby, one called `ruby-buildpack` and the other called `ruby_buildpack`. 
- The first one, `ruby-builpack`, is `v1.8.52`
- The second one, `ruby_buildpack` is `v1.8.53`

The auto-detect process will pick `v1.8.52`.

## Sketch

@bengerman13 said he thought there were two entries for historical reasons, eg we renamed from `ruby-buildpack` to `ruby_buildpack` for consistent naming but left the old name in place to avoid inconveniencing customers who were using the old name. It's fine to have two entries, but they should be using the same version of the buildpack.

We should probably investigate pipelines that might update versions to make sure that we are updating both entries at the same time.

**Comment by bengerman13** [comment]
oh - that's not what I meant. I just meant that I _assume_ the name changed in the past and we never pulled the old one out. In other words, I think having both is a relic of some change, not a deliberate state

**Comment by mogul** [comment]
We should probably audit to figure out how often the two options are used among customer apps, and if there are few enough users of one over the other then we could contact them to see if we can drop that one. (But regardless, the two options should refer to the same version of the buildpack.)

**Comment by dandersonsw** [comment]
After looking into this I found that no apps are currently using the old 'ruby-buildpack'. I believe we can safely remove this now, or just leave it until we deprecate cflinuxfs3 where it will be removed anyways.

**Comment by dandersonsw** [comment]
Closing this since it will be resolved when we complete the switch to cflinuxfs4
