### ISSUE TITLE
Log-based alerting for platform and users

### ISSUE THREAD

**Issue by mogul** [cloud-gov/product#1766]
# What we're after

Without further acquisition, platform operators and customers can easily generate alerts based on logs and metrics generated by the platform.

## Hypothesized benefit(s)/why:
 
* Increase the compliance benefit of using cloud.gov for customers
* Reduce redundant procurement of monitoring/alerting systems across federal programs/agencies
* Expand the set of agencies that get an ATO to use cloud.gov

## Potential metrics

* Monitoring and alerting controls can be completely inherited/implemented by customers without using another CSP (eg New Relic or their own SOC)

---
### Further context for those unfamiliar with what we're doing

Our current logging system is based on ELK, which provides a nice experience for viewing and querying logs, but no functions for alerting based on those logs. Therefore cloud.gov customers are having to purchase other services like New Relic to do log-based alerting. We would like to improve our log offering to provide alerting services and eliminate the need for customers to purchase other services.

### Security considerations

[note any potential changes to security boundaries, practices, documentation, risk]

### Notes for implementers

[We are currently planning to move from an ELK based logging stack to Opensearch](https://github.com/cloud-gov/product/issues/1725) and Opensearch seems to include functionality for alerting.

### Related issues/sub-projects

- [ ] Research and confirm viability of using OpenSearch alerting plugin: https://opensearch.org/docs/latest/monitoring-plugins/alerting/index/
- [ ] If research confirms viability of Opensearch alerting, implement it

**Comment by markdboyd** [comment]
Superseded by https://github.com/cloud-gov/private/issues/660
