### ISSUE TITLE
restricted_egress ASG can access brokered S3 buckets (8/22/2022)

### ISSUE THREAD

**Issue by mogul** [cloud-gov/product#1775]
In order to remove the effort needed for customers to restrict egress access, the platform team wants to enable and configure AWS PrivateLink for AWS S3.

## Acceptance Criteria

* [ ] WHEN I look at [the controlling egress traffic page on the website](https://cloud.gov/docs/management/space-egress/) \
  THEN I see two columns for S3, "AWS S3 (user-provided)" and "AWS S3 (brokered)" \
  AND the "AWS S3 (user-provided)" column has row entries X, X, and ✔ \
  AND the "AWS S3 (brokered)" column has row entries X, ✔, and X.

Prior to this work, the table looks like this:
![Image](https://user-images.githubusercontent.com/47762/172268535-306504f2-e7d2-4270-bf8c-4862db477686.png)

GIVEN a CF space with only the `restricted-egress` ASG applied \
  AND a brokered S3 bucket service instance \
  AND a user-provided service instance with credentials for an S3 bucket outside our accounts \
  AND a test app in the space 
  AND the test app is bound to the brokered S3 bucket service instance \
  AND the test app is bound to the user-provided service instance \
  AND no egress-proxy is in place \ 
  AND I `cf ssh` into the test app \ 
  AND I install the AWS CLI... \
* [ ] WHEN I run `aws s3 ls` with the bucket credentials provided in the brokered service instance \
  THEN the command completes successfully.
* [ ] WHEN I run `aws s3 ls` with the bucket credentials provided in the user-provided service instance \
  THEN the command does not complete successfully.

--- 

## Context

Customers cannot implement egress-control for S3-using apps without also deploying and configuring a separate proxy app in a `public_egress` space that can access the bucket. With this change, the proxy in another space will no longer be required, dramatically reducing the barrier for customers to implement egress-control for the most common cases (apps that only need to reach their bound services).

## Security considerations

This work enables the PrivateLink feature of AWS VPC. Enabling this feature ensures that traffic from hosted apps to brokered S3 buckets traverses an internal AWS network, rather than the internet. This removes opportunities for attackers to get between the app and the bucket (as well as saving bandwidth charges). We have determined that no system diagrams or controls will be impacted by this work, and it involves enabling a feature of an AWS service already in use (AWS VPC). Therefore, we do not think this change falls within the threshold of a Significant Change Request (SCR).

## Implementation sketch

- [ ] Read up on [AWS PrivateLink for AWS S3](https://docs.aws.amazon.com/AmazonS3/latest/userguide/privatelink-interface-endpoints.html).
* [ ] Enable AWS PrivateLink for AWS S3 in our environment
* [ ] Put a VPC endpoint policy in place that [limits access to S3 buckets in our AWS accounts](https://docs.aws.amazon.com/AmazonS3/latest/userguide/privatelink-interface-endpoints.html#privatelink-example-access-bucket-in-specific-account-only)
* [ ] Modify [the AWS S3 broker](https://github.com/cloudfoundry-community/s3-broker) to provide endpoint-specific DNS names in bindings ([boto3 docs](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/s3-example-privatelink.html) may be useful for tests)
* [ ] Update the table in the site space-egress docs

**Comment by mogul** [comment]
It looks like the costs savings here could be significant...!
https://twitter.com/t3rabytes/status/1534885118048878592?s=21&t=LxsXbfVVuK4FlM91PfBO8A

**Comment by rbogle** [comment]
PRs completed in cg-provision and cg-deploy-cf. 
Deployed changes to cg-provision.
Deploying cf changes for ASG will complete technical work. 
Then update to docs and announce.

**Comment by rbogle** [comment]
ECR should be unblocked with the addition of the following statement to the s3 gateway policy:
{
  "Statement": [
    {
      "Sid": "Access-to-specific-bucket-only",
      "Principal": "*",
      "Action": [
        "s3:GetObject"
      ],
      "Effect": "Allow",
      "Resource": ["arn:aws:s3:::prod-us-gov-west-1-starport-layer-bucket/*"]
    }
  ]
}
