### ISSUE TITLE
TCP Routes: Start fulfilling ARL and provide feedback

### ISSUE THREAD

**Issue by pburkholder** [cloud-gov/product#2069]
# What we're after
3PAO has provided their initial ARL (artifact request list): https://app.smartsheetgov.com/sheets/qG67XH3XMGPMxg9fQg8w5r6Qp9WqgjvG5Jxfjwr1?view=grid

> I wanted to get at least an initial start at a request list posted to[ Smartsheet](https://app.smartsheetgov.com/sheets/qG67XH3XMGPMxg9fQg8w5r6Qp9WqgjvG5Jxfjwr1?view=grid) so you can start to get familiar with the requests. We are still learning the system to understand what makes sense to ask for, so if some of these requests don’t make sense, then just wait until I get back and we can discuss.
> Of course, you can upload artifacts to individual rows, add comments, etc. Even if the request does not say “demo” we can still plan to demo the item if easier.

We should respond with how we'll satisfy the requests, or provide requested feedback. If that artifacts are easy, go ahead and get them.

We should try to feedback to them by July 7.

**Comment by Chiakao** [comment]
We started gathering artifacts but have paused this effort indefinitely because TCP routes has been deprioritized.
