### ISSUE TITLE
Port (cloud.gov) Zendesk content to new instance by July 30

### ISSUE THREAD

**Issue by mogul** [cloud-gov/product#2073]
In order to retain our support activity history, we want historical Platform activity migrated from cloud-gov-old.zendesk.com to cloud-gov.zendesk.com.

## Acceptance Criteria
* [x] GIVEN I am logged into cloud-gov.zendesk.com as an Agent \
  WHEN I look at issues \
  THEN I see all expected Platform support activity from before June 2022 is present.

--- 

## Security considerations
Only content will be migrating. Settings for the new instance were part of a previous migration.

## Implementation sketch

* [ ] Can we pay Zendesk to do this for us?
* [x] If not, can we pay a contractor to do this for us?
* [ ] If not, can we use a community-provided tool?
* [ ] If not, can we write our own migration using the Zendesk API?
* [x] Delete the cloud-gov-old.zendesk.com account.

**Comment by ArsHaider** [comment]
As of 7/28/2022: Brain Cell (Zendesk migration people) are getting started on Zendesk migration today! Additionally, Zendesk has extended access to our old account for 30 days to ensure we can get the migration done.

**Comment by ArsHaider** [comment]
As of 8/2/2022: Had a meeting with the team from BrainSell, are requesting access to admin login information for both instances of old cloud gov Zendesk instance and federalist Zendesk instance. Scheduled to have next meeting to start the migration process at 11 am Thursday 8/4/2022.

**Comment by wz-gsa** [comment]
@ArsHaider can this be closed?

**Comment by ArsHaider** [comment]
> @ArsHaider can this be closed?

William, it has already been completed successfully. I will close this ticket, thank you!
