### ISSUE TITLE
Validate data.gov 2xl RDS plans for general availability.

### ISSUE THREAD

**Issue by mogul** [cloud-gov/product#2078]
In order to provide the data.gov team with a path forward on cloud.gov, we want to validate that a higher-performance and lower-cost DB tier will meet their load-testing needs.

## Acceptance Criteria
* [ ] GIVEN we create an ARM-based plan \
  AND we expose that plan as well as the data.gov-proposed plan to the `gsa-datagov` org \ 
  WHEN the data.gov team does load-testing and reports their results \
  THEN we know which plan to promote to general availability

--- 

## Security considerations
All DB plans are implemented as configuration parameters in the catalog YAML file for the aws-broker. Making changes there is one of the safest things that we do, in that no code changes.

## Implementation sketch

The data.gov team submitted [a PR for a plan that would match the DB performance of their existing environment](https://github.com/cloud-gov/aws-broker/pull/247).
* [x] Add an ARM-based plan
* [x] Expose those two new plans to just the `gsa-datagov` organization
* [x ] Ask the data.gov team to do some benchmarking
* [ ] If the ARM plan suffices, promote that to general usage
* [ ] If not, then talk about the cost: Whether it needs to be passed to customers, whether the plan should be made available generally, etc.

**Comment by rbogle** [comment]
associated with PR from datal.gov team: https://github.com/cloud-gov/aws-broker/pull/247

**Comment by rbogle** [comment]
associated with PR from me: https://github.com/cloud-gov/aws-broker/pull/248

**Comment by dandersonsw** [comment]
Rian will check back with data.gov team

**Comment by jameshochadel** [comment]
Rian is working on a script to pull metrics for a specific instance. AWS Console doesn't provide much for this. Looking to get data.gov team some numbers.

**Comment by rbogle** [comment]
Moving this back to backlog for future work. 

at this point we need to determine if the plans given to data.gov org should be made generally available:

https://github.com/cloud-gov/aws-broker/pull/247#issuecomment-1184644744

**Comment by wz-gsa** [comment]
@soutenniza no longer needed
