### ISSUE TITLE
Update federalist-garden-build to use Dockerhub

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/product#2090]
In order to complete the SCRE, we want to start pushing/pulling docker images from cloud.gov's Dockerhub account and stop pushing/pulling images from AWS ECR.

## Background
Pre SCR, Federalist used its own AWS account and ECR services to push and pull images. With the Pages SCR, we will need to update to Dockerhub
- [federalist-garden-build repo](https://github.com/18f/federalist-garden-build)

## Acceptance Criteria
* [x] Create credentials for CI to use Dockerhub
* [x] Update pipeline to build and push images to dockerhub
* [x] Update site build task to pull image from dockerhub
* [ ] Delete AWS ECR credentials and remove service from AWS

--- 

## Security considerations
Needed to complete SCR

**Comment by drewbo** [comment]
Documenting that this was previously mostly completed by @davemcorwin:
- [Initial implementation](https://github.com/18F/federalist-garden-build/commit/7e44aafb3980b6290fc608bb9d6957de2979f86b)
- [Partial reversal for Federalist only](https://github.com/18F/federalist-garden-build/commit/900c6431f9c7468181a60ff7043ffa4708cf2cef)
- [Relevant portion of current code to push image to docker](https://github.com/18F/federalist-garden-build/blob/94a1322ee3ca50b38a015436e338f4870d55e61d/ci/pipeline.yml#L276-L282)
  - The docker push/pull makes use of the [`in`](https://github.com/concourse/docker-image-resource#in-fetch-the-image-from-the-registry) and [`out`](https://github.com/concourse/docker-image-resource#out-push-an-image-or-build-and-push-a-dockerfile) properties of `concourse/docker-image-resource` 
  - The image reference is also stored within concourse [on deploy](https://github.com/18F/federalist-garden-build/blob/staging/ci/tasks/deploy.sh), can be confirmed with `cf app pages-build-container-staging`
- The builder specifically [queries for the concourse build container](https://github.com/18F/federalist-builder/blob/3e59329b1dbd7d8840e9fd9b05c883210b3722e0/src/cloud-foundry-api-client.js#L14-L23) when starting tasks
- [Details on remaining AWS ECR services](https://github.com/18F/federalist-garden-build/pull/276)

**Comment by apburnes** [comment]
☝️ This is good.

A bit of clarification on the following:
> The builder specifically [queries for the concourse build container](https://github.com/18F/federalist-builder/blob/3e59329b1dbd7d8840e9fd9b05c883210b3722e0/src/cloud-foundry-api-client.js#L14-L23) when starting tasks

This refers to the running CF app `build-container` that builds sites via [CF tasks](https://docs.cloudfoundry.org/devguide/using-tasks.html) on the app. The container image is already pulled from Dockerhub or ECR and deployed as an app at this point.

**Comment by drewbo** [comment]
Completed as detailed above will open a new ticket to remove AWS services
