### ISSUE TITLE
Setup Federalist/Pages AWS account for S3 to use SSO

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/product#2099]
In order to keep parity with our AWS accounts, we want to update Federalist's AWS account for S3 Buckets to use SSO.

## Acceptance Criteria
- [x] Add SSO to account
- [ ] Remove credentials created pre-SSO
- [x] Add Federalist/Pages operators to SSO
- [x] Add Platform operators to SSO

## Security Considerations
Simplifies and standardizes authentication across cloud.gov AWS accounts

**Comment by apburnes** [comment]
@rbogle since you sent us the credentials, Can we close this out?

**Comment by rbogle** [comment]
Closing! Will remove the old creds tomorrow
