### ISSUE TITLE
Add site build storage limits to the Pages docs

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/product#2106]
In order to improve our documentation and better inform our Pages customers and potential customers, we outline the current site build storage limits and possible alternatives for tackling the current platform limitations.

## Acceptance Criteria
- [x] Create documentation about the limits and how customers can use a multi site strategy to help cover the platforms limitations.
- [x] Add to federalist.18f.gov and cloud.gov/pages

## Security Considerations
- None

## Implementation details
- [x] Outline the default build container size
- [x] Outline the large build container size and how you can request it as a customer
- [x] Outline creating additional sites to serve media, reports, docs, etc
- [x] Update federalist.18f.gov repo
- [x] Update cloud.gov cg-site repo

**Comment by drewbo** [comment]
- Relevant PR: https://github.com/cloud-gov/federalist.18f.gov/pull/575
- Available on Federalist site: https://federalist.18f.gov/documentation/large-file-handling/

**Comment by drewbo** [comment]
- Relevant PR for cg-site: https://github.com/cloud-gov/cg-site/pull/2174
- Merged to `pages` branch and pending merge to live site

**Comment by drewbo** [comment]
Live on cloud.gov via https://github.com/cloud-gov/cg-site/pull/2179
