### ISSUE TITLE
Deprecate and remove Federalist shared bucket

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/product#2111]
As a Pages operator, I want to remove the shared bucket relic which provided file storage for all Federalist sites years back. The shared bucket affects the logic in the [proxy](https://github.com/18f/federalist-proxy) and adds additional configuration to deployments.

## Acceptance Criteria
- [x] Verify the shared bucket no longer contains any site files
- [x] Update the [proxy](https://github.com/18f/federalist-proxy) to no longer incorporate the shared bucket in its deployment or logic
- [x] Unbind the service from the federalist and pages apps
- [x] The S3 bucket is deleted in:
  - [x] staging
  - [x] production

## Security Considerations
Remove legacy infrastructure that no longer impacts the platform or its customers

**Comment by hursey013** [comment]
Update to core https://github.com/cloud-gov/pages-core/pull/3951

**Comment by apburnes** [comment]
Once we remove the shared bucket service from the app manifest, I think we'll be good to delete the services. (see https://github.com/cloud-gov/pages-core/blob/staging/.cloudgov/manifest.yml#L21)

**Comment by apburnes** [comment]
Complete
