### ISSUE TITLE
Update Netlify CMS authentication to no longer check users' `federalist-user` affiliation

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/product#2113]
In order to support our transition to Pages, users will need to be able to authenticate into their instances of Netlify CMS without having to belong to the [`federalist-users` org](https://github.com/federalist-users).

## Acceptance Criteria
- [ ] Users with write access to a Pages site Github repository will be able to sign into the Netlify CMS admin interface without having to be apart of the `federalist-users` group
- [ ] Completed before users begin migrating to UAA since UAA users will be automatically removed from the `federalist-users` org

## Implementation Sketch
- Update [`github2`](https://github.com/18F/federalist/blob/staging/api/services/passport.js#L127) passport strategy to no longer check for `federalist-users` org affiliation
- [Authentication routes](https://github.com/18F/federalist/blob/staging/api/routers/auth.js#L58-L59) for Netlify CMS auth

## Security Considerations
Needed to complete SCR

**Comment by hursey013** [comment]
Let me know if this is included w/ the work you've been doing @drewbo

**Comment by drewbo** [comment]
@hursey013 yup, apologies for not updating yesterday:
- One of the links above is incorrect in that external authentication from netlify uses the `github` strategy (not `github2`) which calls [`validateUser`](https://github.com/cloud-gov/pages-core/blob/5d31f2115a7b15a3ec6041a9ab0a57a079bec676/api/services/passport.js#L68-L75) to confirm membership in the `federalist-users` organization. Note that it is called conditionally based on the application, so pages will already skip this check. 
- All of our templates currently [point to federalist](https://github.com/cloud-gov/pages-uswds-jekyll/blob/main/admin/config.yml#L1-L7) as the authentication mechanism. I'll have PRs up in a bit to change those to pages.
- The remaining issue this creates is that old sites will continue to authenticate against federalist until this `config.yml` is changed. We should look out for this during migration and monitor this endpoint (`/auth/github`) in the logs to proactively reach out to folks.

**Comment by drewbo** [comment]
Template updates:
- https://github.com/cloud-gov/pages-uswds-jekyll/pull/276
- https://github.com/cloud-gov/pages-uswds-11ty/pull/7
- https://github.com/cloud-gov/pages-uswds-gatsby/pull/488

**Comment by drewbo** [comment]
I've also added a [saved logstash query](https://logs.fr.cloud.gov/app/discover#/view/fe65b550-2a1d-11ed-a366-49c100e2adfc) to track requests against this endpoint

**Comment by apburnes** [comment]
Let's create a new issue to put together some options for notifying users on the endpoint deprecation and then close this out.
