### ISSUE TITLE
EL1: Update logs to comply with time standards

### ISSUE THREAD

**Issue by markdboyd** [cloud-gov/product#2124]
In order to comply with EO M-21-31, we need to use timestamps that comply with the EO standards

## Background

- [Presidential Memorandum M-21-31](https://www.whitehouse.gov/wp-content/uploads/2021/08/M-21-31-Improving-the-Federal-Governments-Investigative-and-Remediation-Capabilities-Related-to-Cybersecurity-Incidents.pdf).
- [Notes from discussion with assurance team about M-21-31](https://docs.google.com/document/d/11PcgXjs42hrYu8o91ep2vmdS5TkjmTw69Br0P1BvsBg/edit)

## Acceptance Criteria

* [ ] GIVEN that we want to comply with EO M-21-31
  WHEN I view app or syste, logs
  THEN I see a compliant timestamp format

--- 

## Security considerations

Allows compliance with EO M-21-31

## Implementation sketch

* [x] Determine the format that timestamps are actually stored in our logs vs how they are presented in Kibana
* [x] If necessary, update configuration for timestamps in log system (platform and customer)

**Comment by dandersonsw** [comment]
From the M-21-31 doc: "Software developed by agencies or by contractors on behalf of agencies must log timestamps for each event in
accordance with these requirements. If the software does not produce data in this format, Federal agencies will
transform records to conform to these standards before the data is ingested into the SIEM or stored in bulk storage. "

**Comment by markdboyd** [comment]
Preliminary research indicates that our timestamp fields are stored as [`date` fields in Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/date.html), which has a default format of [`strict_date_optional_time`](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/mapping-date-format.html#strict-date-time). `strict_date_optional_time` seems to conform to the desired format:

`yyyy-MM-dd'T'HH:mm:ss.SSSZ`

Viewing records in Kibana is misleading because it transforms to a display format like `Aug 29, 2022 @ 17:22:51.246`. But you can retrieve the raw records from Elasticsearch to see the format they are stored in. For example, here is the value of `@timestamp` from the raw document:

`"@timestamp": "2022-08-29T21:22:51.246Z"`

**Comment by markdboyd** [comment]
For further confirmation, you can see in the component template that the `@timestamp` field is defined as a `date` field:

https://github.com/cloud-gov/logsearch-for-cloudfoundry/blob/2c748b78a5fdfd02163cbab2a324e90597616336/jobs/elasticsearch-config-lfc/templates/component-index-mappings.json.erb#L39

**Comment by markdboyd** [comment]
The language from the executive order states:

> Agencies shall maintain log timestamps in a format that meets the following requirements, based on both ISO 7 8601 and RFC 3339: Date and Time on the Internet: Timestamps.
YYYY-MM-DDThh:mm:ss.mmmZ (Zulu time, UTC+0) and  YYYY-MM-DDThh:mm:ss.mmm+04:00 (UTC+4)

By looking at the raw data in Elasticsearch, we have confirmed that our timestamps are stored in an approved format:

`"@timestamp": "2022-08-29T21:22:51.246Z"`

Later on, it further specifies:

>  +|-= time zone designator (Z or +hh:mm or -hh:mm), the + or – values indicate how far ahead or behind a time zone is from the UTC (Coordinated Universal Time) zone.

Based on that language, it seems that if a `Z` is present in the timestamp, it indicates that the timestamp is in zulu time and there is no offset from UTC, thus the `+/-` string at the end of the timestamp is unnecessary.

So my interpretation is that we are already storing timestamps in a format that is compatible with M-21-31 requirements and we can close this ticket.
