### ISSUE TITLE
EL1 requirement: Investigate/implement integrity verification mechanisms

### ISSUE THREAD

**Issue by markdboyd** [cloud-gov/product#2126]
From the [EO](https://www.whitehouse.gov/wp-content/uploads/2021/08/M-21-31-Improving-the-Federal-Governments-Investigative-and-Remediation-Capabilities-Related-to-Cybersecurity-Incidents.pdf):

> Using integrity-verification mechanisms to detect unauthorized changes to event logging configuration and log files that are no longer being written to or are considered closed. 

## Background

- [Presidential Memorandum M-21-31](https://www.whitehouse.gov/wp-content/uploads/2021/08/M-21-31-Improving-the-Federal-Governments-Investigative-and-Remediation-Capabilities-Related-to-Cybersecurity-Incidents.pdf).
- [Notes from discussion with assurance team about M-21-31](https://docs.google.com/document/d/11PcgXjs42hrYu8o91ep2vmdS5TkjmTw69Br0P1BvsBg/edit)

## Acceptance Criteria

* [ ] Verify that sufficient integrity-verification mechanisms are in place to detect unauthorized changes

--- 

## Security considerations

Allows compliance with EO M-21-31

## Notes

Event logging configuration protection should be covered by existing authentication mechanisms in our logging platform.

## Implementation sketch

* [ ] Research existing integrity verification mechanisms built into Logsearch system or our deployment of it that protect against writing to log files considered closed

**Comment by dandersonsw** [comment]
This is the WIP PR: https://github.com/cloud-gov/cg-site/pull/2165

**Comment by dandersonsw** [comment]
We could enable "Object Lock" on our S3 buckets to implement write-once-read-many (WORM).

We could use Index Lifecycle Policies to make indexes read only when they rollover? https://www.elastic.co/guide/en/elasticsearch/reference/current/index-lifecycle-management.html

**Comment by markdboyd** [comment]
From meeting with @pburkholder, investigate:

- Cost of enabling S3 Object Lock given requirement of S3 object versioning
- Lifespan of Elasticsearch log files
- Any other options in AWS? May be worth asking Taylor Wulf, our AWS support contact

Action:

- Use lifecycle policies for logs in ELK

**Comment by dandersonsw** [comment]
Currently s3 buckets can only be written to by the bucket owner, and must specify encryption for any put request.

- Customer logs in s3 are currently set to expire after (548 days)[https://github.com/cloud-gov/cg-provision/blob/eb9a65cb9793769ca02a7ff938392be0ea7f5fbf/terraform/modules/cloudfoundry/buckets.tf#L29]
- Platform logs in s3 are currently set to expire after (365 days)[https://github.com/cloud-gov/cg-provision/blob/eb9a65cb9793769ca02a7ff938392be0ea7f5fbf/terraform/modules/logsearch/platform_log_bucket.tf#L14]

**Comment by dandersonsw** [comment]
Current elasticsearch retention:

- Customer logs are retained for [180 days](https://github.com/cloud-gov/cg-deploy-logsearch/blob/master/logsearch-jobs.yml#L91)
- Platform logs are retained for [30 days](https://github.com/cloud-gov/cg-deploy-logsearch/blob/master/logsearch-platform-jobs.yml#L64)

**Comment by dandersonsw** [comment]
This has been successfully implemented in our ELK stack using the **index_settings** action from the curator to set indices older than 1 day to read only
