### ISSUE TITLE
EL1 requirement: Conduct data integrity checks periodically and on retrieval

### ISSUE THREAD

**Issue by markdboyd** [cloud-gov/product#2127]
From the [EO](https://www.whitehouse.gov/wp-content/uploads/2021/08/M-21-31-Improving-the-Federal-Governments-Investigative-and-Remediation-Capabilities-Related-to-Cybersecurity-Incidents.pdf):

> Conducting integrity checks periodically and upon access against the log hashes throughout their retention period.

## Background

- [Presidential Memorandum M-21-31](https://www.whitehouse.gov/wp-content/uploads/2021/08/M-21-31-Improving-the-Federal-Governments-Investigative-and-Remediation-Capabilities-Related-to-Cybersecurity-Incidents.pdf).
- [Notes from discussion with assurance team about M-21-31](https://docs.google.com/document/d/11PcgXjs42hrYu8o91ep2vmdS5TkjmTw69Br0P1BvsBg/edit)

## Acceptance Criteria

* [ ] Verify that integrity checks are performed regularly and on data access

--- 

## Security considerations

Allows compliance with EO M-21-31

## Prior background/research

Lucene keeps a checksum for each shard in the file that stores the shard, and that the checksum is validated at least:
- when a node (re)starts
- when the shard is replicated
- when the shard is relocated
- when the shard is restored
- when an index is `open`ed

Between these, we'd expect at a minimum that file contents are checked when we update elasticsearch, which happens approximately weekly due to stemcells. I have a hunch that relocation happens periodically due to the daily creation and deletion of indices, but I haven't been able to validate that. I also have a hunch that Lucene may use these checksums more frequently (e.g. when loading a file into memory to execute a search) but I haven't found any documentation about the internals.

The big questions, I think, are:
- does this count as 'upon access'
- does this count as 'periodically'
- is it acceptable that the checksums are in the same file they're intended to protect

Looking into Lucene docs, it seems like each time a file is read, it is checked against its checksum, so I believe we do have `upon access` validation happening

## Implementation sketch

* [ ] Research existing integrity checks built into Logsearch system or our deployment of it
* [ ] Document integrity checks performed by Logsearch and assess whether they are sufficient for this requirement (may require input from assurance team)

**Comment by markdboyd** [comment]
Some useful commentary about Lucene/Elasticsearch checksumming in this post:

https://davecturner.github.io/2020/12/23/lucene-checksums.html

**Comment by markdboyd** [comment]
According to representatives from Elastic support, checksums are generated by Lucene at these times:

- when segments are flushed (written to disk)
- when merging segments

And checksums are verified by Lucene at these times:

- when creating snapshots
- on shard rebalancing
- on cluster restart

They also confirmed that Lucene/Elasticsearch does read checksums when accessing index files and will throw an error if they have been corrupted.

@dandersonsw - Do you think this functionality meets the requirements of "Conducting integrity checks periodically and upon access against the log hashes throughout their retention period."? I'm inclined to say that it does.

**Comment by dandersonsw** [comment]
I am also inclined to say that this meets the requirements related to "Conducting integrity checks periodically and upon access against the log hashes throughout their retention period."

**Comment by markdboyd** [comment]
Closing based on agreement that the current Lucene/Elasticsearch functionality meets the EO requirements
