### ISSUE TITLE
Sunset Federalist site

### ISSUE THREAD

**Issue by Ephraim-G** [cloud-gov/product#2136]
Deprecate the old Federalist pending the successful launch of pages.cloud.gov 

## Acceptance Criteria
* [ ] GIVEN the newly launched pages.cloud.gov site is fully operational \
  WHEN a user visits federalist.18f.gov \
  AND the user receives an 404 error message

--- 

## Security considerations
none

**Comment by wz-gsa** [comment]
@sknep confirmed this can be closed
