### ISSUE TITLE
CloudFoundry Document Indexing

### ISSUE THREAD

**Issue by ArsHaider** [cloud-gov/product#2137]
Research barrier to indexing CF docs with the Cloud gov knowledge base.

**Comment by mogul** [comment]
My understanding is that we were told it was not OK to have search.gov indexing and directing users to a non-.gov site. So it's not a technical barrier, but a policy barrier.

(This is why https://github.com/cloud-gov/product/issues/1780 exists... The CF docs are set up to be branded and incorporated into other websites, eg https://docs.pivotal.io/. If cloud.gov similarly incorporates that CF documentation content into cg-site, then there's no problem with search.gov indexing it alongside everything else on the site.)

**Comment by Ephraim-G** [comment]
issue has been solved
