### ISSUE TITLE
Identify components that have logs flowing into platform logs system

### ISSUE THREAD

**Issue by markdboyd** [cloud-gov/product#2149]
In order to get a better understanding of our logging system, we need to document what components feed data into it

## Background

- [Presidential Memorandum M-21-31](https://www.whitehouse.gov/wp-content/uploads/2021/08/M-21-31-Improving-the-Federal-Governments-Investigative-and-Remediation-Capabilities-Related-to-Cybersecurity-Incidents.pdf).
- [Notes from discussion with assurance team about M-21-31](https://docs.google.com/document/d/11PcgXjs42hrYu8o91ep2vmdS5TkjmTw69Br0P1BvsBg/edit)

## Acceptance Criteria

* [x] Documentation or a diagram exists created to show what systems/components feed data into our platform logs system

--- 

## Security considerations

Diagramming our logging system makes it more intelligible to operators and easier to maintain. Both outcomes ultimately improve our ability to assess and to remediate security risks in the system.

## Implementation sketch

* [x] Research/identify system components that feed logs into our platform logs system
* [x] Create documentation or a diagram of what components feed logs into our platform logs system

**Comment by dandersonsw** [comment]
The logsearch-for-cloud-foundry bosh release is responsible for splitting logs into separate platform and app logs. This is handled by a series of snippets located here: https://github.com/cloud-gov/logsearch-for-cloudfoundry/tree/develop/src/logsearch-config/src/logstash-filters/snippets

**Comment by dandersonsw** [comment]
The order of snippets is important: https://github.com/cloud-gov/logsearch-for-cloudfoundry/blob/develop/src/logsearch-config/src/logstash-filters/default.conf.erb

**Comment by dandersonsw** [comment]
Cloud Foundry Architecture diagram for logs: https://docs.cloudfoundry.org/loggregator/architecture.html#firehose-architecture

How logs and metrics egress from VMs: https://docs.cloudfoundry.org/loggregator/architecture.html#vms-egress
