### ISSUE TITLE
Identify components that have logs flowing into customer log system

### ISSUE THREAD

**Issue by markdboyd** [cloud-gov/product#2150]
In order to get a better understanding of our logging system, we need to document what components feed data into it

## Background

- [Presidential Memorandum M-21-31](https://www.whitehouse.gov/wp-content/uploads/2021/08/M-21-31-Improving-the-Federal-Governments-Investigative-and-Remediation-Capabilities-Related-to-Cybersecurity-Incidents.pdf).
- [Notes from discussion with assurance team about M-21-31](https://docs.google.com/document/d/11PcgXjs42hrYu8o91ep2vmdS5TkjmTw69Br0P1BvsBg/edit)

## Acceptance Criteria

* [x] Documentation or a diagram exists created to show what components feed data into our customer logs system

--- 

## Security considerations

Diagramming our logging system makes it more intelligible to operators and easier to maintain. Both outcomes ultimately improve our ability to assess and to remediate security risks in the system.

## Implementation sketch

* [x] Research/identify system components that feed logs into our customer logs system
* [x] Create documentation or a diagram of what components feed logs into our customer logs system

**Comment by dandersonsw** [comment]
This is a diagram of how customer data flows through our system: https://diagrams.fr.cloud.gov/10-4.1-customer-data-flow.html
