### ISSUE TITLE
digitalgov.gov build was never queued - investigate why

### ISSUE THREAD

**Issue by hursey013** [cloud-gov/product#2159]
Folks from digital.gov reported that changes merged to their main branch were not appearing on their live website: https://gsa-tts.slack.com/archives/C1NUUGTT5/p1659136299542889

> Hi,
> Our merged pull requests aren't building in Federalist https://federalistapp.18f.gov/sites/193/builds, and the updates aren't live. Some that I worked on today:
> https://github.com/GSA/digitalgov.gov/pull/5217
> https://github.com/GSA/digitalgov.gov/pull/5223
> https://github.com/GSA/digitalgov.gov/pull/5224
> https://github.com/GSA/digitalgov.gov/pull/5225 (live page https://digital.gov/resources/negotiated-terms-of-service-agreements/ does not have the edits seen in https://github.com/GSA/digitalgov.gov/pull/5225/files, even though the 'last updated' timestamp at the bottom of the page seems correct)
> https://github.com/GSA/digitalgov.gov/pull/5226

After investigating, it was determined that while the job was created, it was never queued - blocking all future builds on that branch (due to throttling). Investigate what led to the job going into this unexpected state.

**Comment by apburnes** [comment]
Close in favor of https://github.com/cloud-gov/pages-core/issues/4026
