### ISSUE TITLE
Implement Pages support roles and permissions

### ISSUE THREAD

**Issue by hursey013** [cloud-gov/product#2164]
Our admin UI does not currently allow different roles and permissions - we need to add a new role system to allow support folks to log into and manage domains, view logs.

## Background
We are currently [transitioning from Github based authentication](https://github.com/cloud-gov/product/issues/2098) to UAA based authentication. From a complexity and effort standpoint, it makes sense to add the role system after this transition to avoid supporting two authentication schemes.

## Acceptance Criteria
* [ ] Support role description added to [Pages SCR Addendum](https://docs.google.com/document/d/1KS7BHJZVAd6gDROYOw92LVMCnwpIpf-f/edit)
* [ ] Role permissions matching this description are implemented in Pages Admin UI 

## Implementation Details
The current Admin UI authentication is implemented [here](https://github.com/18F/federalist/blob/staging/api/admin/passport.js#L56) and enforced for routes via [this middleware](https://github.com/18F/federalist/blob/staging/api/middlewares/ensure-authenticated.js). This needs to be transitioned to route-level authorization to allow for certain actions by different roles (e.g. the introduction of a `pages.support` role):
- [ ] Create new role in cloud.gov UAA
- [ ] Update passport strategy
- [ ] Add route-level authorization to relevant express endpoints

---

**Comment by drewbo** [comment]
Updating the top level comment and title to reflect work needed

**Comment by Ephraim-G** [comment]
@Ephraim-G
