### ISSUE TITLE
Add Pages status to cloud.gov StatusPage

### ISSUE THREAD

**Issue by drewbo** [cloud-gov/product#2182]
Added as a separate [component group](https://support.atlassian.com/statuspage/docs/create-a-component-group/)

Acceptance Criteria
- [x] New status group is added to cloud.gov StatusPage
- [x] Update StatusPage link on Pages app
- [x] Update StatusPage link on Pages marketing site
- [x] Change made live via deploy Pages app
- [x] Change made live via deploy Pages marketing site
- [x] Complete StatusPage migration:
  - [x] Subscribers
  - [x] Incidents
- [x] Shutdown Federalist StatusPage

**Comment by drewbo** [comment]
Pages is now added to the cloud.gov StatusPage and our subscribers have been migrated h/t @jameshochadel

**Comment by apburnes** [comment]
I think we can close this out with TTS Tech Portfolio shutting down the instance.
