### ISSUE TITLE
Change code coverage check for Pages repos

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/product#2183]
In order to maintain our code coverage status check on PRs and remove the current code climate check, we want to create a status check that compares the code coverage reports between a PR and it's merge branch using the CI tools available to us.

Change code coverage check for the following repos:
- https://github.com/18f/federalist
- https://github.com/18F/federalist-builder
- https://github.com/18F/federalist-garden-build

Add new code coverage check to the following repos:
- https://github.com/18F/federalist-proxy

## Acceptance Criteria
* [ ] Given a PR, a status check runs to compare the change in code coverage between the PR and the branch
* [x] Removes the current code climate check from the repository

--- 

## Security considerations
Removing code climate service

## Implementation sketch
* [ ] Compare the possibilities between Concourse CI and Github Actions
* [ ] Save code coverage reports for staging and main branches to compare to PR code coverage
* [x] Remove any webhooks and branch protection involving the code climate check

**Comment by markdboyd** [comment]
Confirmed with @apburnes this can be closed
