### ISSUE TITLE
Investigate number of customers/applications using MySQL 5.7

### ISSUE THREAD

**Issue by markdboyd** [cloud-gov/product#2206]
## Background

We would like to upgrade our aws-broker database plans to use db.t4g instance types in order to get performance and cost benefits, but [they only support versions of MySQL 8.0.25+](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.DBInstanceClass.html). We currently support MySQL version 5.7, so by making this change we would be dropping support for MySQL 5.7

We need to determine the size of our user base for MySQL to determine if this deprecation of support for MySQL 5.7 would likely be problematic. 

Even if there are a significant number of customers using MySQL 5.7, it may just be because that was the default when they provisioned their database, so we should still have an an engineering conversation to consider whether it is okay to deprecate support for MySQL 5.7

## Tasks

- [x] Produce a report showing the number of databases (in production) running on MySQL 5.7
- [ ] Coordinate an engineering discussion to get a consensus on whether we can deprecate support for MySQL 5.7 and move to db.t4g instance types

**Comment by cweibel** [comment]
There are 41 `5.7.*` and 74 `8.0.28` instance.

The following methodology was used to determine these numbers:

 - Query the ccdb for all app guids which have a service instance bound from the `aws-broker` where the plan name is like `%mysql%`
 - Use cf curl /v3/app/<guids from query>/env to retrieve the environment variables of the app, pulling out an instances of `rds.amazonaws.com`
 - Loop through the rds instances from the previous step and using the aws cli to retrieve the engine version

Holes in the logic - if there is more than 1 rds instance associated with an app, not all of them are necessarily provisioned with our broker (hence the 10 postgres hits), there is at least 1 instance of a CUPS or similar mysql instance being bound to an app in addition to the aws-broker brokered one.

The redacted script used is here: https://gist.github.com/cweibel/3bfd5a360f757c1f0b03ee687cb6edd3 , the exercise of providing the ccdb credentials is left to the operator.

**Comment by cweibel** [comment]
According to https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/MySQL.Concepts.VersionMgmt.html the 5.7.38 instances will lose support in June 2023 and all versions of 5.7 are losing support as of October 2023.

**Comment by cweibel** [comment]
The team met and discussed this and came up with the following:

 - Create and publish out deprecation notice for 5.7 for september (there is an example of this with Postgresql 9.5 https://cloud-gov-new.zendesk.com/agent/tickets/4375 )
 - Verify that the latest versions are in the broker 
 - Prevent creation of new 5.7
 - Create documentation to new city (backup, create new, restore) for customer and version differences between 5.7 and 8.x
 - May need to come up with a way of support on how to do this via console or similar for those customers with support
 - Verify you will be auto-updated in september with AWS person (check bi-weekly calendar - Taylor ) OR just create a support ticket

**Comment by markdboyd** [comment]
Create https://github.com/cloud-gov/aws-broker/issues/302 as a follow-up
