### ISSUE TITLE
Update deploy-deployer-account broker pipeline

### ISSUE THREAD

**Issue by dandersonsw** [cloud-gov/product#2207]
In order to successfully enable account broker services for user spaces, we want to fix the deploy-deployer-account-broker pipeline

## Acceptance Criteria
* [x] GIVEN [a precondition] \
  AND [another precondition]
  WHEN [test step] \
  AND [test step] \
  THEN [verification step] \
  AND [verification step]

--- 

## Security considerations
[note any potential changes to security boundaries, practices, documentation, risk that arise directly from this story]

## Implementation sketch
Since the test-broker job is failing, the push-broker-staging job doesn't run unless done so manually. This eventually causes the push-broker-production job to spin indefinitely, as it is waiting for an updated version from the push-broker-staging job.

* [x] Fix test-broker-job
* [x] Make sure all jobs in the pipeline run successfully

**Comment by JasonTheMain** [comment]
Working https://ci.fr.cloud.gov/teams/main/pipelines/deploy-uaa-credentials-broker/jobs/acceptance-tests-production/builds/35
