### ISSUE TITLE
Passive DNS: Implement DNS resolver query logging

### ISSUE THREAD

**Issue by markdboyd** [cloud-gov/product#2216]
## Background

Passive DNS is a requirement of [Executive Order M-21-31](https://www.whitehouse.gov/wp-content/uploads/2021/08/M-21-31-Improving-the-Federal-Governments-Investigative-and-Remediation-Capabilities-Related-to-Cybersecurity-Incidents.pdf), as seen in https://github.com/cloud-gov/product/issues/2153.

All DNS records for cloud.gov are managed in AWS Route 53. [DNS resolver query logging](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/resolver-query-logs.html) is one feature offered by Route53 that will allow us to achieve partial compliance with M-21-31.

See the [ADR on Passive DNS](https://github.com/cloud-gov/product/blob/master/adr/ADR-0008-passive-dns.md).

## Implementation

- [x] Add buckets for DNS resolver query logs which transition to IA storage after 12 months and expire data after 30 months
  - [x] development
  - [x] staging
  - [x] production
- [x] Enable DNS resolver query logging and store logs in S3 buckets
  - [x] development
  - [x] staging
  - [x] production
- ~[ ] Implement Logstash configuration to import logs from S3 into ELK~
- ~[ ] Update BOSH releases as necessary to have resolver query logs continuously imported from S3~

## Acceptance criteria

- [x] Resolver query logs are appearing in S3 ~and ELK~
- ~[ ] ELK logs are formatted according to the standards on page 15 of [Executive Order M-21-31](https://www.whitehouse.gov/wp-content/uploads/2021/08/M-21-31-Improving-the-Federal-Governments-Investigative-and-Remediation-Capabilities-Related-to-Cybersecurity-Incidents.pdf)~

**Comment by markdboyd** [comment]
After discussion with the team, we decided that there is not an imminent need to push these logs from S3 to ELK, especially considering that shipping these logs to ELK could significantly increase the storage needs for our Elasticsearch nodes.

Since the work to enable the query resolver logs and ship them to S3 is already done for development, staging, and prod, this ticket can be closed.

**Comment by pburkholder** [comment]
I don't see any documentation on how to find and query these logs. Can we add that to internal docs and the ADR? I'm reopening until we have that, or we can resolve in another issue (or close with a link if documentation already exists). TY

**Comment by markdboyd** [comment]
@pburkholder  Do these PRs address the concerns?

https://github.com/cloud-gov/internal-docs/pull/65
https://github.com/cloud-gov/product/pull/2225

Other related PRs that I forgot to document

https://github.com/cloud-gov/product/pull/2215
https://github.com/cloud-gov/cg-provision/pull/1129/files

**Comment by pburkholder** [comment]
Thanks for the internal-docs updates, that'll help when we actually need to use those logs.

Can you update the ADR with why we ship to S3 instead of cloudwatch logs? It's an implementation that, since I have it, I expect others will tool.

**Comment by markdboyd** [comment]
@pburkholder I think I just defaulted to S3 out of the assumption that storing to S3 was probably cheaper. And initially I was going to ship these logs to ELK as well and knew that there was a well-defined path for importing S3 files into ELK.

**Comment by markdboyd** [comment]
@pburkholder After offline discussion and [creating a spreadsheet to estimate of costs storing these logs in S3 vs Cloudwatch](https://docs.google.com/spreadsheets/d/1c13rKRgWVNo0g_Dq4f9MAyusfUOVWSZcIrxgaVlw3Mc/edit#gid=0), we decided that putting these logs in Cloudwatch instead of S3 would not be cost prohibitive, so I've changed our implementation and docs to use Cloudwatch instead:

https://github.com/cloud-gov/cg-provision/pull/1136
https://github.com/cloud-gov/product/pull/2232
https://github.com/cloud-gov/internal-docs/pull/66

Let me know if that addresses the concern.
