### ISSUE TITLE
Update compliance inventory worksheets for container scanning

### ISSUE THREAD

**Issue by soutenniza** [cloud-gov/product#2217]

**Comment by jameshochadel** [comment]
Van worked with Peter to identify gaps, which include:

* Hardening containers
* Ignoring old (~2013) CVEs
* Finishing ConMon pipeline to scan containers

After which, this goes to Peter.

**Comment by jameshochadel** [comment]
Time-sensitive; priority during PI sprint.

**Comment by jameshochadel** [comment]
Waiting on Peter; may go into next PI.

**Comment by soutenniza** [comment]
Closing this one out since inventory is done. New stories for others will be added
