### ISSUE TITLE
Enable CloudFront and Shield Advanced for entire platform

### ISSUE THREAD

**Issue by jameshochadel** [cloud-gov/product#2219]
* [x] Create ADR in the product repo
  * https://github.com/cloud-gov/product/blob/master/adr/ADR-0009-shield-advanced.md
  * [x] Need to update this to reflect that we need to enable WAF in commercial. We already have it enabled in Gov, but Shield can't write to it cross-partition.
* [ ] Find earlier SCR and take ownership + update
  * Folder: https://drive.google.com/drive/folders/1OS63mtGAFjGmXRBvbzHotATS2ahZE4AJ
* [ ] Update SSP
* [ ] See if change can be tested in development, given that it's not on the public internet
* [ ] Implement change in cg-provision

**Comment by markdboyd** [comment]
We're going to close this issue, because we have broken the work down into smaller issues that are included in https://github.com/cloud-gov/product/issues/2272.
