### ISSUE TITLE
Refactor of cloud.gov Pages repos

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/product#2228]
In order to keep our repos current and consistent, complete a series of general refactoring tasks across the cloud.gov Pages repositories.

## Acceptance Criteria
_Note: The following list maybe broken down into separate issues in their respective repositories_

- [x] Update dependencies and remove deprecated libraries
- [ ] Create consistency across certain code base portions (import vs require, multiple iterations of auth functions in core, njk vs jsx, etc)
- [ ] Drop unused services, unused code, partially implemented experiments (or complete)
- [x] Cut down on noisy warnings, deprecation warnings, build info/warnings
- [ ] Update/audit repo README documentation

**Comment by drewbo** [comment]
Some updates made here as part of 31.IP Sprint, removing iteration until better scoped

**Comment by apburnes** [comment]
Closing for more specific issues.
