### ISSUE TITLE
Remove AWS, GitHub, and CF privileges for team member on extended leave

### ISSUE THREAD

**Issue by pburkholder** [cloud-gov/product#2233]
In order to meet 30-day absence / access policy, https://docs.google.com/document/d/1MO0-XQW5BCDpaNRfd9KivCrL1y8t4nNvjlhP5yZUvyU/edit, 
we want to remove privileged access for team members on extended leave.

## Acceptance Criteria
* [x] AWS privs revoked
* [x] CF admin privs revoded
* [x] GitHub team memberships updated. 
--- 

## Security considerations
Align with policy.

**Comment by markdboyd** [comment]
https://github.com/cloud-gov/aws-admin/pull/28
