### ISSUE TITLE
[Research] Jammy or Bionic FIPS Stemcells

### ISSUE THREAD

**Issue by soutenniza** [cloud-gov/product#2250]
In order to figure our path forward for stemcells, we want know which bosh stemcell to move to.

## Acceptance Criteria
Jammy or FIPS

--- 

## Security considerations
Bionic is EOL in April. 
FIPS is not approved for Jammy
CF-Deployment already switched default stemcell to Jammy

## Implementation sketch
* [ ] Work with assurance to see what is more important, FIPS or Jammy
* [ ] Figure out if Jammy is

**Comment by pburkholder** [comment]
We decided to go ahead with Jammy stemcells since the EOL for Bionic stemcells rendered that path a dead end.
