### ISSUE TITLE
CFLinuxsf4 Stack for Applications

### ISSUE THREAD

**Issue by soutenniza** [cloud-gov/product#2252]
In order to ensure we move out of bionic for buildpacks, we want to start testing our applications using the cflinuxsf4 stack

## Acceptance Criteria
* [ ] Verify that language buildpacks are supporting cflinuxsf4 - Example: https://github.com/cloudfoundry/nodejs-buildpack/releases/tag/v1.8.0
* [ ] CG Applications working on new stack
* [ ] Customer communication about moving to cflinuxsf4

--- 

## Security considerations
cflinuxsf3 is EOL in April

## Implementation sketch
* [ ] Confirm all our default buildpacks have new stack added
* [ ] Start testing our simple apps with new stack - doc here: https://docs.cloudfoundry.org/devguide/deploy-apps/stacks.html
* [ ] Blog post or status page about new stack

**Comment by markdboyd** [comment]
Superseded by other tickets
