### ISSUE TITLE
Enable AWS GuardDuty for GovCloud

### ISSUE THREAD

**Issue by markdboyd** [cloud-gov/product#2271]
## Background

See the [Security: Monitoring & Alerting ADR](https://github.com/cloud-gov/product/blob/main/adr/ADR-0010-aws-security-monitoring-alerting.md) for background on this feature

## Prerequisites

- https://github.com/cloud-gov/product/issues/2342
- https://github.com/cloud-gov/product/issues/2343

## Acceptance criteria

- [x] GuardDuty is enabled in all accounts of the GovCloud AWS Organization
- [x] GuardDuty is managed in the security account of the GovCloud AWS Organization

## Implementation

Possibly useful guide from AWS as a reference: https://github.com/aws-samples/amazon-guardduty-for-aws-organizations-with-terraform/blob/main/enable-gd/modules/guardduty-baseline/main.tf

1. Add code in `cg-provision` in the organization management account to designated delegated administrator
    - reference: <https://github.com/aws-samples/amazon-guardduty-for-aws-organizations-with-terraform/blob/main/enable-gd/modules/guardduty-baseline/main.tf#L47>
1. Add code in `cg-provision` to enable AWS GuardDuty in the delegated administrator account
    - https://github.com/aws-samples/amazon-guardduty-for-aws-organizations-with-terraform/blob/881be14a671a9c5ba82317ca52a88c4577a7e397/enable-gd/modules/guardduty-baseline/main.tf#L28
    - https://github.com/aws-samples/amazon-guardduty-for-aws-organizations-with-terraform/blob/881be14a671a9c5ba82317ca52a88c4577a7e397/enable-gd/modules/guardduty-baseline/main.tf#L58
    - https://github.com/aws-samples/amazon-guardduty-for-aws-organizations-with-terraform/blob/881be14a671a9c5ba82317ca52a88c4577a7e397/enable-gd/modules/guardduty-baseline/main.tf#L97
1. Add code in `cg-provision` to link accounts as members of the GuardDuty
    - https://github.com/aws-samples/amazon-guardduty-for-aws-organizations-with-terraform/blob/881be14a671a9c5ba82317ca52a88c4577a7e397/enable-gd/modules/guardduty-baseline/main.tf#L76

**Comment by markdboyd** [comment]
During the JAB review of the SCR, they requested security assessment as a next step, so this work is on hold until that security assessment is complete

**Comment by jameshochadel** [comment]
Security assessment might mean it needs to be assessed by the 3pao. Might be able to combine with AA.

**Comment by markdboyd** [comment]
@pburkholder got this SCR included in the annual assessment

**Comment by markdboyd** [comment]
The annual assessment interview for GuardDuty is scheduled for Thursday, February 23, so we need to have it enabled in at least one account by then

**Comment by markdboyd** [comment]
Work here has started to support the annual assessment:

https://github.com/cloud-gov/aws-admin/pull/56
https://github.com/cloud-gov/aws-admin/pull/62
https://github.com/cloud-gov/aws-admin/pull/63

**Comment by markdboyd** [comment]
More PRs:

https://github.com/cloud-gov/aws-admin/pull/64
https://github.com/cloud-gov/aws-admin/pull/65
https://github.com/cloud-gov/aws-admin/pull/69
https://github.com/cloud-gov/aws-admin/pull/70

**Comment by markdboyd** [comment]
GuardDuty is now configured and enabled in all accounts. Closing the issue.
