### ISSUE TITLE
Harden containers to CIS Level 1 Benchmarks

### ISSUE THREAD

**Issue by pburkholder** [cloud-gov/product#2301]
For FedRAMP we need to harden container to CIS L1, as we do for VMs. 

I think we can use the [FIPS container process](https://ubuntu.com/blog/fips-ubuntu-container-security-updates) to apply [Ubuntu Advantage CIS hardening](https://ubuntu.com/security/certifications/docs/cis)

**Comment by pburkholder** [comment]
Van and I have decided that on this iteration, all CVEs for the UbuntuAdvantage hardened image are false positives, and then we will inspect all the findings from Grype for the images postinstall.

**Comment by pburkholder** [comment]
UA hardening is now working, and then UA (Ubuntu Advantage) token and tools are removed from the image before storing in ECR.

**Comment by pburkholder** [comment]
Van, David: Where do matters stand with this? I need to give the JAB an update.

**Comment by dandersonsw** [comment]
Container hardening has been implemented, and cis audit results are emailed at the beginning of every month. Work that still needs to be done has been separated out into other tickets
