### ISSUE TITLE
Create interview guide/template

### ISSUE THREAD

**Issue by markdboyd** [cloud-gov/product#2304]
## Notes

- Possibly collaborate with research guild to create interview guide
- Make sure to ask about support experience as part of the interview

**Comment by jameshochadel** [comment]
* More in depth than customer survey
* Mid- and long-term roadmaps from customers
* Usefulness, developer experience of platform

**Comment by rbogle** [comment]
https://docs.google.com/document/d/1kTMlaqAReJFj4nZSs-1iYbR76cf-PDMRgC-f4fij_Wg/edit

**Comment by rcgottlieb** [comment]
I incorporated the above document into a more formal set of documents to flesh out a process around conducting the interviews as well as recording the results. This is my first stab at it. Note that I copied quite a bit from other research work templates in TTS. 

https://docs.google.com/document/d/1OBXZtcbzoECwoA1ItxVmZn9zYiAANdS6fj0rqClJuiI/edit

**Comment by rcgottlieb** [comment]
I'm marking this as done and am noting that this is a living document. I expect after the first or second interview we might change (add, delete, update) some of the questions. For now, this is good enough to get going after the New Year.
