### ISSUE TITLE
Migrate 18F users and repos from Federalist to cloud.gov Pages

### ISSUE THREAD

**Issue by drewbo** [cloud-gov/product#2312]
There are a large number of 18F repositories that require migration to cloud.gov Pages. We'll setup a separate meeting, outside the standard migration meeting schedule, to handle these.

**Comment by drewbo** [comment]
Moving to the next sprint to avoid Performance Review season

**Comment by apburnes** [comment]
Should we move this to the next sprint again since folks are tied up with the holiday and annual reviews?

**Comment by apburnes** [comment]
Migrated initial sites with 18F folks
