### ISSUE TITLE
Issue Pages support role level access for the ZAP scan

### ISSUE THREAD

**Issue by Ephraim-G** [cloud-gov/product#2329]
In order to be able to run ZAP scans James H. will be granted a support level permissions role to be able to access the Pages UI admin interface. 

## Acceptance Criteria
* [ ] GIVEN when logged into the Pages UI with the support level role \
  THEN the user will have necessary access privileges for auditing purposes.
--- 

## Security considerations
The support level role will be assigned and **NOT** a full admin role with delete privileges.  

Support Role incorporates the following:  Audit only cloud.gov platform control, No delete access in the Pages administrative application, Administrative access to Pages application

**Comment by pburkholder** [comment]
I approve.  

We may want to make this standard access for Platform Ops, at least until we have a better scanning regime in place.

**Comment by jameshochadel** [comment]
Added `pages.support` role to myself in staging and production, but @hursey013 is taking over the scans because those permissions weren't sufficient. Progress on that is tracked elsewhere, so I'm closing this ticket as done.
