### ISSUE TITLE
Update S3 resource image to use Ubuntu as base image

### ISSUE THREAD

**Issue by markdboyd** [cloud-gov/product#2332]
## Background

In order to leverage our tools for container image hardening, which expect Ubuntu as the base layer, we need to update our S3 resource image from using Alpine Linux as the base image to using Ubuntu

## Implementation

- [x] Update S3 resource image Dockerfile to use `ubuntu:18.04` instead of `alpine`: https://github.com/cloud-gov/s3-resource-simple/blob/main/Dockerfile#L1
  - Create a PR and merge after approval
- [x] Make sure `s3-resource-simple-job` succeeds with your changes included: https://ci.fr.cloud.gov/teams/main/pipelines/update-task-image
- [x] Make sure that the S3 resource in the `cg-pgp-keys` pipeline still works by re-running it: https://ci.fr.cloud.gov/teams/main/pipelines/cg-pgp-keys/resources/pgp-keys-s3-simple
  - This will confirm that changing the image from alpine to ubuntu didn't break anything
- [x] If manual testing of the image above reveals an issue, then address with PRs to https://github.com/cloud-gov/s3-resource-simple/blob/main/Dockerfile
  - Pair with @markdboyd to resolve issues as necessary
- [x] Remove these lines from the CI pipeline that builds the S3 resource image:
  - https://github.com/cloud-gov/cg-deploy-concourse-docker-image/blob/main/pipeline.yml#L50-L53
  - https://github.com/cloud-gov/cg-deploy-concourse-docker-image/blob/main/pipeline.yml#L118-L121

**Comment by markdboyd** [comment]
@pburkholder After discussing with @soutenniza, we thought that using Ubuntu was required since our container hardening tools only work on Ubuntu

**Comment by dtamasang2** [comment]
The S3 resource image has been updated to Ubuntu 18.04 and the CI pipeline updated.
