### ISSUE TITLE
Tracking/managing 2023 annual assessment

### ISSUE THREAD

**Issue by pburkholder** [cloud-gov/product#2334]
This is an issue for our "Ongoing" column for Dec 2022 through March 2023. Since much of the actual work is on the 3PAO's SmartSheet, we'll not detail this exhaustively. However, we may create subtasks so our "Doing" column is correct.

**Comment by Chiakao** [comment]
Reviewing strategy for ARL as of 12/6

**Comment by pburkholder** [comment]
Reference:
cloud-gov/cg-compliance#211

**Comment by markdboyd** [comment]
Annual assessment is wrapped up, so closing this ticket
