### ISSUE TITLE
Update container-scanning pipeline to allow ignoring vulnerabilities

### ISSUE THREAD

**Issue by markdboyd** [cloud-gov/product#2338]
## Background

We have a pipeline for scanning container images before they are published to ECR for internal use. The code for the pipeline can be found here (note that the code only lives in the `initial-deploy` branch): https://github.com/cloud-gov/container-scanning/tree/inital-deploy

The container scanning pipeline in CI can be found here: https://ci.fr.cloud.gov/teams/main/pipelines/container-scanning

Sometimes, the scanning tool that we are using, [`grype`](https://github.com/anchore/grype), may be detect vulnerabilities that are false positives or not relevant (as decided by the compliance team).

As a result, we want to implement the ability to ignore certain vulnerabilities across all of our scans in the container-scanning pipeline. [`grype` has documentation for how to create a file with ignore patterns for vulnerabilities](https://github.com/anchore/grype#specifying-matches-to-ignore).

## To do

- [x] Create a new bucket in our Gov prod account: `cg-container-scanning-config`
- [x] Create an empty `grype.yaml` file in the `cg-container-scanning-config` S3 bucket
- [x] Add an S3 resource for the `grype.yaml` file to the container pipeline definition
     ```
    - name: grype-scan-ignore-config
       type: s3-simple
       source:
         bucket: cg-container-scanning-config
         region: us-gov-west-1
         path: grype.yaml
     ````
- [x] Add the `grype-scan-ignore-config` resource as an input to the scanning configuration files:
  - https://github.com/cloud-gov/container-scanning/blob/inital-deploy/ci/conmon-scan-ecr-container.yml#L9
  - https://github.com/cloud-gov/container-scanning/blob/inital-deploy/ci/scan-container.yml#L9
  - https://github.com/cloud-gov/container-scanning/blob/inital-deploy/ci/scan-ecr-container.yml#L9
- [x] Update the scanning script files to copy the ignore config to the location expected by grype: `cp grype-scan-ignore-config ~/grype.yaml`. Make sure this command runs before the `grype` command does
  - https://github.com/cloud-gov/container-scanning/blob/inital-deploy/ci/scan-container.sh
  - https://github.com/cloud-gov/container-scanning/blob/inital-deploy/ci/conmon-scan-ecr-container.sh
  - https://github.com/cloud-gov/container-scanning/blob/inital-deploy/ci/scan-ecr-container.sh
- [x] Run a test by adding a  detected low-severity vulnerability to the `grype.yaml` file in S3 then re-running the container scanning pipeline to see if that vulnerability is ignored. If the test is successful, then updated `grype.yaml` to remove the ignored vulnerability, re-run the scan and verify that the vulnerability is detected again

**Comment by dandersonsw** [comment]
Working on doing a test that the vulnerabilities are ignored

**Comment by dtamasang2** [comment]
Troubleshooting grype ignore config as it is still not ignoring set vulnerabilities

**Comment by dtamasang2** [comment]
The grype ignore configuration tested successfully. The grype.yaml file is being called by the scanning script and utilized as expected.

**Comment by dtamasang2** [comment]
Re-opening this issue to fix the conmon scanning pipeline for grype ignore.

**Comment by dtamasang2** [comment]
Modified the pipeline script by adding the following inputs to the scanning task, this fixed the missing inputs error.
- get: grype-scan-ignore-config
    trigger: true
Modified sh scan scripts by changing the input gype.yaml file path to grype-scan-ignore-config/grype.yaml and this fixed the no such file or directory error.
