### ISSUE TITLE
Shield Advanced: Add required rate limit rule to management ACL

### ISSUE THREAD

**Issue by jameshochadel** [cloud-gov/product#2354]
An ACL must have a rate limit rule in order to use Shield Advanced automatic L7 DDoS protection. (The docs wrongly say that this is optional. If you try to add the protection in the console, it says it's required.)

**Comment by markdboyd** [comment]
Per the ADR, this is being deprioritized for now. See https://github.com/cloud-gov/internal-docs/pull/197
