### ISSUE TITLE
FIPS 140: Assess customer appetite for excluding IdP from authorization boundary

### ISSUE THREAD

**Issue by pburkholder** [cloud-gov/product#2360]
Per our response to the FedRAMP JAB, we are this quarter assessing option 1 for resolving _compliance_ issues with cloud.gov IdP. 

> 1. cloud.gov customers adopt their agency IdP and inherit their agency's relevant controls/compliance status or accept the risk of using the cloud.gov IdP and attendant FIPS 140 status

If we were to make this policy change, 
a) the cloud.gov IdP would only be authorized for sandboxes -- which are not authorized to hold federal data
b) the cloud.gov IdP would be authorized by the customer, and no longer part of the FedRAMP Authorization Boundary Diagram

Not all customers are using their agency IdP, so we would need to discuss the proposed policy with a representative sample, and use results to inform investing in this option or pursuing other options.

## Acceptance criteria
- [ ] 2 customers with ATOS have interview reports filed in [Customer IdP Interviews folder](https://drive.google.com/drive/folders/1MkYGqcGc3loG7uIdvaMlh4FrltUpOp5Q)
- [ ] 1 customer pursuing an ATO has an interview report filed in [Customer IdP Interviews folder](https://drive.google.com/drive/folders/1MkYGqcGc3loG7uIdvaMlh4FrltUpOp5Q)
- [ ] The cloud.gov team has summarized their recommendations/next steps publicly

**Comment by pburkholder** [comment]
[Document for selecting customers](https://docs.google.com/document/d/1t2DdhF6K9zpNb1a9GvAh9Siftp92RtvS555NWyuzGcc/edit#)

**Comment by jameshochadel** [comment]
Adding myself. As discussed in Sprint Architecture Meeting today, an alternative to interviewing customers or moving the IDP out of the boundary is to rebuild Shibboleth and UAA Extras to use FIPS-validated cryptographic modules. I documented the cryptography in Shibboleth and UAA Extras, so I have a little context and could do research on that avenue.

**Comment by jameshochadel** [comment]
OS-level support is required in the pre-start script to generate a certificate with `openssl`: https://github.com/cloudfoundry/uaa-release/blob/66132b8f36a3b2f075da599707d425ee7d16897a/jobs/uaa/templates/bin/pre-start.erb#L133-L151

**Comment by markdboyd** [comment]
Blocked until we determine if this work is necessary

**Comment by pburkholder** [comment]
Great! Thank you James.

**Comment by markdboyd** [comment]
This research is complete and was presented to the JAB, so closing this ticket
