### ISSUE TITLE
Deprecate landing.app.cloud.gov

### ISSUE THREAD

**Issue by drewbo** [cloud-gov/product#2362]
The previous documentation site (landing.app.cloud.gov) has been replaced by cloud.gov. The [repository is archived](https://github.com/cloud-gov/cg-landing) but the application is still deployed

## Acceptance Criteria
- [x] Review content to see if any additional information needs migration
- [x] Remove or redirect domain
- [x] Remove deployed application

cc: @pburkholder @Ephraim-G

**Comment by apburnes** [comment]
Redirect domains to cloud.gov and added a CG calendar note to delete the redirects in January 2024.
