### ISSUE TITLE
Patch Stratos to be compatible with new Cloud Foundry log streaming protocol

### ISSUE THREAD

**Issue by jameshochadel** [cloud-gov/product#2381]
## Background

Cloudfoundry recently changes its architecture for clients to receive streaming logs from applications.

Previously, logs were accessed via the Loggregator Traffic Controller component as seen in this document: https://docs.pivotal.io/application-service/2-8/loggregator/architecture.html

However, logs are now access via the Log Cache VMs: https://docs.pivotal.io/application-service/3-0/loggregator/architecture.html

Consequently, CloudFoundry components are being updated to retrieve logs from the Log Cache service. In the process, Stratos broke, because it is unmaintained. 

This is the code that Stratos is using to retrieve logs: https://github.com/cloudfoundry/stratos/blob/3de685ceeb01a751e84e6287576f950863d074e3/src/jetstream/plugins/cloudfoundry/cf_websocket_streams.go#L127

You can see that it relies on code which was recently deprecated: https://github.com/cloudfoundry/noaa/commit/f0749146decfd357a5583c29bd3ad2b15b322c85#diff-6062a9244038ef69f131734bb106b690368b624472c63597d883eb687376fd17L23

Even if that code in the `noaa` library weren't deprecated, the ability to retrieve logs that way was deprecated in Loggregator as of version 107, which we are now running: https://github.com/cloudfoundry/loggregator-release/releases/tag/v107.0.0

So the only option is to update Stratos to retrieve logs directly from Log Cache

## Acceptance criteria

- Stream of app logs are viewable in the dashboard

## Implementation

One idea is to see if we can copy the code from the `cf` CLI, also written in Go, and re-use it in Stratos to fetch the logs:

https://github.com/cloudfoundry/cli/blob/be7b0fd5de6ec7ddcdb9f055ef8563cc6738c639/cf/commands/application/logs.go#L101

It might also be helpful to run `CF_TRACE=1 cf logs <app>` to observe how it fetches logs

## Tasks

- [ ] Update Stratos fork to fetch logs from log cache service
- [ ] Deploy updated Stratos to dev and test whether the log stream is visible

**Comment by markdboyd** [comment]
Someone patched their own fork of Stratos: https://github.com/freudl/stratos/pull/1. Hopefully we can just adopt their changes

**Comment by rcgottlieb** [comment]
2/28/23 Update:
In build/bk-build.sh, I changed go get github.com/swaggo/swag/cmd/swag@v1.6.7 to go install github.com/swaggo/swag/cmd/swag@v1.6.7.

I was able to get the build to compile and run locally. When I pushed it to development via a merge into main, I saw what appears to be a database migration failure. Further investigation revealed that the migrations in the cnsis table were out of order according to their primary key. 

Possible next steps:
a. Continue and look at the staging database to see what migrations were applied and bring the development database to the same state manually (not preferred)
b. Roll back the development database to its prior state and rerun the deployment to see if it fixes itself (semi-preferred)
c. Roll back development to main to a point where it compiles and deploys per what is running in production, and roll back the dev database to the same point. (semi-preferred)

b or c are most likely the next step

If we choose c, we lose all of the changes we made to main after the merge from the upstream cloudfoundry master branch.

We are putting this aside for now until we have more time this week to come back to it.

**Comment by markdboyd** [comment]
Update: I have the issues with Go binary compilation for Stratos (binary name is `jetstream`) fixed, but now there are issues with the build failing when trying to apply the database migrations that were merged in from the upstream repo.

To test whether this is an issue with us not doing the upgrade path correctly, I'm attaching a new test database service to stratos in dev,  `stratos-db-mboyd-test`, which is empty to see if the database migrations will cleanly.

WIP is on this branch: https://github.com/cloud-gov/cg-deploy-stratos/tree/fix-stratos-build

**Comment by markdboyd** [comment]
I take it back. The suggested fix for the Go binary compilation from Cloudfoundry slack was to use `CGO_ENABLED=0`, but that is causing the binary compilation to fail with:

```shell
# bitbucket.org/liamstask/goose/lib/goose
../../../../go/pkg/mod/bitbucket.org/liamstask/goose@v0.0.0-20150115234039-8488cc47d90c/lib/goose/dialect.go:119:15: undefined: sqlite3.Error
```
