### ISSUE TITLE
Put hardened containers into use (Revisit 2/27)

### ISSUE THREAD

**Issue by dandersonsw** [cloud-gov/product#2386]
In order to meet FedRamp container scanning requirements, we want to replace any containers in use with hardened containers

## Acceptance Criteria
* [ ] GIVEN a pipeline currently references a container that is not hardened \
  THEN the pipeline should be updated to use a hardened container

--- 

## Security considerations
Using hardened containers will provide better security for our containers

## Implementation sketch

This script may be useful for identifying what containers a pipeline is using: https://github.com/cloud-gov/cg-scripts/blob/master/get-pipeline-container-images.sh. Or it can be used to print a list of all the containers used by all pipelines, which can help us make sure that we've updated the references in all of our pipelines

* [ ] Identify pipelines using containers
* [ ] Update the container references in the pipelines to use hardened containers

**Comment by dandersonsw** [comment]
Need to confirm with compliance, do we need an SCR before implementing this?

**Comment by markdboyd** [comment]
@pburkholder has confirmed that we don't need to wait on an SCR for this

**Comment by dandersonsw** [comment]
Majority of pipelines have been updated. Created new tickets for pipelines that still need updating
