### ISSUE TITLE
Gather customer requirements for an Observability tool

### ISSUE THREAD

**Issue by rcgottlieb** [cloud-gov/product#2390]
Questions

- Does it integrate well with CloudFoundry?
- Multi-tenancy
- Is it cost effective, i.e. does it cost less than 2 FTEs maintaining an open source stack like ELK
- Can we offer it to our customers within budget and/or cost recovery? The thought is that we still have to integrate it so there will be Platform FTE costs, and we can recover some or all of that cost depending on the price structure.
- SSO Support for integration with UAA for authn/authz
- Can we export data if we ever decide to leave the platform? Are there costs associated? What formats are supported?

**Comment by jameshochadel** [comment]
I think we should add "SSO Support" so it can integrate with UAA for authentication and authorization — are users are who they say, and they only have access to the data that's theirs (ties in with multi-tenancy).

**Comment by rcgottlieb** [comment]
> I think we should add "SSO Support" so it can integrate with UAA for authentication and authorization — are users are who they say, and they only have access to the data that's theirs (ties in with multi-tenancy).

Agreed and story updated!

**Comment by jameshochadel** [comment]
Awesome. Added one more about data export.

**Comment by markdboyd** [comment]
Superseded by https://github.com/cloud-gov/private/issues/651
