### ISSUE TITLE
Confirm Due Date for M-21-31 EL2 Requirements

### ISSUE THREAD

**Issue by dandersonsw** [cloud-gov/product#2394]
In order to meet logging/observability requirements, we want to confirm the due date for M-21-31 EL2

## Acceptance Criteria
* [x] Confirm due date of Feb 27, 2023

--- 

## Security considerations
Need to find out due date so we can remain compliant

## Implementation sketch
* [x] Discuss with Peter if the due date of Feb 27, 2023 is still relevant

**Comment by jameshochadel** [comment]
Meeting scheduled with Peter on 2/7 to discuss.

**Comment by jameshochadel** [comment]
Resolved by https://github.com/cloud-gov/private/issues/624.
