### ISSUE TITLE
[Jammy] awslogs bosh release

### ISSUE THREAD

**Issue by soutenniza** [cloud-gov/product#2397]
In order to move to jammy stemcells, we want update awslogs to work jammy VMS.
https://github.com/cloud-gov/cg-awslogs-boshrelease/pull/47 for xenial to bioinic reference

## Acceptance Criteria
* [x] New Bosh Job that is `awslogs-jammy`
* [x] Deploy in a dev VM like BOSH and confirm that logs are going to AWS CW
* [x] Runtime config updated to only certain deployments: https://github.com/cloud-gov/cg-deploy-bosh/pull/511

**Comment by markdboyd** [comment]
Confirmed that logs are appearing in Cloudwatch in the group name `awslogs-jammy` and stream names like `/var/vcap/sys/log/awslogs-jammy/awslogsd.log-<instance-id>`. 

I do some errors in the logs like:

```
2023-02-16 21:01:59,022 - cwlogs.push.publisher - WARNING - 6503 - Thread-11 - Caught exception: An error occurred (ResourceNotFoundException) when calling the PutLogEvents operation: The specified log stream does not exist.
```

However, I see these errors in recent logs for the `awslogs-bionic` job, so I think it's just a transient issue where it tries to put logs in the stream before the log stream is created

**Comment by markdboyd** [comment]
I'm not sure if I'm seeing logs for the other processes in the container appearing in Cloudwatch. Need to investigate further

**Comment by markdboyd** [comment]
I have confirmed that logs for other processes running on the Jammy test VM, like `aide` and `clamav`, are appearing in Cloudwatch. I just wasn't looking in the right place.

**Comment by markdboyd** [comment]
As seen in the referenced PRs, we are now building a BOSH release of awslogs-boshrelease for Jammy stemcells. And that release is included in the runtime config for any VMs running on Jammy stemcells. So this work is complete and the ticket can be closed.
