### ISSUE TITLE
[Jammy] Test, Verify, and Update clamav release 

### ISSUE THREAD

**Issue by soutenniza** [cloud-gov/product#2400]
In order to [reason/outcome/goal], [someone or "we"] want [a specific change in product implementation/behavior]

## Acceptance Criteria
* [ ] GIVEN [a precondition] \
  AND [another precondition]
  WHEN [test step] \
  AND [test step] \
  THEN [verification step] \
  AND [verification step]

--- 

## Security considerations
[note any potential changes to security boundaries, practices, documentation, risk that arise directly from this story]

## Implementation sketch
[links to background notes, sketches, and/or relevant documentation
* [ ] [first thing to do]
* [ ] [another thing to do]

**Comment by markdboyd** [comment]
This task was completed successfully as a team. 

For reference on how to include releases in runtime config for Jammy: https://github.com/cloud-gov/cg-deploy-bosh/pull/500
