### ISSUE TITLE
[Jammy] Test, Verify, and Update syslog release 

### ISSUE THREAD

**Issue by soutenniza** [cloud-gov/product#2403]
In order to keep our system dependencies up to date and be ready for security patches, we want to verify that our syslog bosh release is compatible with the Ubuntu Jammy stemcell

## Acceptance Criteria

* [x] Using a test manifest/deployment, we demonstrate the syslog bosh release compiles on Ubuntu Jammy
* [x] Using a test deployment, verify that syslog runs successfully in a VM running on Ubuntu Jammy
* [x] Update runtime config to include syslog bosh release as part of for Ubuntu Jammy VMs
  * [ ] If necessary, updated/change the manifest properties for release

--- 

## Security considerations

Verifying our compatibility with Ubuntu Jammy will help us stay up-to-date on security patches

## Resources

- Ticket for testing of syslog release for Bionic: https://github.com/cloud-gov/product/issues/1580
- Syslog release: https://github.com/cloudfoundry/syslog-release
- Example manifest for deploying a single release on Ubuntu Jammy (replace clamAV with release of choice): https://github.com/cloud-gov/cg-deploy-bosh/blob/89a0f7908462ee961cdf89d197d2027b1b208038/empty-vm.yml
- Example of adding ClamAV to runtime config for Jammy: https://github.com/cloud-gov/cg-deploy-bosh/pull/500

**Comment by JasonTheMain** [comment]
https://github.com/cloud-gov/cg-deploy-bosh/pull/501
