### ISSUE TITLE
[Jammy] Test, Verify, and Update cg-hardening/FISMA release 

### ISSUE THREAD

**Issue by soutenniza** [cloud-gov/product#2404]
In order to keep our system dependencies up to date and be ready for security patches, we want to verify that our hardening/FISMA bosh release is compatible with the Ubuntu Jammy stemcell

## Acceptance Criteria

* [ ] Using a test manifest/deployment, we demonstrate the hardening bosh release compiles on Ubuntu Jammy
* [ ] Using a test deployment, verify that that the hardening scripts run successfully in a VM running on Ubuntu Jammy
* [ ] Update runtime config to include hardening bosh release as part of for Ubuntu Jammy VMs
  * [ ] If necessary, updated/change the manifest properties for release

--- 

## Security considerations

Verifying our compatibility with Ubuntu Jammy will help us stay up-to-date on security patches

## Resources

- hardening/FISMA bosh release: https://github.com/cloud-gov/cg-harden-boshrelease
- Example manifest for deploying a single release on Ubuntu Jammy (replace clamAV with release of choice): https://github.com/cloud-gov/cg-deploy-bosh/blob/89a0f7908462ee961cdf89d197d2027b1b208038/empty-vm.yml
- Example of adding ClamAV to runtime config for Jammy: https://github.com/cloud-gov/cg-deploy-bosh/pull/500

**Comment by markdboyd** [comment]
The current FISMA release compiled/deployed on Jammy and I saw this output in the `post-deploy-stdout.log` for the `harden` job in the deployed VM:

```
---> Finished hardening process
---> Updating AIDE db
```

So I think testing has confirmed that the FISMA release is working
