### ISSUE TITLE
[Jammy] Test, Verify, and Update secureproxy release 

### ISSUE THREAD

**Issue by soutenniza** [cloud-gov/product#2405]
In order to keep our system dependencies up to date and be ready for security patches, we want to verify that our secureproxy bosh release is compatible with the Ubuntu Jammy stemcell

## Acceptance Criteria

* [x] Using a test manifest/deployment, we demonstrate the secureproxy bosh release compiles on Ubuntu Jammy
* [x] Using a test deployment, verify that secureproxy runs successfully in a VM running on Ubuntu Jammy

--- 

## Security considerations

Verifying our compatibility with Ubuntu Jammy will help us stay up-to-date on security patches

## Instructions

https://gist.github.com/markdboyd/0e49641870a9792fd97e33a131a42c2c

## Resources

- secureproxy release: https://github.com/cloud-gov/cg-secureproxy-boshrelease
- Example manifest for deploying a single release on Ubuntu Jammy (replace clamAV with release of choice): https://github.com/cloud-gov/cg-deploy-bosh/blob/89a0f7908462ee961cdf89d197d2027b1b208038/empty-vm.yml
- Example of adding ClamAV to runtime config for Jammy: https://github.com/cloud-gov/cg-deploy-bosh/pull/500

**Comment by JasonTheMain** [comment]
looks like it might not be supported 
```This version of the BOSH Stemcell (jammy) is not supported!
  Distributor ID:	Ubuntu
  Description:	Ubuntu 22.04.1 LTS
  Release:	22.04
  Codename:	jammy
, Stderr: + echo 'Extracting pcre...'
++ mktemp -d
+ PCRE_TARGET=/var/vcap/data/tmp/tmp.2SAeiDDXMy
+ tar xzvf pcre-8.41.tar.gz -C /var/vcap/data/tmp/tmp.2SAeiDDXMy
+ echo 'Extracting nginx...'
++ mktemp -d
+ OPENRESTY_TARGET=/var/vcap/data/tmp/tmp.4dRmDFwNHV
+ tar xzvf openresty-1.13.6.2.tar.gz -C /var/vcap/data/tmp/tmp.4dRmDFwNHV
++ lsb_release -sc
+ codename=jammy
+ case "$codename" in
+ echo 'This version of the BOSH Stemcell (jammy) is not supported!'
+ lsb_release --all
+ sed -e 's/^/  /'
No LSB modules are available.```

**Comment by markdboyd** [comment]
Secureproxy is used in the following deployments in production:

```shell
root@PRODUCTION:/tmp/build/8e72821d$ bosh deployments --json | jq '.Tables[].Rows[] | select(.release_s | contains("secureproxy")) | .name'
"admin-ui"
"cf-production"
"logsearch-platform"
"shibboleth-production"
```

And in tooling:

```shell
root@Tooling:/tmp/build/8e72821d$ bosh deployments --json | jq '.Tables[].Rows[] | select(.release_s | contains("secureproxy")) | .name'
"opsuaa"
"prometheus-production"
"prometheus-staging"
```

And we can find the associated configuration files for those deployments using secureproxy:

- https://github.com/cloud-gov/cg-deploy-shibboleth/blob/d2c6607bbf10f9c0db8df7739c958f5b7ab2e8fc/bosh/manifest.yml#L7
- https://github.com/cloud-gov/cg-deploy-admin-ui/blob/fe9455f0db53b78023aad23494199915454ac870/bosh/manifest.yml#L7
- https://github.com/cloud-gov/cg-deploy-opslogin/blob/c95e7596960a1782981cc69e73188b339e767100/manifest.yml#L18
- https://github.com/cloud-gov/cg-deploy-logsearch/blob/dd3376ca5080b38fad2606203650d8ff11825ae6/logsearch-platform-deployment.yml#L21
- https://github.com/cloud-gov/cg-deploy-prometheus/blob/f71328600e37969fb4659f185e2d02439b4021a9/bosh/manifest.yml#L8

**Comment by markdboyd** [comment]
Secureproxy was updated for compatibility with Jammy: https://github.com/cloud-gov/cg-secureproxy-boshrelease/pull/67

Since the packaging script is written to run different steps depending on whether the stemcell is Bionic or Jammy, the same BOSH release should continue to function for both. Thus, we shouldn't need to update any of the deployments using Secureproxy (Prometheus, Shibboleth, etc). Once those deployments themselves are updated to use Ubuntu Jammy stemcells, they should be able package the Secureproxy BOSH release properly and everything should work. 

So there is no more work to do here and the ticket can be closed.
