### ISSUE TITLE
[Jammy] cflinuxsf4 - aws-broker

### ISSUE THREAD

**Issue by soutenniza** [cloud-gov/product#2409]
In order to migrate cflinuxsf4 stack (jammy), we want to test and verify that aws-broker works using the new stack

## Acceptance Criteria
* Confirm that aws-broker's buildpack supports cflinuxsf4
* Deploy aws-broker in development cf using stack cflinuxsf4
* Update application manifest to point to cflinuxsf4

--- 

## Security considerations
None

## Resources

- https://github.com/cloud-gov/aws-broker

## Implementation sketch

* [x] Update the AWS broker to use the cflinuxfs4 stack:
  * [x] In your custom branch, add `stack: cflinuxfs4` to https://github.com/cloud-gov/aws-broker/blob/master/manifest.yml
  * [x] In the credentials file for the pipeline, set the `aws-broker-branch-development` value to the name of your branch
  * [x] Re-fly the pipeline: `fly -t ci set-pipeline -p deploy-aws-broker -c ci/pipeline.yml -l path/to/credentials.yml`
  * [x] Run the dev deployment job if it doesn't run automatically
* [x] Run the dev smoke test jobs and confirm that they pass:
  * [x] acceptance-tests-db-development
  * [x] acceptance-tests-redis-development
  * [x] acceptance-tests-search-development

**Comment by dtamasang2** [comment]
All smoke tests ran successfully.
