### ISSUE TITLE
[Jammy] Concourse deployments 

### ISSUE THREAD

**Issue by soutenniza** [cloud-gov/product#2410]
In order to migrate to Jammy stemcells, we want to update our Concourse deployment to use Jammy

## Acceptance Criteria
* Concourse deployment is updated to use Jammy stemcell

--- 

## Security considerations
None

## Implementation sketch

- [x] Update Concourse deployment ops file to remove `bionic` instead of `xenial`: https://github.com/cloud-gov/cg-deploy-concourse/blob/5c22641092ef1c165b3d243c8f8b36a71f70cf92/operations/use-bionic.yml#L2-L3
- [x] Update default stemcell to Jammy: https://github.com/cloud-gov/cg-deploy-concourse/blob/5c22641092ef1c165b3d243c8f8b36a71f70cf92/operations/use-bionic.yml#L6-L11
- [x] Rename `operations/use-bionic.yml` to `operations/use-jammy.yml`
- [x] Update IAAS worker to use Jammy stemcell: https://github.com/cloud-gov/cg-deploy-concourse/blob/5c22641092ef1c165b3d243c8f8b36a71f70cf92/operations/iaas-worker.yml#L8
- [x] Update all references in pipelines from Bionic to Jammy
  - [x] https://github.com/cloud-gov/cg-deploy-concourse/blob/5c22641092ef1c165b3d243c8f8b36a71f70cf92/ci/pipeline.yml
  - [x] https://github.com/cloud-gov/cg-deploy-concourse/blob/5c22641092ef1c165b3d243c8f8b36a71f70cf92/ci/pipeline-development.yml#L15
- [x] Redeploy Concourse in staging: https://ci.fr.cloud.gov/teams/main/pipelines/deploy-concourse
- [x] Confirm whether Concourse is working by:
  - Viewing the bosh deployment VMs in the jumpbox and verifying that they are healthy
  - Visiting https://ci.fr-stage.cloud.gov/

**Comment by JasonTheMain** [comment]
Tested in staging. https://github.com/cloud-gov/cg-deploy-concourse/pull/195
once production is ran this ticket will be closed
