### ISSUE TITLE
[Jammy] Prometheus deployment

### ISSUE THREAD

**Issue by soutenniza** [cloud-gov/product#2413]
In order to migrate to Jammy stemcells, we want to update our Prometheus deployment to use Jammy

## Acceptance Criteria
* Prometheus deployment is updated to use Jammy stemcell

--- 

## Security considerations
None

## Implementation sketch

- [x] Update Prometheus deployment manifest to use Jammy: https://github.com/cloud-gov/cg-deploy-prometheus/blob/main/bosh/manifest.yml#L10-L13
- [x] Update Prometheus pipline to reference Jammy stemcells: https://github.com/cloud-gov/cg-deploy-prometheus/blob/main/ci/pipeline.yml
- [x] Redeploy Prometheus: https://ci.fr.cloud.gov/teams/main/pipelines/deploy-prometheus?group=deployment
- [x] Confirm whether Prometheus is working by visiting https://prometheus.fr-stage.cloud.gov/. If it is not working, you may need to debug using the logs in the BOSH deployment VMs

**Comment by markdboyd** [comment]
PR to update Prometheus deployment to Jammy was merged: https://github.com/cloud-gov/cg-deploy-prometheus/pull/187

Going to wait 24 hours to ensure Prometheus is stable on staging before deploying to production, but so far everything looks good

**Comment by markdboyd** [comment]
Prometheus deployed successfully to prod twice and everything looks healthy, so closing this ticket
