### ISSUE TITLE
[Jammy] Logsearch-platform deployments 

### ISSUE THREAD

**Issue by soutenniza** [cloud-gov/product#2414]
In order to migrate to Jammy stemcells, we want to update our Logsearch Platform deployment to use Jammy

## Acceptance Criteria
* Logsearch Platform deployment is updated to use Jammy stemcell

--- 

## Security considerations
None

## Implementation sketch

- [ ] Create PR to update Logsearch Platform development to use Jammy: https://github.com/cloud-gov/cg-deploy-logsearch/blob/7c45f5cf6175d2374eddc008e1d85e3b81b26998/logsearch-platform-development.yml#L57
- [ ] After successful deployment triggered by merging PR, manually trigger the deployment job again and make sure it passes: https://ci.fr.cloud.gov/teams/main/pipelines/deploy-logsearch/jobs/deploy-logsearch-platform-development
- [ ] Observe health of Logsearch platform development
  - Visit https://logs-platform.dev.us-gov-west-1.aws-us-gov.cloud.gov/. If it is not working, you may need to debug using the logs in the BOSH deployment VMs
  - Prometheus alerts
  - Grafana metrics (CPU, memory)
- [ ] **After 2 days of Logsearch platform development health**, create PR to update Logsearch Platform staging to use Jammy: https://github.com/cloud-gov/cg-deploy-logsearch/blob/7c45f5cf6175d2374eddc008e1d85e3b81b26998/logsearch-platform-staging.yml#L39
- [ ] After successful deployment triggered by merging PR, manually trigger the deployment job again and make sure it passes: https://ci.fr.cloud.gov/teams/main/pipelines/deploy-logsearch/jobs/deploy-logsearch-platform-staging
- [ ] Observe health of Logsearch platform staging
  - Visit https://logs-platform.fr-stage.cloud.gov/. If it is not working, you may need to debug using the logs in the BOSH deployment VMs
  - Prometheus alerts
  - Grafana metrics (CPU, memory)
- [ ] **After 2 days of Logsearch platform staging health**, create PR to update Logsearch Platform production to use Jammy: https://github.com/cloud-gov/cg-deploy-logsearch/blob/7c45f5cf6175d2374eddc008e1d85e3b81b26998/logsearch-platform-production.yml#L54
- [ ] Confirm health of Logsearch platform production
  - Visit https://logs-platform.fr.cloud.gov/. If it is not working, you may need to debug using the logs in the BOSH deployment VMs
  - Prometheus alerts
  - Grafana metrics (CPU, memory)
- [ ] After successful deployment triggered by merging PR, manually trigger the deployment job again and make sure it passes: https://ci.fr.cloud.gov/teams/main/pipelines/deploy-logsearch/jobs/deploy-logsearch-platform-production
- [ ] Update Logsearch Platform pipline to reference Jammy stemcells: https://github.com/cloud-gov/cg-deploy-logsearch/blob/7c45f5cf6175d2374eddc008e1d85e3b81b26998/ci/pipeline.yml#L1473

**Comment by markdboyd** [comment]
This is complete
