### ISSUE TITLE
[Jammy] Logsearch (Customer)  deployments 

### ISSUE THREAD

**Issue by soutenniza** [cloud-gov/product#2415]
In order to migrate to Jammy stemcells, we want to update our Logsearch customer deployment to use Jammy

## Acceptance Criteria
* Logsearch customer deployment is updated to use Jammy stemcell

--- 

## Security considerations
None

## Implementation sketch

- [ ] Create PR to update Logsearch customer development to use Jammy:  https://github.com/cloud-gov/cg-deploy-logsearch/blob/7c45f5cf6175d2374eddc008e1d85e3b81b26998/logsearch-development.yml#L98
- [ ] After successful deployment triggered by merging PR, manually trigger the deployment job again and make sure it passes: https://ci.fr.cloud.gov/teams/main/pipelines/deploy-logsearch/jobs/deploy-logsearch-development
- [ ] Observe health of Logsearch customer development
  - Visit https://logs.dev.us-gov-west-1.aws-us-gov.cloud.gov/. If it is not working, you may need to debug using the logs in the BOSH deployment VMs
  - Prometheus alerts
  - Grafana metrics (CPU, memory)
- [ ] **After 2 days of Logsearch customer development health**, create PR to update Logsearch customer staging to use Jammy: https://github.com/cloud-gov/cg-deploy-logsearch/blob/7c45f5cf6175d2374eddc008e1d85e3b81b26998/logsearch-staging.yml#L77
- [ ] After successful deployment triggered by merging PR, manually trigger the deployment job again and make sure it passes: https://ci.fr.cloud.gov/teams/main/pipelines/deploy-logsearch/jobs/deploy-logsearch-staging
- [ ] Observe health of Logsearch customer staging
  - Visit https://logs.fr-stage.cloud.gov/. If it is not working, you may need to debug using the logs in the BOSH deployment VMs
  - Prometheus alerts
  - Grafana metrics (CPU, memory)
- [ ] **After 1 week of Logsearch customer staging health**, create PR to update Logsearch customer production to use Jammy: https://github.com/cloud-gov/cg-deploy-logsearch/blob/7c45f5cf6175d2374eddc008e1d85e3b81b26998/logsearch-production.yml#L80
- [ ] Confirm health of Logsearch customer production
  - Visit https://logs.fr.cloud.gov/. If it is not working, you may need to debug using the logs in the BOSH deployment VMs
  - Prometheus alerts
  - Grafana metrics (CPU, memory)
- [ ] After successful deployment triggered by merging PR, manually trigger the deployment job again and make sure it passes: https://ci.fr.cloud.gov/teams/main/pipelines/deploy-logsearch/jobs/deploy-logsearch-production
- [ ] Update Logsearch customer pipline to reference Jammy stemcells: https://ci.fr.cloud.gov/teams/main/pipelines/deploy-logsearch/jobs/deploy-logsearch-development/builds/1073

**Comment by markdboyd** [comment]
This was deployed successfully to prod. Closing.
