### ISSUE TITLE
[Jammy] CF deployments 

### ISSUE THREAD

**Issue by soutenniza** [cloud-gov/product#2416]
In order to migrate to Jammy stemcells, we want to update our Cloudfoundry deployment to use Jammy

## Acceptance Criteria
* Cloudfoundry deployment is updated to use Jammy stemcell

--- 

## Security considerations
None

## Implementation sketch

- [ ] Create PR to update pipeline for CF development to remove opsfiles that are keeping us on Bionic stemcells: https://github.com/cloud-gov/cg-deploy-cf/blob/a74391adb947874fbb709eb997958eeca30627c6/ci/pipeline.yml#L41
- [ ] Deploy CF development: https://ci.fr.cloud.gov/teams/main/pipelines/deploy-cf/jobs/deploy-cf-development
- [ ] Observe health of CF development:
  - Request https://api.dev.us-gov-west-1.aws-us-gov.cloud.gov/ to verify Cloud Controller is working
  - Use the CF CLI to login to the dev environment and verify that you can:
    - Create an org
    - Create a space
    - Push an app
    - Add a user
    - Create a brokered database    
- [ ] **After a couple days of observing a healthy status for CF staging**, create PR to update pipeline for CF staging to remove opsfiles that are keeping us on Bionic stemcells: https://github.com/cloud-gov/cg-deploy-cf/blob/a74391adb947874fbb709eb997958eeca30627c6/ci/pipeline.yml#L535
- [ ] Deploy CF staging: https://ci.fr.cloud.gov/teams/main/pipelines/deploy-cf/jobs/deploy-cf-staging
- [ ] Observe health of CF staging
  - Request https://api.fr-stage.cloud.gov/ to verify Cloud Controller is working
  - Use the CF CLI to login to the staging environment and verify that you can:
    - Create an org
    - Create a space
    - Push an app
    - Add a user
    - Create a brokered database    
- [ ] **After a week of observing a healthy status for CF staging**: 
  - [ ] Create PR to update pipeline for CF prod to remove opsfiles that are keeping us on Bionic stemcells: https://github.com/cloud-gov/cg-deploy-cf/blob/a74391adb947874fbb709eb997958eeca30627c6/ci/pipeline.yml#L1040
  - [ ] Deploy changes to CF prod: https://ci.fr.cloud.gov/teams/main/pipelines/deploy-cf/jobs/deploy-cf-production
- [ ] Confirm whether CF prod is working by:
  - Request https://api.fr.cloud.gov/ to verify Cloud Controller is working
  - Use the CF CLI to login to the staging environment and verify that you can:
    - Create an org
    - Create a space
    - Push an app
    - Add a user
    - Create a brokered database

**Comment by markdboyd** [comment]
This is deployed in production
