### ISSUE TITLE
Ship v2.1 of SSP

### ISSUE THREAD

**Issue by pburkholder** [cloud-gov/product#2421]
Download from Google, open in Word, clean up table, etc.

Save as PDF, Docusign it. We ship SSPs as PDFs so they're more or less immutable

Save as DOCX, upload back to Google Drive as the 'indev' version.

## Acceptance Criteria

* SSP has been Docusigned by:
  * [x] ISSO
  * [x] System Owner
  * [x] Product Lead or Biz Lead or Eng Supervisor
* Signed SSP delivered to
  * [x] Max
  * [x] Google Drive Archive folder
* SSP update notification (with highlights) emailed to
  * [x] cloud-gov-team
  * [x] JAB TRRs
* [x] Google Drive updated with latest .docx
  

## Security Considerations

Safe. The existence of this issue provides no useful public info to a malicious actor. Regularly 
update our SSP is good for compliance & security

**Comment by Chiakao** [comment]
Signed SSP uploaded to Max.gov and Google drive. JAB and CG Team have been notified.
