### ISSUE TITLE
Update runbook for how to swap in a restored DB as the active CCDB

### ISSUE THREAD

**Issue by pburkholder** [cloud-gov/product#2425]
In order to enable fast recovery if we have to recover from a failed/lost/corrupted CCDB, we should write a runbook based on our experience in Quartery Backup-Restore Exercise.

## Acceptance Criteria
* [x] Runbook PR to internal-docs is merged.

--- 

## Security considerations
More Docs. Safe

**Comment by dtamasang2** [comment]
I have performed an in-depth review of the existing document on the backup and restore process for CCDB RDS databases. The document details the steps we took with the exception that it uses a faster method of restoring the database by updating the manifest via a jump box. This was the preferred method Van mentioned we use for a faster backup/restore.

https://github.com/cloud-gov/internal-docs/blob/main/docs/runbooks/Platform/cg-db-restore.md
