### ISSUE TITLE
[Jammy] Test, verify, and update node-exporter release

### ISSUE THREAD

**Issue by markdboyd** [cloud-gov/product#2427]
In order to keep our system dependencies up to date and be ready for security patches, we want to verify that our node-exporter bosh release is compatible with the Ubuntu Jammy stemcell

## Acceptance Criteria

* [x] Using a test manifest/deployment, we demonstrate the node-exporter  bosh release compiles on Ubuntu Jammy
* [x] Using a test deployment, verify that node-exporter runs successfully in a VM running on Ubuntu Jammy
* [ ] Update runtime config to include node-exporter  bosh release as part of for Ubuntu Jammy VMs
  * [ ] If necessary, updated/change the manifest properties for release

--- 

## Security considerations

Verifying our compatibility with Ubuntu Jammy will help us stay up-to-date on security patches

## Resources

- node-exporter release:  https://github.com/cloudfoundry-community/node-exporter-boshrelease
- Ticket for testing node-exporter with Bionic: https://github.com/cloud-gov/product/issues/1580
- Example manifest for deploying a single release on Ubuntu Jammy (replace clamAV with release of choice): https://github.com/cloud-gov/cg-deploy-bosh/blob/89a0f7908462ee961cdf89d197d2027b1b208038/empty-vm.yml
- Example of adding ClamAV to runtime config for Jammy: https://github.com/cloud-gov/cg-deploy-bosh/pull/500

**Comment by jameshochadel** [comment]
`node-exporter` outputs no errors in the logs and `monit summary all` shows it is up.
