### ISSUE TITLE
Write a post about build time improvements

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/product#2430]
Create a write up on the improved site build times with the added implementation over the past ~6 months.

## Acceptance Criteria

- [x] Create and publish a write up for the cloud.gov news posts
- [ ] Publish the write up in the monthly newsletter
- [x] Add 📉

**Comment by drewbo** [comment]
Draft post here for review: https://docs.google.com/document/d/1C1HttSP8QOnPbbobBh7eX7tUcmwKpq59zCT3Q6GGWVI/edit#

**Comment by apburnes** [comment]
@drewbo Looks great to me. Added a comment about expanding some estimates.

**Comment by apburnes** [comment]
I'll move this into the current sprint.

**Comment by drewbo** [comment]
Preview is up, waiting on a few approvals
