### ISSUE TITLE
[Jammy] cflinuxsf4 - external-domain-broker & workers

### ISSUE THREAD

**Issue by markdboyd** [cloud-gov/product#2435]
In order to migrate cflinuxsf4 stack (jammy), we want to test and verify that external-domain-broker works using the new stack

## Acceptance Criteria

* Confirm that external-domain-broker's buildpack supports cflinuxsf4
* Deploy external-domain-broker in development cf using stack cflinuxsf4
* Update application manifest to point to cflinuxsf4

--- 

## Security considerations
None

## Resources

https://github.com/cloud-gov/external-domain-broker
https://ci.fr.cloud.gov/teams/main/pipelines/external-domain-broker

## Implementation sketch

* [x] Update broker deployment in dev to use cflinuxfs4
  * [x] In a custom branch, add `stack: cflinuxfs4` to the manifests for the app and workers
    * [x] https://github.com/cloud-gov/external-domain-broker/blob/main/manifests/app.yml
    * [x] https://github.com/cloud-gov/external-domain-broker/blob/main/manifests/workers.yml
  * [x] Update the pipeline to use a custom source for the dev deployment with your custom branch: https://github.com/cloud-gov/external-domain-broker/blob/main/ci/pipeline.yml#L250
  * [x] Update the pipeline to add a new `dev-acceptance-tests` job that runs after the `dev` deployment by copying the `staging-acceptance-tests`: https://github.com/cloud-gov/external-domain-broker/blob/main/ci/pipeline.yml#L387-L438
  * [x] Run the `dev` job
* [x] Confirm that broker still works from the output of the  `dev-acceptance-tests` job
* [x] Confirm that the workers are running by viewing the log output for the app in the dashboard or CLI

**Comment by rcgottlieb** [comment]
I have verified that the external-domain-broker & workers works on cflinuxfs4
