### ISSUE TITLE
Remediate a11y issues on cloud.gov website using AMP

### ISSUE THREAD

**Issue by hursey013** [cloud-gov/product#2436]
# What we're after
Based on a recent run of the Accessibility Management Platform (AMP) tool by the Digital Council, cloud.gov is shown to have a score of 83% compliance: https://docs.google.com/spreadsheets/d/1sp6I7ApvNBiYlpy2ZotdCtuH9LojdR4Z-xSjoYrz29o/edit#gid=1103782849. The goal is to improve the overall score of cloud.gov.

## Hypothesized benefit(s)/why:
* Compliance
* Best practice

## Potential metrics
* An AMP score > 83%

---
### Further context for those unfamiliar with what we're doing

Slack thread for reference: https://gsa-tts.slack.com/archives/GNSL334HM/p1676314063967809
AMP: https://insite.gsa.gov/employee-resources/information-technology/508-accessibility/accessibility-management-platform-amp?term=

### Security considerations
None

**Comment by hursey013** [comment]
@drewbo and I have both requested access to AMP.

**Comment by svenaas** [comment]
I've requested an AMP account as well.

**Comment by hursey013** [comment]
> I've requested an AMP account as well.

Probably a good idea to start preemptively lowering your expectations of the tool 😦

**Comment by svenaas** [comment]
Oh boy, oh boy.

**Comment by apburnes** [comment]
Good to go!
