### ISSUE TITLE
[Jammy] cflinuxsf4 - allstar

### ISSUE THREAD

**Issue by markdboyd** [cloud-gov/product#2437]
In order to migrate cflinuxsf4 stack (jammy), we want to test and verify that allstar works using the new stack

## Acceptance Criteria

* Confirm that allstar's buildpack supports cflinuxsf4
* Deploy allstar in development cf using stack cflinuxsf4
* Update application manifest to point to cflinuxsf4

--- 

## Security considerations
None

## Resources

https://github.com/cloud-gov/cg-deploy-allstar
https://ci.fr.cloud.gov/teams/main/pipelines/deploy-allstar

## Implementation sketch

* [x] Update broker deployment in dev to use cflinuxfs4
  * [x] In a custom branch, add `stack: cflinuxfs4` to the manifest: https://github.com/cloud-gov/cg-deploy-allstar/blob/main/manifest.yml
  * [x] Update the pipeline to use a custom source for the dev deployment with your custom branch: https://github.com/cloud-gov/cg-deploy-allstar/blob/main/ci/pipeline.yml
  * [x] Update the pipeline with a deployment to the dev environment, copying the job for deploying to prod: https://github.com/cloud-gov/cg-deploy-allstar/blob/main/ci/pipeline.yml
  * [x] Run the development deployment job
* [x] Confirm that allstar still works by viewing its logs: `cf target -o cloud-gov -s services && cf logs allstar --recent`

**Comment by rcgottlieb** [comment]
I verified the cflinuxfs4 does work with deploy-allstar
