### ISSUE TITLE
[Jammy] cflinuxsf4 - external-domain-broker-migrator

### ISSUE THREAD

**Issue by markdboyd** [cloud-gov/product#2438]
In order to migrate cflinuxsf4 stack (jammy), we want to test and verify that external-domain-broker-migrator works using the new stack

## Acceptance Criteria

* Confirm that external-domain-broker-migrator's buildpack supports cflinuxsf4
* Deploy external-domain-broker-migrator in development cf using stack cflinuxsf4
* Update application manifest to point to cflinuxsf4

--- 

## Security considerations
None

## Resources

https://github.com/cloud-gov/external-domain-broker-migrator
https://ci.fr.cloud.gov/teams/main/pipelines/external-domain-broker-migrator

## Implementation sketch

* [x] Update broker deployment in dev to use cflinuxfs4
  * [x] In a custom branch, add `stack: cflinuxfs4` to the manifest: https://github.com/cloud-gov/external-domain-broker-migrator/blob/main/manifest.yml
  * [x] Update the pipeline to use a custom source for the dev deployment with your custom branch: https://github.com/cloud-gov/external-domain-broker-migrator/blob/main/ci/pipeline.yml
  * [x] Run the `dev` job
* [x] Confirm that the app still works by  viewing the log output for the app in the dashboard or CLI

**Comment by rcgottlieb** [comment]
This deployment works as is with cflinuxfs4
