### ISSUE TITLE
[Jammy] cflinuxsf4 - diagrams

### ISSUE THREAD

**Issue by markdboyd** [cloud-gov/product#2441]
In order to migrate cflinuxsf4 stack (jammy), we want to test and verify that diagrams works using the new stack

## Acceptance Criteria

* Confirm that diagrams's buildpack supports cflinuxsf4
* Deploy diagrams in development cf using stack cflinuxsf4
* Update application manifest to point to cflinuxsf4

--- 

## Security considerations
None

## Resources

https://github.com/cloud-gov/cg-diagrams
https://ci.fr.cloud.gov/teams/main/pipelines/deploy-diagrams

## Implementation sketch

* [x] Update broker deployment in dev to use cflinuxfs4
  * [x] In a custom branch, add `stack: cflinuxfs4` to the manifest: https://github.com/cloud-gov/diagrams/blob/main/manifest.yml
  * [x] Update the pipeline to use your custom branch for deploying to prod: https://github.com/cloud-gov/diagrams/blob/main/ci/pipeline.yml. For this application, it's just diagrams and not customer-facing functionality, so we're not worried about breaking it in testing
  * [x] Run the `deploy-production` job if it doesn't run automatically
* [x] Confirm that the app still works by visiting https://diagrams.fr.cloud.gov

**Comment by rcgottlieb** [comment]
I verified the cflinuxfs4 does work with diagrams
