### ISSUE TITLE
[Jammy] cflinuxfs4 - uaa-extras

### ISSUE THREAD

**Issue by markdboyd** [cloud-gov/product#2442]
In order to migrate cflinuxsf4 stack (jammy), we want to test and verify that uaa-extras works using the new stack

## Acceptance Criteria

* Confirm that uaa-extras's buildpack supports cflinuxsf4
* Deploy uaa-extras in development cf using stack cflinuxsf4
* Update application manifest to point to cflinuxsf4

--- 

## Security considerations
None

## Resources

https://github.com/cloud-gov/cg-uaa-extras
https://ci.fr.cloud.gov/teams/main/pipelines/deploy-uaa-extras

## Implementation sketch

* [x] Update app deployment in dev to use cflinuxfs4
  * [x] In a custom branch, update manifest to include `stack: cflinuxfs4`: https://github.com/cloud-gov/cg-uaa-extras/blob/main/manifest_uaaextra.yml#L6
  * [x] Update the pipeline to use your custom branch for deploying to dev: https://github.com/cloud-gov/cg-uaa-extras/blob/main/ci/pipeline.yml.
  * [x] Run the `deploy-development` job if it doesn't run automatically
* [x] Confirm that the app still works by visiting https://account.dev.us-gov-west-1.aws-us-gov.cloud.gov/ and testing out the functionality
  - [x] Invite user functionality still works
* [x] If testing is successful, update the production manifest to include `stack: cflinuxfs4`: https://github.com/cloud-gov/cg-uaa-extras/blob/main/manifest_production_fr_uaaextra.yml

**Comment by rcgottlieb** [comment]
I verified the cflinuxfs4 does work with uaaextras.
