### ISSUE TITLE
[Jammy] cflinuxfs4 - legacy-domain-certificate-renewer

### ISSUE THREAD

**Issue by markdboyd** [cloud-gov/product#2445]
In order to migrate cflinuxsf4 stack (jammy), we want to test and verify that legacy-domain-certificate-renewer works using the new stack

## Acceptance Criteria

* Confirm that legacy-domain-certificate-renewer's buildpack supports cflinuxsf4
* Deploy legacy-domain-certificate-renewer in development cf using stack cflinuxsf4
* Update application manifest to point to cflinuxsf4

--- 

## Security considerations
None

## Resources

https://github.com/cloud-gov/legacy-domain-certificate-renewer
https://ci.fr.cloud.gov/teams/main/pipelines/legacy-domain-certificate-renewer

## Implementation sketch

* [x] Update app deployment in dev to use cflinuxfs4
  * [x] In a custom branch, update manifests to include `stack: cflinuxfs4`:
    - [x] https://github.com/cloud-gov/legacy-domain-certificate-renewer/blob/main/manifests/renewer.yml
    - [x] https://github.com/cloud-gov/legacy-domain-certificate-renewer/blob/main/manifests/upgrade-schema.yml
  * [x] Update the pipeline to use your custom branch for deploying to dev: https://github.com/cloud-gov/legacy-domain-certificate-renewer/blob/main/ci/pipeline.yml
  * [x] Run the `dev` job if it doesn't run automatically
* [x] Confirm that the app still works by going to the dashboard or using the CLI to view the application logs

**Comment by dandersonsw** [comment]
Note: For the upgrade-schema task to use cflinuxfs4 you need to set `-s cflinuxfs4` in the cf push command called by the update-schema.sh script.
