### ISSUE TITLE
[Jammy] Postfix deployment

### ISSUE THREAD

**Issue by markdboyd** [cloud-gov/product#2457]
In order to migrate to Jammy stemcells, we want to update our Postfix deployment to use Jammy

## Acceptance Criteria
* Postfix deployment is updated to use Jammy stemcell

--- 

## Security considerations
None

## Implementation sketch

- [x] Update Postfix deployment manifest to use Jammy: https://github.com/cloud-gov/cg-deploy-postfix/blob/master/bosh/manifest.yml#L14-L17
- [x] Update Postfix pipline to reference Jammy stemcells: https://github.com/cloud-gov/cg-deploy-postfix/blob/master/ci/pipeline.yml
- [x] Redeploy Postfix: https://ci.fr.cloud.gov/teams/main/pipelines/deploy-postfix
- [x] Confirm whether Postfix is working by running the smoke-tests production job: https://ci.fr.cloud.gov/teams/main/pipelines/deploy-postfix/jobs/smoke-tests-production/builds/225901

**Comment by JasonTheMain** [comment]
Seems to be working and using jammy
