### ISSUE TITLE
[Jammy] cflinuxfs4 - java-hello-worlds

### ISSUE THREAD

**Issue by JasonTheMain** [cloud-gov/product#2460]
In order to migrate cflinuxsf4 stack (jammy), we want to test and verify that the hello-world apps work using the new stack
## Acceptance Criteria

* Confirm that hello-world app buildpacks support cflinuxsf4
* Deploy hello-world apps in development cf using stack cflinuxsf4
* Update application manifests to point to cflinuxsf4

--- 

## Security considerations
None

## Resources

https://github.com/cloud-gov/cf-hello-worlds
https://ci.fr.cloud.gov/teams/main/pipelines/test-hello-worlds

## Implementation sketch

* [ ] Update app manifests in dev to use cflinuxfs4
  * [ ] In a custom branch, update manifests to include `stack: cflinuxfs4`
    - [ ] https://github.com/cloud-gov/cf-hello-worlds/blob/main/java-see/manifest.yml
  * [] Update the pipeline to use your custom branch for deploying: https://github.com/cloud-gov/cf-hello-worlds/blob/main/pipeline.yml
    - In this case these apps are only deployed to prod and they are demo apps that aren't used by anyone so it doesn't matter if we break them
  * [] Run the deploy jobs if they don't run automatically
* [ ] Confirm that the apps still work:
  - [ ] https://test-java.app.cloud.gov/

**Comment by JasonTheMain** [comment]
https://github.com/cloudfoundry/java-buildpack/issues/960
Java buildpack is blocking this ticket

**Comment by JasonTheMain** [comment]
fixed in latest buildpack

**Comment by soutenniza** [comment]
Removed java buildpack from manifest and it autodetects right buildpack. The hello world is green on concourse now
