### ISSUE TITLE
Reconcile cloud.gov CIS and CRM

### ISSUE THREAD

**Issue by Chiakao** [cloud-gov/product#2461]
In order to have an accurate and well documented CIS and CRM that our customers can leverage, we will reconcile both documents and resolve any differences. 

## Acceptance Criteria
* [ ] Updated CIS
* [ ] Updated CRM

--- 

## Security considerations
Updating our security documentation

## Implementation sketch
* [ ] Review CIS/CRM Recon: https://docs.google.com/spreadsheets/d/12WUnPTxtmZqaV42YFu3SjTU0Vct9FpHaFgx2Tnd8lUQ/edit#gid=1046768333
* [ ] Update documentation

**Comment by pburkholder** [comment]
I'm moving this into doing since we also need to push out a formatting correct to the CRM.

**Comment by Chiakao** [comment]
We noted this as a "won't do" due to competing priorities. If our customers need this information, we will reprioritize.
