### ISSUE TITLE
Price and launch new ElasticSearch plan

### ISSUE THREAD

**Issue by jameshochadel** [cloud-gov/product#2463]
During https://github.com/cloud-gov/private/issues/636, we manually scaled up an ElasticSearch cluster to use larger nodes in the AWS console. We have previously identified the need to have built-in support for a larger plan type provided to customers. 

Acceptance criteria: A new ElasticSearch plan is available in the marketplace and priced appropriately for its cost to us.

* [x] How do we make a pricing change on the business/organization side? 
* [x] What do we charge for the cluster? It should be consistent with the charges for smaller clusters and cover our costs.
* [x] Create the new plan in the broker and publish it
* [x] Verify that users can upgrade ES plans in the broker

**Comment by jameshochadel** [comment]
Per [this slack conversation](https://gsa-tts.slack.com/archives/GNSL334HM/p1678990559725399), we'll do this relatively soon.

**Comment by jameshochadel** [comment]
After a conversation with the customer, we have tentatively agreed to create a new plan using `m6i.2xlarge` nodes. We may also price a cluster based on `m6i.4xlarge` nodes so it is available in case a quick upgrade is needed in the future. We think the memory-optimized instance types will be a good fit for Elasticsearch workloads.

**Comment by jameshochadel** [comment]
PR here: https://github.com/cloud-gov/aws-broker/pull/297

To the above, these are general-purpose instance types, and in the m5 family, since m6i [isn't available](https://aws.amazon.com/opensearch-service/pricing/), at least in GovCloud.

**Comment by jameshochadel** [comment]
Current problem: I've merged and deployed the change, but I still don't see it in the marketplace.

**Comment by markdboyd** [comment]
Plans aren't enabled in prod because the pipeline wasn't re-flown with the changes to enabled the plans. I've enabled the plans and I'll run the jobs to deploy the plans now

**Comment by markdboyd** [comment]
Need to fix Go version for aws-broker so I can deploy these changes through to prod: https://github.com/cloud-gov/aws-broker/pull/304

**Comment by markdboyd** [comment]
The new plans are now available in prod, which you can see if you run `cf marketplace -e aws-elasticsearch`
