### ISSUE TITLE
Support Assurance Team in responding to SAR findings (Due: 2023-03-27)

### ISSUE THREAD

**Issue by pburkholder** [cloud-gov/product#2465]
In order to properly schedule and plan our assurance work, Assurance and Platform should work together to 
write up our remediation plan, and do a rough estimation of the work and resources needed.

We'll need this before the technical meeting with the JAB TRRs sometime the week of March 27-31.

--

## Security considerations
This is security and compliance critical work

**Comment by markdboyd** [comment]
We met with compliance team on Wednesday, 3/29 to review the SAR findings and discuss remediation
