### ISSUE TITLE
The harden-concourse-tasks in repo cg-deploy-concourse-docker-image has an incorrect version of golang

### ISSUE THREAD

**Issue by rcgottlieb** [cloud-gov/product#2473]
Stratos/Dashboard requires Golang 1.18+ Currently the version of golfing in the harden-concourse-tasks task is set to golang 1.8

## Acceptance Criteria
The script harden-concourse-tasks/scripts/build.sh:156 modified to use the most current version of golang

--- 

## Security considerations
This will bring the golang version up to the most current which will cover many vulnerabilities 

## Implementation sketch

- [ ] Update https://github.com/cloud-gov/cg-deploy-concourse-docker-image/blob/main/task/harden-concourse-tasks/scripts/build.sh#L155 to change the version to 1.20.2 either by using the this link: [go1.20.2.linux-amd64.tar.gz](https://go.dev/dl/go1.20.2.linux-amd64.tar.gz)
- [ ] Test the task using the test.sh script to verify nothing breaks

**Comment by dandersonsw** [comment]
Closing this as we now use the general-task image and we are up to date with golang
