### ISSUE TITLE
Create a role for Pages operators to access ECR

### ISSUE THREAD

**Issue by drewbo** [cloud-gov/product#2476]
In order to debug and scan hardened containers, Pages operators want access to ECR

## Acceptance Criteria
* [ ] A new AWS role is created
* [ ] Access is granted to @cloud-gov/pages-ops 

--- 

## Security considerations
This is an expansion of an access control but very limited in scope

## Implementation sketch
TODO

**Comment by markdboyd** [comment]
Handled by https://github.com/cloud-gov/aws-admin/pull/84
