### ISSUE TITLE
(Jammy) Update domain-broker deployment

### ISSUE THREAD

**Issue by markdboyd** [cloud-gov/product#2484]
In order to migrate to Jammy stemcells, we want to update our domain-broker deployment to use Jammy

## Acceptance Criteria
* domain-broker deployment is updated to use Jammy stemcell

--- 

## Security considerations
None

## Implementation sketch

- [x] Pause staging and prod deployments: https://ci.fr.cloud.gov/teams/main/pipelines/deploy-domains-broker
- [x] Update domain-broker deployment manifest to use Jammy: https://github.com/cloud-gov/cf-domain-broker-alb/blob/6bb65d9da29d120e0a6740ad30de1e9e82fef9c4/bosh/manifest.yml#L8
- [x] Update domain-broker pipline to reference Jammy stemcells: https://github.com/cloud-gov/cf-domain-broker-alb/blob/6bb65d9da29d120e0a6740ad30de1e9e82fef9c4/ci/pipeline.yml#L19
- [x] Update the domain-broker deployment manifest to point to Jammy
- [x] Redeploy domain-broker in development: https://ci.fr.cloud.gov/teams/main/pipelines/deploy-domains-broker/jobs/deploy-development
- [x] Confirm whether domain-broker is working by going to the development jumpbox and verifying the health of the VMs. SSH into the VMs and inspect the process health with monit
- [x] If everything is healthy, unpause and deploy to staging
- [x] Confirm whether domain-broker is working by going to the staging jumpbox and verifying the health of the VMs. SSH into the VMs and inspect the process health with monit
- [x] If everything is healthy, unpause and deploy to production

**Comment by dtamasang2** [comment]
Domain-broker has been updated to use Jammy and deployed without issues.
