### ISSUE TITLE
Hub to spoke port mapping

### ISSUE THREAD

**Issue by cweibel** [cloud-gov/product#2500]
## Background

In order to reduce the number of open ports in security groups, we need to create a map of the ports which need to be opened between the hub (tooling) and environments (spokes, such as development, staging and production).  These will then be enforced during subsequent tickets where security groups are defined

Note:  We will likely not be perfect on the first attempt, this is ok, however the diagram/documentation will need to be updated if holes are found.

## Acceptance Criteria
* [ ] A diagram of all the components in the hubs and spokes and the ports which are needed is created

--- 

## Security considerations
This will help to harden the firewall rules of ports allowed in/out of the security groups used by each environment

## Implementation sketch
* [ ] Generate a diagram and document the ports which need to be opened
* [x] Use the existing deployments of tooling and production to identify components and ports used
* [ ] The platform team reviews the diagram looking for anything overlooked

**Comment by markdboyd** [comment]
Closed with https://github.com/cloud-gov/internal-docs/pull/114
