### ISSUE TITLE
Update documentation for contingency situations

### ISSUE THREAD

**Issue by pburkholder** [cloud-gov/product#2511]
In order to hold an effective contingency plan rehearsal, we need enough documentation and updated runbooks for the team to not waste too much time.

The assigned engineers should also review the current docs in internal-docs to add some hints on

* How to recover from a lost BOSH director
* How to scale up in a single AZ

## Acceptance Criteria

 - [ ]  PRs accepted to internal-docs

## Security considerations

Required for authorization and also a good idea

**Comment by pburkholder** [comment]
@ChrisMcGowan Is this on track to be ready for the CP exercise on the 25th?

**Comment by ChrisMcGowan** [comment]
Yes @pburkholder it will be.
