### ISSUE TITLE
Investigate how dns for urls for environments will be migrated for hubs and spokes

### ISSUE THREAD

**Issue by cweibel** [cloud-gov/product#2523]
In order to create the new hub and spoke environments, we need to decide how the existing stating, development and tooling urls will be mapped for DNS

## Acceptance Criteria
* [ ] GIVEN that we are migrating to new hubs and spokes for the existing dev, staging and tooling environments, we need to decide whether the existing urls will be reused or new ones (and what those values will be) are defined

--- 

## Security considerations
This is part of the effort to split hub and spokes accounts and will increase isolation of resources

## Implementation sketch
* [ ] For development, there are references such as https://github.com/cloud-gov/cg-provision/blob/main/ci/pipeline.yml#L516-L517 and https://github.com/cloud-gov/cg-provision/blob/main/ci/pipeline.yml#L521-L523 which need to be decided to reuse the urls or use new urls for dns purposes
* [ ] Repeat the exercise for staging and tooling
* [ ] If changing, create a spreadsheet of the old to new mappings

**Comment by ChrisMcGowan** [comment]
Had a good talk with Taylor@AWS on options here and i'll write up a formal doc but in short form using tooling -> hub as example:

- In our current account create a new subdomain under fr.cloud.gov - call it hub.fr.cloud.gov 
- In our existing TF code that creates/manages DNS entries - duplicate the A record to include this new zone
- When cutover happens - on the OG prod zone, remove the old A records from the sub zone and instead update the sub zone NS records to point to the NS servers for the zone in the new account

The one item that still needs review is for items in hub/tooling that use route-registrar to leverage wildcard routing using the production platform - probs going to have to move those resources off that release and onto a LB with DNS record instead even if those tools/releases are single host

**Comment by ChrisMcGowan** [comment]
Working doc: https://docs.google.com/document/d/1uD2kqSt2Aw1UGl1RYCWLlIlXaeGqon76hTIJm7jyBz0/edit?usp=sharing
