### ISSUE TITLE
Review, assign and schedule artifact gathering

### ISSUE THREAD

**Issue by banessamoradi** [cloud-gov/product#2536]
**Description:**

- Review the Container Scanning SCR Smartsheet for level of effort
- Verify line items are reasonable and we know what question is being answered
- 

**Acceptance Criteria:**

- [ ] Comments are filled out for the line items that require further attention/revision

**Comment by rcgottlieb** [comment]
I filled out the line items with some places that we would get some of the artifacts as a reminder for when we actually gather them. There wasn't anything more of significance found other than what @pburkholder and I found last week. 

I'm going to close this as done. We should probably call this review and drop assign and schedule as we are already doing that with our meeting last week.
