### ISSUE TITLE
Document procedure for hardening 3rd party containers

### ISSUE THREAD

**Issue by banessamoradi** [cloud-gov/product#2537]
In order to meet container scanning criteria, we want to have documentation on how to harden 3rd party containers

## Acceptance Criteria
* [x] Documentation is available on hardening 3rd party containers
--- 

## Security considerations
None

## Implementation sketch
We need to consider how we handle Ubuntu and non-Ubuntu based images
* [x] Create documentation outlining our process for hardening a 3rd party container

**Comment by banesssa** [comment]
Read FEDRAMP container requirement and see what is required (decide where to place them)
