### ISSUE TITLE
Demonstrate gating an image on CIS audit failure

### ISSUE THREAD

**Issue by banessamoradi** [cloud-gov/product#2539]
In order to meet container scanning criteria, we want to demonstrate removing an image from the ECR if it fails a CIS audit.

## Acceptance Criteria
* [x] If an image fails a CIS audit, ~it is removed from ECR~ it is not promoted to `production` 
* [x] An image CIS failure in staging triggers an "alert" for review 
--- 

## Security considerations
Removing the image from the ECR will improve security by not allowing use of an image that isn't properly hardened.

## Implementation sketch
* [x] Update code to disallow the promotion of images from staging to production if they fail the CIS Audit
* [x] Upon failure of CIS Audit an alert is sent out via Slack and Email with the offending image and resulting scans

**Comment by pburkholder** [comment]
@pburkholder or @Chiakao should confirm requirements here, we may not need to re-do compliance scans for images in 'prod' since compliance doesn't age out (until there's a new OS).

**Comment by jameshochadel** [comment]
Summary of progress so far:

* Script to audit hardened containers is here: https://github.com/cloud-gov/container-scanning/blob/audit-gating/ci/audit-ecr-container.sh (note the topic branch)
* That bash script calls this python script: https://github.com/cloud-gov/container-scanning/blob/audit-gating/ci/parse_cis_audit_html.py

Items to do:

* Possibly modify script to change printing failure to exit 1 or similar
* Gate image promotion based on script results
* Alert on audit failure

**Comment by dandersonsw** [comment]
Rather than using python or grype, maybe xmllint is the way to go?

`xmllint --xpath "//*[name()='score']/text()"` Would get us the score value from the xml file.

This does require us to install xmllint on the image

**Comment by dandersonsw** [comment]
Created a ticker for deleting files after running `usg` tasks to a separate ticket: https://github.com/cloud-gov/product/issues/2596 since this doesn't actually apply until we are running the audit script before creating the image.
