### ISSUE TITLE
Demonstrate gating an image on late CVE

### ISSUE THREAD

**Issue by banessamoradi** [cloud-gov/product#2540]
In order to meet container scanning criteria, we want to demonstrate gating an image so that it cannot move from the staging ECR to the production ECR repo if it has CVEs that are late in being resolved

## Acceptance Criteria
* [x] Given a late CVE, the image is not promoted to the production ECR repo
--- 

## Security considerations
Gating the image will help us meet container scanning criteria where images must have a clean scan to be promoted and used in production

## Implementation sketch
A CVE is considered late at 15 days for a Critical CVE, and 30 days for a High CVE
* [x] Update code to have a condition which gates images from staging to production on past due CVEs

**Comment by dandersonsw** [comment]
Updated this ticket to better reflect the work
