### ISSUE TITLE
Remove ECR images on failing CVE check

### ISSUE THREAD

**Issue by dandersonsw** [cloud-gov/product#2554]
In order to meet container scanning requirements, we want to scan our images at least once every 30 days, and remove any images that have past due CVEs. (With some grace period so we don't break pipelines immediately.)

## Acceptance Criteria
* [ ] GIVEN an image fails the CVE check, send an alert that the image is going to be deleted in X amount of days. (Look at FedRAMP guidance to figure out value of X)
* [ ] THEN automatically delete the image once it's reached the time limit

--- 

## Security considerations
[note any potential changes to security boundaries, practices, documentation, risk that arise directly from this story]

## Implementation sketch

* [ ] Modify code to track failed scans for images
* [ ] Add code to delete the image
* [ ] Notify team via Slack of failing scans

**Comment by jameshochadel** [comment]
Implementation ideas:

* File in CredHub that tracks image and last failed scan date, then after N days not fixed, delete the image
* Use Defect Dojo API (if it exists) to get scan history for an image, then after N days not fixed, delete the image

Maybe see if the image is `latest` or older; if not `latest` we can delete it sooner.

**Comment by banesssa** [comment]
Vulnerability requirements do not require that we delete images when they have a CVE. Instead we will track the vulnerabilities & come up with the plan to close them in a timely fashion.
See @jameshochadel
