### ISSUE TITLE
Upgrade Sonarqube to 10.1

### ISSUE THREAD

**Issue by Ephraim-G** [cloud-gov/product#2558]
The current version of Sonarqube is reaching EOL. Upgrade to version 10.1 which was releaded 6/20/2023. [Full Release Notes ](https://sonarsource.atlassian.net/browse/SONAR-18182?jql=project%20%3D%2010139%20AND%20fixVersion%20%3D%2013931)

## Acceptance Criteria
* [x] Stop and remove the existing SonarQube container (a restart from the UI is not enough as the environment variables are only evaluated during the first run, not during a restart):
$ docker stop <container_id>
$ docker rm <container_id>
* [x] Run Docker

$> docker run -d --name sonarqube \
    -p 9000:9000 \
    -e SONAR_JDBC_URL=... \
    -e SONAR_JDBC_USERNAME=... \
    -e SONAR_JDBC_PASSWORD=... \
    -v sonarqube_data:/opt/sonarqube/data \
    -v sonarqube_extensions:/opt/sonarqube/extensions \
    -v sonarqube_logs:/opt/sonarqube/logs \
    <image_name>
* [ ] Go to http://yourSonarQubeServerURL/setup and follow the setup instructions.
* [ ] Reanalyze your projects to get fresh data.

--- 

## Security considerations
None, local upgrade

## Implementation sketch

* [ ] Full upgrade steps [documentation ](https://docs.sonarqube.org/latest/setup-and-upgrade/upgrade-the-server/upgrade-guide/)

**Comment by Ephraim-G** [comment]
@apburnes I was able to successfully update the container by just pulling down the new image, albeit this process doesn't transfer over the projects which I was okay with since we have the screenshots in the drive. Similar to the steps above 1. `docker stop sonarqube` 2. `docker rm sonarqube` 3. `docker pull sonarqube` 4. `docker run -d --name sonarqube -p 9000:9000 sonarqube` 4. `docker logs sonarqube` to make sure everything looks good.

**Comment by apburnes** [comment]
@Ephraim-G do we document the steps for Pages personnel to set up sonarqube on their local machines?

**Comment by Ephraim-G** [comment]
@apburnes no official documentation, I do have steps in my notes/slack I could put a doc together to be shared and/or added to the new hire checklist if needed.
