### ISSUE TITLE
Build `s3-resource-simple` with pipeline from `common-pipelines`

### ISSUE THREAD

**Issue by jameshochadel** [cloud-gov/product#2568]
Try two different approaches :
1. fork the upstream repo and update its docker file to use our hardener image 
2.  Maintain a separate repo with a docker multistage build that pulls the relevant file form the open source repo

**Comment by dandersonsw** [comment]
This repo is actually one that we own and manage in our github (https://github.com/cloud-gov/s3-resource-simple)

**Comment by jameshochadel** [comment]
Got it — so this one probably isn't a good candidate for trying out the different approaches then. I see we also maintain a fork of the s3-resource, but there is also an [upstream version](https://github.com/concourse/s3-resource). I wonder what features we added in our 15 commits and if we could switch to using the upstream. Otherwise, there are a few we definitely haven't forked. `cfcommunity/slack-notification-resource` looks like the next most used — perhaps that?

**Comment by dandersonsw** [comment]
This pipeline is now in concourse. We may eventually want to rename the pipeline and repo from `s3-resource-simple` to `s3-simple-resource`.
