### ISSUE TITLE
Create Runtime Config for ProtoBOSH (stub)

### ISSUE THREAD

**Issue by soutenniza** [cloud-gov/product#2576]
In order to be able to deploy tooling bosh, we want a runtime config configured.

## Acceptance Criteria
* [x] WestA runtime config that matches our standards for runtime bosh release for dns

--- 

## Security considerations
None

## Implementation sketch

* [x] find the pipeline for bosh dns
* [x] Duplicate the deployment process and document in the readme

**Comment by cweibel** [comment]
Emptyvm deployment which consumed the dns runtime config for the protobosh:

```
emptyvm/0c5f3086-0369-4463-a3b4-4bbaacb72cb1:~$ sudo -i
emptyvm/0c5f3086-0369-4463-a3b4-4bbaacb72cb1:~# monit summary
The Monit daemon 5.2.5 uptime: 0m

Process 'bosh-dns'                  running
Process 'bosh-dns-resolvconf'       running
Process 'bosh-dns-healthcheck'      running
System 'system_b5629e78-9d7d-44a4-84f3-a8127dfa0528' running
```
