### ISSUE TITLE
Run gap assessment to maintain 3/17 Annual Assessment SAR delivery date

### ISSUE THREAD

**Issue by pburkholder** [cloud-gov/product#2586]
In order to continue with an Annual Assessment cadence with a recurring 3/17 SAR delivery date, we need to assess the 55 controls that are due 2024-01-17 for their 3-year assessment.

Our rough schedule is:

* September: SAP development and approval
* October: [cloud.gov](http://cloud.gov/) ARL responses
* November: interviews and testing
* December: SAR prep and delivery

```[tasklist]
### Tasks
- [ ] https://github.com/cloud-gov/product/issues/2587
```

## Security considerations
This new cadence will make for a more humane working environment.

**Comment by jameshochadel** [comment]
SAR delivered. Closing.
