### ISSUE TITLE
Delete files after running usg fix

### ISSUE THREAD

**Issue by dandersonsw** [cloud-gov/product#2596]
To make sure our images stay as small as possible we want to delete any reports generated from running `usg fix`. (In the latest version of the pipeline, `usg audit` is run after the image is built, so its artifacts are not saved back to the image filesystem.)

Acceptance Criteria
- [x] Before creating the image the files generated by `usg fix` are deleted. Do this in the same step of the Docker build so they don't appear in a lower layer.

Related to #2566

**Comment by dtamasang2** [comment]
Added `rm -rf /var/lib/usg` to build.sh to remove files created by `usg`.
