### ISSUE TITLE
Success- Create a squad-specific google group

### ISSUE THREAD

**Issue by banesssa** [cloud-gov/product#2598]
A a member of a Cloud.gov Success squad  I need a squad-specific google group so that I can easily communicate with my squad and control Cloud.gov squad records access.

**Comment by markdboyd** [comment]
Submitted REQ0801422 to create a Google group for the customer success squad

**Comment by markdboyd** [comment]
Google group is created and I've added the squad members to it:

https://groups.google.com/a/gsa.gov/g/cloud-gov-customer-success/members
