### ISSUE TITLE
Harden image cfcommunity/slack-notification-resource

### ISSUE THREAD

**Issue by jameshochadel** [cloud-gov/product#2614]
Upstream uses an Alpine base image and calls Alpine's `apk` package manager, so even if we could make the base image a build arg, it wouldn't work right. We'll either need to maintain a dockerfile that uses their file as a builder step in a multi-stage build, or fork the repo and rewrite the dockerfile to use our base image and Ubuntu tools like apt.

https://github.com/cloudfoundry-community/slack-notification-resource/blob/master/Dockerfile

**Comment by banesssa** [comment]
We need to Harden one community resource that is not from Concourse organization before we can do the SCR

**Comment by dandersonsw** [comment]
Decided to move forward with making a fork of the original repo. Doing a multi-stage image can work, but could get messy really fast depending on how many files need to be copied over. Using the forked repo we'll just need to make sure we keep up to date with the upstream repo.

We should make a ticket for the future to look into the best way to keep our forks up to date with what is in upstream. The best way may be to create a pipeline that checks the upstream repos.
