### ISSUE TITLE
Harden image cfplatformeng/concourse-pypi-resource

### ISSUE THREAD

**Issue by jameshochadel** [cloud-gov/product#2615]
External Resource: https://github.com/cf-platform-eng/concourse-pypi-resource

Dockerfile uses a python image. We should be able to use a hardened image (maybe our general resource image?) instead.

**Comment by wz-gsa** [comment]
forked to[ ](https://github.com/cloud-gov/concourse-pypi-resource)

**Comment by wz-gsa** [comment]
Worked with @soutenniza to confirm this is no longer in use and no longer needed. Resource has been removed from all relevant locations.
