### ISSUE TITLE
Harden image cftoolsmiths/cron-resource

### ISSUE THREAD

**Issue by jameshochadel** [cloud-gov/product#2616]
Need to harden `cron-resource`. Part of unblocking #2632

**Comment by dandersonsw** [comment]
This repo is archived: https://github.com/vmware-archive/cron-resource

Should we fork this one so we can keep it up to date?

**Comment by jameshochadel** [comment]
Darn, that's unfortunate. I suppose so, yes. We use this pretty widely right? And I see there's no first-party Concourse equivalent.

**Comment by dandersonsw** [comment]
We only use it in a couple of repos as far as I can tell, but it is used for some important monthly billing/tracking items. I'm not seeing any alternatives to it either, as the `time` resource doesn't let you specify running a job on the first day of the month, or anything that needs to be that specific.
