### ISSUE TITLE
Use hardened images for deploy-go-s3-broker pipeline

### ISSUE THREAD

**Issue by jameshochadel** [cloud-gov/product#2640]
Repository is located here: https://github.com/cloud-gov/cg-deploy-s3-broker

#### Pipeline Resource types
   - [x] slack-notification
   - [x] s3-iam
   - [x] git
   - [x] semver-iam
 
#### Resources that needs to be created
   - [x] cf
   - [x] server-iam

#### Pipeline built-in resources
   - [x] git
   - [x] s3

#### Images that need to be hardened
   - [x] cloudfoundry-community/cf-resource
   - [x] governmentpaas/semver-resource

**Comment by dtamasang2** [comment]
It looks like the images being used by the `deploy-go-s3-broker` pipeline have already been hardened with the exception of the `semver-iam` image.

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

- name: s3-iam
  type: docker-image
  source:
    repository: 18fgsa/s3-resource

- name: semver-iam
  type: docker-image
  source:
    repository: governmentpaas/semver-resource

**Comment by dtamasang2** [comment]
Available hardened resources have been added to the `deploy-go-s3-broker` pipeline. Placing ticket on blocked until other required resources have been hardened such as `cf` and `semver-iam`.

**Comment by dtamasang2** [comment]
All resources hardened and applied to the pipeline.
