### ISSUE TITLE
Fix git-resource Dockerfile build to run non-interactively

### ISSUE THREAD

**Issue by jameshochadel** [cloud-gov/product#2683]
The `oci-build` step of the [git-resource]() pipeline runs indefinitely because the following step prompts for interactive input:

```
#7 18.54 Setting up libpam-systemd:amd64 (249.11-0ubuntu3.9) ...
#7 18.67 debconf: unable to initialize frontend: Dialog
#7 18.67 debconf: (TERM is not set, so the dialog frontend is not usable.)
#7 18.67 debconf: falling back to frontend: Readline
#7 18.76 PAM configuration
#7 18.76 -----------------
#7 18.76 
#7 18.76 One or more of the files /etc/pam.d/common-{auth,account,password,session} have
#7 18.76 been locally modified.  Please indicate whether these local changes should be
#7 18.76 overridden using the system-provided configuration.  If you decline this
#7 18.76 option, you will need to manage your system's authentication configuration by
#7 18.76 hand.
#7 18.76 
#7 18.76 Override local changes to /etc/pam.d/common-*? [yes/no]
```

[Example failure.](https://ci.fr.cloud.gov/teams/main/pipelines/git-resource/jobs/main/builds/5)

Note that this change started when we switched to the `ubuntu-hardened` base image; it's possible that `usg fix` changed one of the files that this error refers to ("One or more of the files /etc/pam.d/common-{auth,account,password,session}"). 

A few (but probably not all) possible fixes in order of preference:

1. Figure out how to make the existing approach run without interaction. Maybe we can pass an environment variable to the docker build? Maybe, but less likely, we can pass a flag to buildkit in the `oci-image` step? 
2. Submit a contribution upstream to make this step always work without interaction.
3. Fork the repo like we forked [slack-notification-resource](https://github.com/cloud-gov/slack-notification-resource) and change the relevant instruction in the dockerfile to run non-interactively.

**Comment by jameshochadel** [comment]
The [cflinuxfs4 Dockerfile](https://github.com/cloudfoundry/cflinuxfs4/blob/main/Dockerfile) has some apt tricks that might be useful. Note the DEBIAN_FRONTEND=noninteractive.

**Comment by dandersonsw** [comment]
Fixed by adding DEBIAN_FRONTEND=noninteractive as an ARG to the Dockerfiles which use the base_image
