### ISSUE TITLE
Ship new version of cloud.gov SSP (2.03)

### ISSUE THREAD

**Issue by pburkholder** [cloud-gov/product#2689]
In order to keep our stakeholder up-to-date with our leadership structure, we need to ship a new version of the SSP with the new System Owner and minor updates.

Related to @kfoley-18F onboarding ticket at #2582

Steps:

Edit in Drive, then:

Download from Google Drive, open in Word, clean up table of contents, pagination, etc.

Save as PDF, Docusign it. We ship SSPs as PDFs so they're more or less immutable

Save as DOCX, upload back to Google Drive as the 'indev' version.

## Acceptance Criteria

* SSP has been Docusigned by:
  * [x] ISSO
  * [x] System Owner
  * [x] Product Lead or Biz Lead or Eng Supervisor
* Signed SSP delivered to
  * [x] Max
  * [x] Google Drive Archive folder
* SSP update notification (with highlights) emailed to
  * [x] cloud-gov-team
  * [x] JAB TRRs
* [x] Google Drive updated with latest .docx
  

## Security Considerations

Safe. The existence of this issue provides no useful public info to a malicious actor. Regularly 
update our SSP is good for compliance & security

**Comment by Chiakao** [comment]
v2.2 signed SSP uploaded to Max.gov and JAB/cloud.gov team notified on 9/12
