### ISSUE TITLE
Concourse db tuning

### ISSUE THREAD

**Issue by cweibel** [cloud-gov/product#2705]
In order to increase performance and reduce costs we want to look at peforming tuning on the concourse databse

## Acceptance Criteria
* [ ] Don't make it worse - this is an investigate and apply changes as discovered, validate by observing aws rds stats

--- 

## Security considerations
No, should just be scaling

## Implementation sketch

* [ ] Reindex that database `REINDEX DATABASE ATC;`
* [ ] Use cron bosh release or similar to schedule weekly reindexes, Sunday at 6am sounds like a good time
* [ ] Look over data retention available on the bosh release v concourse itself, the db is XXXGB and that seems too large by a factor of... alot.
* [ ] May need to work with Peter to find out if any of the job history retention is something needed for audit purposes

**Comment by wz-gsa** [comment]
This ticket is no longer needed
