### ISSUE TITLE
Onboard Sarah to Pages team

### ISSUE THREAD

**Issue by drewbo** [cloud-gov/product#2723]
#### Acceptance Criteria

- [x] Share [README](https://docs.google.com/document/d/17vcjJ0PB4yxCUIDoKh8TP3mYK5ArhF90SymGrITxEx0/edit)
- [x] Add to [cloud-gov-team](https://github.com/orgs/cloud-gov/teams/cloud-gov-team/members) in Github cloud-gov org.
- [x] Add to [pages-ops](https://github.com/orgs/cloud-gov/teams/pages-ops/members) in Github cloud-gov org.
- [x] Add to #cg-pages- channels in Slack as needed, and add to @cg-pages-team Slack user group
- [x] Add to daily standup, retro, and sprint planning
- [x] Ensure user has cloud.gov Pages Github project access and brief on its use
- [x] Ensure user has GPG signing set up for GitHub: https://docs.google.com/document/d/11UDxvfkhncyLEs-NUCniw2u54j4uQBqsR2SBiLYPUZc/edit (Step 8 is automatically handled via https://github.com/cloud-gov/pages-gpg-keys)
- [x] Add to Google Groups as needed
- [x] Add them as an agent to https://cloud-gov-new.zendesk.com/agent/
- [x] Add to search.usa.gov config
- [x] Add to [backups list](https://docs.google.com/document/d/17vcjJ0PB4yxCUIDoKh8TP3mYK5ArhF90SymGrITxEx0/edit#heading=h.ygis65t0w3xq) as needed
- [x] Add new user as developer to the gsa-18f-federalist cloud.gov cloudfoundry organization
- [x] Have a cloud.gov operator add to the “pages.support" group in the cloud.gov UAA by using the make-pages-admin.sh script
- [x] Have a cloud.gov operator add to the “concourse.pages” team in the cloud.gov OpsUAA by using the make-pages-ops-admin.sh script so they can access Concourse CI
- [ ] ~Add to AWS (Production GovCloud only)~
- [x] Add to cloud.gov calendar

**Comment by jameshochadel** [comment]
Authorization to onboard: https://groups.google.com/a/gsa.gov/g/cloud-gov-compliance/c/aF2vLibOUxE
See also #2725
