### ISSUE TITLE
Draft Pages Build Task SCR

### ISSUE THREAD

**Issue by drewbo** [cloud-gov/product#2735]
In order to release the Build Tasks feature in the cloud.gov Pages application, we want to determine whether an SCR is needed, and draft it.

## Acceptance Criteria
* [x] [Compliance folder](https://drive.google.com/drive/folders/1o3uSd9HreEkXYH37nhQMTbXjoKBNPKFx?usp=drive_link)
* [x] Finish rough draft
* [x] Summarize SCR for compliance lead

--- 

## Security considerations
The SCR will document security posture changes to the system

**Comment by apburnes** [comment]
Initial work complete
