### ISSUE TITLE
Run October 2023 Pages/Zendesk user, role, and org sync

### ISSUE THREAD

**Issue by svenaas** [cloud-gov/product#2744]
Monthly review to make sure cloud.gov Pages users, orgs, and roles are accurately reflected in Zendesk.

# Pages/Zendesk user, role, and org sync

## Export organization, user, and role information from Pages Admin

- In Pages Admin, navigate to the Reports section
- View the Organizations report, and download a CSV export
- View the Users report, and download a CSV export

### Organization Import

*Important! The Organizations report needs to be imported first otherwise users being added in the Users report to new organizations which don't yet exist in Zendesk will cause the job to fail*

- Download and open the CSV export in Google Sheets for editing purposes
- In the header of the first column rename "Organizations" to "names" 
- In the header of the second column rename "Agency" to "details"
- Save the sheet as an CSV
- Navigate to the Zendesk admin center 
- In the lefthand panel locate "Bulk actions" and choose "Import organizations"
- An import job report will be sent to your .gov inbox where you can view if the job was successful/unsuccesful

### User Import

- Download and open the CSV export in Google Sheets for editing purposes
- Delete all columns besides "Email" "Organizations" "Name" "Details"
*The "Name" and "Email" fields are required for importing new users, without them the entire job will fail*
- Save the sheet as an CSV
- Navigate to the Zendesk admin center 
- In the lefthand panel locate "Bulk actions" and choose "Import organizations"
- An import job report will be sent to your .gov inbox where you can view if the job was successful/unsuccesful

## Acceptance criteria

- [x] Orgs in Zendesk match current Pages orgs
- [x] Org users in Zendesk match current Pages partners users, including
  - [x] Org assignments
  - [x] Roles (org manager or not)
  - [x] Names and emails

**Comment by Ephraim-G** [comment]
@svenaas the organizations report was imported with no problem but ran into an issue when importing the users report. The user import report stated that  71 new users were created another 314 were updated and another 859 user imports failed. Now there weren't 859 users in total but the report has some blank fields in between users and some users missing the "Organization" and "Details" values. I've shared the spreadsheet with additional notes.

**Comment by svenaas** [comment]
@Ephraim-G I replied via email with more details. In Pages admin I see multiple users (both active and inactive) with no email addresses. I also see inactive users who have email addresses. I don't know what's best to do with these in ZenDesk.

**Comment by svenaas** [comment]
@Ephraim-G, am I correct that you're done with this, based on our discussion? As I understand it you've imported/updated all the orgs, and all the users with emails, and I believe that's all that you can load in. If that's correct you can go ahead and check off the tasks in Acceptance Criteria, close this issue, and change its status to Done.
