### ISSUE TITLE
Update external-domain-broker to update Postgres from 11 to 15 and fix errors in the logs

### ISSUE THREAD

**Issue by rcgottlieb** [cloud-gov/product#2753]
In order to keep the external-domain-broker up to date and functional, the Postgres version needs to be updated as well as fixing the code related to renewal of certificates which fails in certain conditions

Acceptance Criteria
 Given that Postgres is updated and verified as well as the renewal code fixed, the external-domain-broker should function without errors

Security considerations
None

Implementation sketch
* [ ] research if upgrading Postgres to 15 will remove the errors related to Postgres dependencies in the app log
* [ ] trace the errors in the CF application logs to find the root cause 
* [ ] fix and test the code
* [ ] create a new release for the external-domain-broker

**Comment by rcgottlieb** [comment]
Breadcrumbs for future me or someone else:
I figured out that the Dockerfile that uses Postgres 11 is just for development. This should fix the test step.
We would have to backup the current production database and restore it to a new database running Postgres 15 to update from Postgres 11. 

The external domain broker should build once the test step is fixed, if not then that's where the root cause will need to be investigated.

**Comment by markdboyd** [comment]
This was fixed via https://github.com/cloud-gov/external-domain-broker/pull/279 and the pipeline is working now
