### ISSUE TITLE
Container Scanning: SSP Updates for "Hardened Images"

### ISSUE THREAD

**Issue by jameshochadel** [cloud-gov/product#2761]
Based on the [FedRAMP Vulnerability Scanning Requirements for Containers](https://drive.google.com/open?id=15u9HW0fgBGqoTbokyQIdTVQShFfrmpkC&usp=drive_fs), we must update the following controls related to the "Hardened Images" section:

* [x] CM-6
* [x] SC-2
* [x] SC-3
* [x] SC-4
* [x] SC-6
* [x] SC-28
* [x] SC-39

**Comment by dandersonsw** [comment]
This was marked done by James back on Nov 30, 2023
