### ISSUE TITLE
Evaluate customer impact of deprecating current service

### ISSUE THREAD

**Issue by banesssa** [cloud-gov/product#2769]

**Comment by pburkholder** [comment]
Done. @jameshochadel completed this work in the Spring of 2023. We determined that many of our cloud.gov Pages customers rely on the cloud.gov IdP, and don't have the resources to provide us with an Agency/Office Idp. So, retiring our current service would not meet their needs.

Related: Neither do they have the resources to "accept the risk" of using an IdP that's not in boundary.
