### ISSUE TITLE
Add common build errors & resolutions to the "build errors" documentation page.

### ISSUE THREAD

**Issue by Ephraim-G** [cloud-gov/product#2866]
The cloud.gov pages [build error documentation](https://cloud.gov/pages/documentation/build-errors/) could use a rework but for now there are a few common build errors that users run into that are undocumented. Having these issues visible in a public space will enable users to know what is occurring and take action, either through their own doing or via pages support. 

## Acceptance Criteria
* [ ] Create more robust error documentation by adding common engineer known/user reported issues.
* [ ] For each known issue state a way a user can remediate it or what support will have to do on their behalf
--- 

## Security considerations
Do not expose any secrets or confidential cloud.gov Pages data.

**Comment by apburnes** [comment]
Build errors are bit too unique for documentation
