### ISSUE TITLE
Fork and scan the cloudfoundry-community/cf-resource repo

### ISSUE THREAD

**Issue by dandersonsw** [cloud-gov/product#2901]
We want to fork the [github.com/cloudfoundry-community/cf-resource](http://github.com/cloudfoundry-community/cf-resource) repo

## Acceptance Criteria
* [x] Fork the cloudfoundry-community/cf-resource repo
* [x] Run scan tooling against the repo
* [x] Address security concerns
* [x] Add dependabot.yml
* [x] Communicate forked repo being ready to platform and pages teams

--- 

## Security considerations
Forking this repo for now until we have a better solution. This allows us more control over what we are pulling into our system.

**Comment by wz-gsa** [comment]
https://github.com/cloud-gov/common-pipelines/pull/60
