### ISSUE TITLE
Fork and scan the cloudfoundry-community/cron-boshrelease repo

### ISSUE THREAD

**Issue by dandersonsw** [cloud-gov/product#2902]
We want to fork the [github.com/cloudfoundry-community/cron-boshrelease](http://github.com/cloudfoundry-community/cron-boshrelease) repo

## Acceptance Criteria
* [x] Fork the cloudfoundry-community/cron-boshrelease repo
* [x] Run scan tooling against the repo
* [x] Address security concerns
* [x] Add dependabot.yml
* [x] Communicate forked repo being ready to platform and pages teams

--- 

## Security considerations
Forking this repo for now until we have a better solution. This allows us more control over what we are pulling into our system.

**Comment by rcgottlieb** [comment]
Finished by forking the repo, making the changes from cloudfoundry-community to cloud-gov and updating cg-deploy-bosh to use the new fork name
