### ISSUE TITLE
Remove the bionic references

### ISSUE THREAD

**Issue by cweibel** [cloud-gov/product#2944]
As general housekeeping, we should remove references to bionic stemcells

## Acceptance Criteria
* [x] GIVEN a bosh director controlled by cg-deploy-bosh, when a director is deployed, remove the bionic references in the runtime config.  Verified via deployment to all bosh directors and running `bosh rc` and observing a lack of bionic references
* [x] GIVEN a pipeline controlled by cg-deploy-bosh, remove bionic-specific releases such as cg-s3-fisma-release, cg-s3-snort-release and cg-s3-awslogs-bionic-release

--- 

## Security considerations
None, cleanup of no longer used resources

## Implementation sketch

* [x] Remove bionic references in https://github.com/cloud-gov/cg-deploy-bosh/blob/main/runtime-config/runtime.yml
* [x] The script which generates the pipeline jobs to use the older bionic releases is at https://github.com/cloud-gov/cg-deploy-bosh/blob/main/ci/update-runtime-config.sh with the inputs defined at https://github.com/cloud-gov/cg-deploy-bosh/blob/main/ci/update-runtime-config.yml, removed the unused ones:  cg-s3-fisma-release, cg-s3-snort-release and cg-s3-awslogs-bionic-release
* [x] Verify with a `bosh deps` command that none of the underlying removed releases from the previous step are used by the tooling, dev, stage, prod directors
* [x] Deploy to master
* [x] Deploy to tooling
* [x] Deploy to dev
* [x] Deploy to staging
* [x] Deploy to prod

**Comment by rcgottlieb** [comment]
All three references were removed, as were any references to Bionic.
