### ISSUE TITLE
SPIKE: Add EFS volume brokered service

### ISSUE THREAD

**Issue by markdboyd** [cloud-gov/product#3102]
## Background

Customers or potential customers often are interested in running software on cloud.gov that requires on-disk storage. Currently, cloud.gov cannot really support this type of software since the app containers on cloud.gov are ephemeral and the storage is wiped on restart. Plus, there is a hard limit on disk size in containers of 7 GB.

One option to support durable on-disk storage for cloud.gov apps is adding support for EFS volumes that could be mounted to VMs and accessible to apps.

Cloud Foundry in fact used to support EFS volumes directly, but the code is no longer maintained: https://github.com/cloudfoundry-attic/efs-volume-release

We should research whether we could run this EFS volume release, with updates as necessary, to support EFS volumes as a brokered service offering on the platform.

## To do 

- [ ] Successfully deploy EFS volume release in dev
- [ ] Confirm that you can create an EFS volume through the deployed broker
- [ ] Confirm that you see the created EFS volume in AWS
- [ ] Confirm that you can create a cloud.gov app which writes data to the EFS volume
- [ ] Confirm that the EFS volume and data remain bound to the app even after restart

**Comment by JasonTheMain** [comment]
We were able to make 2 branches, one called make-blobs which is based on the NFS volume release which has community backing and one named old-way which is the efsbroker from the cloudfoundry attic. 

The Attic one has been updated for the changing Go dependencies and is able to make a efs instance in aws and a volume in the diego cell. It fails to mount and in theory needs mounting fixed to be able to make a bindable instance. Currently with that and a few other small bugs it is unable to make or delete a instance succefully.

The NFS based branch called make-blobs is able to make a instance in AWS. it is comparable to the nfs release with slight differences to account for AWS. It can make an instance and bind it for the broker but the driver does not make a mountable volume corrrectly and if passed the right OPS values it might work succefully. currently it doesn;t pass a source to the driver which is where the driver is stuck.
