### ISSUE TITLE
Upgrade customer postgres DBs (research-based task)

### ISSUE THREAD

**Issue by mogul** [cloud-gov/product#918]
In order to help our customers keep their systems secure and compliant, we want to get all customers to be using up-to-date versions of Postgres.

## Acceptance Criteria
- [ ] WHEN I run scans of customer DBs THEN I see no findings indicating unsupported/insecure Postgres versions were found

## Implementation sketch
- Make newest version of postgres available in a plan
- Announce the change to customers and give them directions on how to migrate
- NTH: Ping customers periodically who haven't upgraded

**Comment by pburkholder** [comment]
Re-opening as this has yet to be resolved. More particularly, we need the BOSH and CCDB instances updated to address a POA&M.

**Comment by pburkholder** [comment]
@mogul or @sharms -- Is there prior work on this about what the difficulties were in getting RDS instances to update through AWS maintenance?

**Comment by mogul** [comment]
Not that I recall but this is a level of detail below where I was floating when I was on the team.

**Comment by karareinsel** [comment]
Suggest time-boxing (4 hours max) this work as a research task.

**Comment by karareinsel** [comment]
Reach out to @pburkholder to pair on this issue.
